var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var f=a.length,g=0;g<f;g++){var h=a[g];if(b.call(c,h,g,a))return{i:g,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,f){if(b){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var g=a[f];g in c||(c[g]={});c=c[g]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");function everyTime(a){a=$("input[name=v_"+a.name+"]");a.val("*");a.change()}
function unAppoint(a){var b=a.name;a="?";"year"==b&&(a="");b=$("input[name=v_"+b+"]");b.val(a);b.change()}function cycle(a){var b=a.name,c=$(a).parent().find(".numberspinner");a=c.eq(0).numberspinner("getValue");c=c.eq(1).numberspinner("getValue");b=$("input[name=v_"+b+"]");b.val(a+"-"+c);b.change()}function startOn(a){var b=a.name,c=$(a).parent().find(".numberspinner");a=c.eq(0).numberspinner("getValue");c=c.eq(1).numberspinner("getValue");b=$("input[name=v_"+b+"]");b.val(a+"/"+c);b.change()}
function lastDay(a){a=$("input[name=v_"+a.name+"]");a.val("L");a.change()}function weekOfDay(a){var b=a.name,c=$(a).parent().find(".numberspinner");a=c.eq(0).numberspinner("getValue");c=c.eq(1).numberspinner("getValue");b=$("input[name=v_"+b+"]");b.val(a+"#"+c);b.change()}function lastWeek(a){var b=$("input[name=v_"+a.name+"]");a=$(a).parent().find(".numberspinner").eq(0).numberspinner("getValue");b.val(a+"L");b.change()}
function workDay(a){var b=a.name;a=$(a).parent().find(".numberspinner").eq(0).numberspinner("getValue");b=$("input[name=v_"+b+"]");b.val(a+"W");b.change()}function getQueryString(a,b){a=new RegExp("(^|&)"+a+"=([^&]*)(&|$)","i");b=b&&""!=b?b.substring(b.indexOf("?")):window.location.search;r=b.substr(1).match(a);return null!=r?unescape(r[2]):null}
$(function(){$(".numberspinner").numberspinner({onChange:function(){$(this).closest("div.line").children().eq(0).click()}});var a=$("#cron");a.change(function(){btnFan();$.ajax({type:"post",url:(window.ctx||getQueryString("ctx"))+"/job/checkCron",dataType:"json",data:{cron:$("#cron").val()},success:function(a){$("#runTime").html(a.message)}})});var b=$("input[name^='v_']");b.change(function(){var d=[];b.each(function(){d.push(this.value)});var c=0;$(".tabs>li").each(function(a,b){if($(b).hasClass("tabs-selected"))return c=
a,!1});3==c&&(d[c+2]="?"==d[c]?"1":"?");5==c&&(d[c-2]="?"==d[c]?"1":"?");"?"==d[3]&&"?"==d[5]&&(d[3]="1");for(var e=c;1<=e;e--)if("*"!=d[e]&&"*"==d[e-1]||"6"==c)4==e?d[e-1]="1":3>=e&&(d[e-1]="0");if("*"==d[c])for(e=c+1;e<d.length;e++)d[e]=5==e?"?":"*";a.val(d.join(" ")).change()});var c=$(".secondList").children();$("#sencond_appoint").click(function(){this.checked&&(0==$(c).filter(":checked").length&&$(c.eq(0)).attr("checked",!0),c.eq(0).change())});c.change(function(){if($("#sencond_appoint").prop("checked")){var a=
[];c.each(function(){this.checked&&a.push(this.value)});var b="?";0<a.length&&59>a.length?b=a.join(","):59==a.length&&(b="*");var e=$("input[name=v_second]");e.val(b);e.change()}});var f=$(".minList").children();$("#min_appoint").click(function(){this.checked&&(0==$(f).filter(":checked").length&&$(f.eq(0)).attr("checked",!0),f.eq(0).change())});f.change(function(){if($("#min_appoint").prop("checked")){var a=[];f.each(function(){this.checked&&a.push(this.value)});var b="?";0<a.length&&59>a.length?
b=a.join(","):59==a.length&&(b="*");var c=$("input[name=v_min]");c.val(b);c.change()}});var g=$(".hourList").children();$("#hour_appoint").click(function(){this.checked&&(0==$(g).filter(":checked").length&&$(g.eq(0)).attr("checked",!0),g.eq(0).change())});g.change(function(){if($("#hour_appoint").prop("checked")){var a=[];g.each(function(){this.checked&&a.push(this.value)});var b="?";0<a.length&&24>a.length?b=a.join(","):24==a.length&&(b="*");var c=$("input[name=v_hour]");c.val(b);c.change()}});var h=
$(".dayList").children();$("#day_appoint").click(function(){this.checked&&(0==$(h).filter(":checked").length&&$(h.eq(0)).attr("checked",!0),h.eq(0).change())});h.change(function(){if($("#day_appoint").prop("checked")){var a=[];h.each(function(){this.checked&&a.push(this.value)});var b="?";0<a.length&&31>a.length?b=a.join(","):31==a.length&&(b="*");var c=$("input[name=v_day]");c.val(b);c.change()}});var k=$(".mouthList").children();$("#mouth_appoint").click(function(){this.checked&&(0==$(k).filter(":checked").length&&
$(k.eq(0)).attr("checked",!0),k.eq(0).change())});k.change(function(){if($("#mouth_appoint").prop("checked")){var a=[];k.each(function(){this.checked&&a.push(this.value)});var b="?";0<a.length&&12>a.length?b=a.join(","):12==a.length&&(b="*");var c=$("input[name=v_mouth]");c.val(b);c.change()}});var l=$(".weekList").children();$("#week_appoint").click(function(){this.checked&&(0==$(l).filter(":checked").length&&$(l.eq(0)).attr("checked",!0),l.eq(0).change())});l.change(function(){if($("#week_appoint").prop("checked")){var a=
[];l.each(function(){this.checked&&a.push(this.value)});var b="?";0<a.length&&7>a.length?b=a.join(","):7==a.length&&(b="*");var c=$("input[name=v_week]");c.val(b);c.change()}})});
function btnFan(){var a=$("#cron").val();""==a&&(a="* * * * * ? *",$("#cron").val(a).change());a=a.split(" ");$("input[name=v_second]").val(a[0]);$("input[name=v_min]").val(a[1]);$("input[name=v_hour]").val(a[2]);$("input[name=v_day]").val(a[3]);$("input[name=v_mouth]").val(a[4]);$("input[name=v_week]").val(a[5]);initObj(a[0],"second");initObj(a[1],"min");initObj(a[2],"hour");initDay(a[3]);initMonth(a[4]);initWeek(a[5]);6<a.length&&($("input[name=v_year]").val(a[6]),initYear(a[6]))}
function initObj(a,b){var c=$("input[name='"+b+"'");if("*"==a)c.eq(0).attr("checked","checked");else if(1<a.split("-").length)a=a.split("-"),c.eq(1).attr("checked","checked"),$("#"+b+"Start_0").numberspinner("setValue",a[0]),$("#"+b+"End_0").numberspinner("setValue",a[1]);else if(1<a.split("/").length)a=a.split("/"),c.eq(2).attr("checked","checked"),$("#"+b+"Start_1").numberspinner("setValue",a[0]),$("#"+b+"End_1").numberspinner("setValue",a[1]);else if(c.eq(3).attr("checked","checked"),"?"!=a)for(a=
a.split(","),c=0;c<a.length;c++)$("."+b+"List input[value='"+a[c]+"']").attr("checked","checked")}
function initDay(a){var b=$("input[name='day'");if("*"==a)b.eq(0).attr("checked","checked");else if("?"==a)b.eq(1).attr("checked","checked");else if(1<a.split("-").length)a=a.split("-"),b.eq(2).attr("checked","checked"),$("#dayStart_0").numberspinner("setValue",a[0]),$("#dayEnd_0").numberspinner("setValue",a[1]);else if(1<a.split("/").length)a=a.split("/"),b.eq(3).attr("checked","checked"),$("#dayStart_1").numberspinner("setValue",a[0]),$("#dayEnd_1").numberspinner("setValue",a[1]);else if(1<a.split("W").length)a=
a.split("W"),b.eq(4).attr("checked","checked"),$("#dayStart_2").numberspinner("setValue",a[0]);else if("L"==a)b.eq(5).attr("checked","checked");else for(b.eq(6).attr("checked","checked"),a=a.split(","),b=0;b<a.length;b++)$(".dayList input[value='"+a[b]+"']").attr("checked","checked")}
function initMonth(a){var b=$("input[name='mouth'");if("*"==a)b.eq(0).attr("checked","checked");else if(1<a.split("-").length)a=a.split("-"),b.eq(1).attr("checked","checked"),$("#mouthStart_0").numberspinner("setValue",a[0]),$("#mouthEnd_0").numberspinner("setValue",a[1]);else if(1<a.split("/").length)a=a.split("/"),b.eq(2).attr("checked","checked"),$("#mouthStart_1").numberspinner("setValue",a[0]),$("#mouthEnd_1").numberspinner("setValue",a[1]);else for(b.eq(3).attr("checked","checked"),a=a.split(","),
b=0;b<a.length;b++)$(".mouthList input[value='"+a[b]+"']").attr("checked","checked")}
function initWeek(a){var b=$("input[name='week'");if("*"==a)b.eq(0).attr("checked","checked");else if("?"==a)b.eq(1).attr("checked","checked");else if(1<a.split("-").length)a=a.split("-"),b.eq(2).attr("checked","checked"),$("#weekStart_0").numberspinner("setValue",a[0]),$("#weekEnd_0").numberspinner("setValue",a[1]);else if(1<a.split("#").length)a=a.split("#"),b.eq(3).attr("checked","checked"),$("#weekStart_1").numberspinner("setValue",a[0]),$("#weekEnd_1").numberspinner("setValue",a[1]);else if(1<
a.split("L").length)a=a.split("L"),b.eq(4).attr("checked","checked"),$("#weekStart_2").numberspinner("setValue",a[0]);else for(b.eq(5).attr("checked","checked"),a=a.split(","),b=0;b<a.length;b++)$(".weekList input[value='"+a[b]+"']").attr("checked","checked")}
function initYear(a){var b=$("input[name='year'");"*"==a?b.eq(1).attr("checked","checked"):1<a.split("-").length&&(a=a.split("-"),b.eq(2).attr("checked","checked"),$("#yearStart_0").numberspinner("setValue",a[0]),$("#yearEnd_0").numberspinner("setValue",a[1]))};
