/*
 WebUploader 0.1.5 */
(function(t,p){var C={},g=function(a,b){var d;if("string"===typeof a)return k(a);var h=[];var f=a.length;for(d=0;d<f;d++)h.push(k(a[d]));return b.apply(null,h)},l=function(a,b,d){2===arguments.length&&(d=b,b=null);g(b||[],function(){var h=arguments,b={exports:d};"function"===typeof d&&(h.length||(h=[g,b.exports,b]),h=d.apply(null,h),void 0!==h&&(b.exports=h));C[a]=b.exports})},k=function(a){var b=C[a]||t[a];if(!b)throw Error("`"+a+"` is undefined");return b},c=function(a){var b,d,h;var f=function(a){return a&&
a.charAt(0).toUpperCase()+a.substr(1)};for(b in C){var c=a;if(C.hasOwnProperty(b)){var r=b.split("/");for(h=f(r.pop());d=f(r.shift());)c[d]=c[d]||{},c=c[d];c[h]=C[b]}}return a},b=function(a){t.__dollar=a;return c(p(t,l,g))};if("object"===typeof module&&"object"===typeof module.exports)module.exports=b();else if("function"===typeof define&&define.amd)define(["jquery"],b);else{var a=t.WebUploader;t.WebUploader=b();t.WebUploader.noConflict=function(){t.WebUploader=a}}})(window,function(t,p,C){p("dollar-third",
[],function(){var g=t.__dollar||t.jQuery||t.Zepto;if(!g)throw Error("jQuery or Zepto not found!");return g});p("dollar",["dollar-third"],function(g){return g});p("promise-builtin",["dollar"],function(g){function l(c){var b=[],a=!c&&[],f=function(e){m=e;d=!0;r=n||0;n=0;z=b.length;for(h=!0;b&&r<z;r++)b[r].apply(e[0],e[1]);h=!1;b&&(a?a.length&&f(a.shift()):b=[])},e={add:function(){if(b){var a=b.length;(function y(a){g.each(a,function(a,d){a=g.type(d);"function"===a?b.push(d):d&&d.length&&"string"!==
a&&y(d)})})(arguments);h?z=b.length:m&&(n=a,f(m))}return this},disable:function(){b=a=m=void 0;return this},lock:function(){a=void 0;m||e.disable();return this},fireWith:function(e,c){!b||d&&!a||(c=c||[],c=[e,c.slice?c.slice():c],h?a.push(c):f(c));return this},fire:function(){e.fireWith(this,arguments);return this}},d,h,n,z,r,m;return e}function k(c){var b=[["resolve","done",l(!0),"resolved"],["reject","fail",l(!0),"rejected"],["notify","progress",l()]],a="pending",f={state:function(){return a},always:function(){e.done(arguments).fail(arguments);
return this},then:function(){var a=arguments;return k(function(d){g.each(b,function(b,h){var c=h[0],n=g.isFunction(a[b])&&a[b];e[h[1]](function(){var a;if((a=n&&n.apply(this,arguments))&&g.isFunction(a.promise))a.promise().done(d.resolve).fail(d.reject).progress(d.notify);else d[c+"With"](this===f?d.promise():this,n?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=a?g.extend(a,f):f}},e={};f.pipe=f.then;g.each(b,function(d,h){var c=h[2],z=h[3];f[h[1]]=c.add;z&&c.add(function(){a=
z},b[d^1][2].disable,b[2][2].lock);e[h[0]]=function(){e[h[0]+"With"](this===e?f:this,arguments);return this};e[h[0]+"With"]=c.fireWith});f.promise(e);c&&c.call(e,e);return e}return{Deferred:k,isPromise:function(c){return c&&"function"===typeof c.then},when:function(c){var b=0,a=[].slice,f=a.call(arguments),e=f.length,d=1!==e||c&&g.isFunction(c.promise)?e:0,h=1===d?c:k(),n=function(b,f,e){return function(c){f[b]=this;e[b]=1<arguments.length?a.call(arguments):c;e===r?h.notifyWith(f,e):--d||h.resolveWith(f,
e)}},z;if(1<e){var r=Array(e);var m=Array(e);for(z=Array(e);b<e;b++)f[b]&&g.isFunction(f[b].promise)?f[b].promise().done(n(b,z,f)).fail(h.reject).progress(n(b,m,r)):--d}d||h.resolveWith(z,f);return h.promise()}}});p("promise",["promise-builtin"],function(g){return g});p("base",["dollar","promise"],function(g,l){function k(a,d){return function(){return a.apply(d,arguments)}}function c(a){if(Object.create)return Object.create(a);var d=function(){};d.prototype=a;return new d}var b=function(){},a=Function.call,
f=l.Deferred,e=l.isPromise;l=l.when;var d=function(a){var d={},b=a.match(/WebKit\/([\d.]+)/),h=a.match(/Chrome\/([\d.]+)/)||a.match(/CriOS\/([\d.]+)/),f=a.match(/MSIE\s([\d\.]+)/)||a.match(/(?:trident)(?:.*rv:([\w.]+))?/i),e=a.match(/Firefox\/([\d.]+)/),c=a.match(/Safari\/([\d.]+)/);a=a.match(/OPR\/([\d.]+)/);b&&(d.webkit=parseFloat(b[1]));h&&(d.chrome=parseFloat(h[1]));f&&(d.ie=parseFloat(f[1]));e&&(d.firefox=parseFloat(e[1]));c&&(d.safari=parseFloat(c[1]));a&&(d.opera=parseFloat(a[1]));return d}(navigator.userAgent),
h=function(a){var d={},b=a.match(/(?:Android);?[\s\/]+([\d.]+)?/);a=a.match(/(?:iPad|iPod|iPhone).*OS\s([\d_]+)/);b&&(d.android=parseFloat(b[1]));a&&(d.ios=parseFloat(a[1].replace(/_/g,".")));return d}(navigator.userAgent);var n=t.console?k(console.log,console):b;return{version:"0.1.5",$:g,Deferred:f,isPromise:e,when:l,browser:d,os:h,inherits:function(a,d,b){if("function"===typeof d){var h=d;d=null}else h=d&&d.hasOwnProperty("constructor")?d.constructor:function(){return a.apply(this,arguments)};
g.extend(!0,h,a,b||{});h.__super__=a.prototype;h.prototype=c(a.prototype);d&&g.extend(!0,h.prototype,d);return h},noop:b,bindFn:k,log:n,nextTick:function(){return function(a){setTimeout(a,1)}}(),slice:function(d){return function(){return a.apply(d,arguments)}}([].slice),guid:function(){var a=0;return function(d){for(var b=(+new Date).toString(32),h=0;5>h;h++)b+=Math.floor(65535*Math.random()).toString(32);return(d||"wu_")+b+(a++).toString(32)}}(),formatSize:function(a,d,b){var h;for(b=b||["B","K",
"M","G","TB"];(h=b.shift())&&1024<a;)a/=1024;return("B"===h?a:a.toFixed(d||2))+h}}});p("mediator",["base"],function(g){function l(a,h,f,e){return b.grep(a,function(a){return a&&(!h||a.e===h)&&(!f||a.cb===f||a.cb._cb===f)&&(!e||a.ctx===e)})}function k(a,h,e){b.each((a||"").split(f),function(a,d){e(d,h)})}function c(a,b){for(var d=!1,h=-1,f=a.length,e;++h<f;)if(e=a[h],!1===e.cb.apply(e.ctx2,b)){d=!0;break}return!d}var b=g.$,a=[].slice,f=/\s+/;var e={on:function(a,b,f){var d=this;if(!b)return this;var h=
this._events||(this._events=[]);k(a,b,function(a,b){a={e:a};a.cb=b;a.ctx=f;a.ctx2=f||d;a.id=h.length;h.push(a)});return this},once:function(a,b,f){var d=this;if(!b)return d;k(a,b,function(a,b){var h=function(){d.off(a,h);return b.apply(f||d,arguments)};h._cb=b;d.on(a,h,f)});return d},off:function(a,h,f){var d=this._events;if(!d)return this;if(!a&&!h&&!f)return this._events=[],this;k(a,h,function(a,h){b.each(l(d,a,h,f),function(){delete d[this.id]})});return this},trigger:function(d){if(!this._events||
!d)return this;var b=a.call(arguments,1);var f=l(this._events,d);var e=l(this._events,"all");return c(f,b)&&c(e,arguments)}};return b.extend({installTo:function(a){return b.extend(a,e)}},e)});p("uploader",["base","mediator"],function(g,l){function k(b){this.options=c.extend(!0,{},k.options,b);this._init(this.options)}var c=g.$;k.options={};l.installTo(k.prototype);c.each({upload:"start-upload",stop:"stop-upload",getFile:"get-file",getFiles:"get-files",addFile:"add-file",addFiles:"add-file",sort:"sort-files",
removeFile:"remove-file",cancelFile:"cancel-file",skipFile:"skip-file",retry:"retry",isInProgress:"is-in-progress",makeThumb:"make-thumb",md5File:"md5-file",getDimension:"get-dimension",addButton:"add-btn",predictRuntimeType:"predict-runtime-type",refresh:"refresh",disable:"disable",enable:"enable",reset:"reset"},function(b,a){k.prototype[b]=function(){return this.request(a,arguments)}});c.extend(k.prototype,{state:"pending",_init:function(b){var a=this;a.request("init",b,function(){a.state="ready";
a.trigger("ready")})},option:function(b,a){var f=this.options;if(1<arguments.length)c.isPlainObject(a)&&c.isPlainObject(f[b])?c.extend(f[b],a):f[b]=a;else return b?f[b]:f},getStats:function(){var b=this.request("get-stats");return b?{successNum:b.numOfSuccess,progressNum:b.numOfProgress,cancelNum:b.numOfCancel,invalidNum:b.numOfInvalid,uploadFailNum:b.numOfUploadFailed,queueNum:b.numOfQueue,interruptNum:b.numofInterrupt}:{}},trigger:function(b){var a=[].slice.call(arguments,1),f=this.options,e="on"+
b.substring(0,1).toUpperCase()+b.substring(1);return!1===l.trigger.apply(this,arguments)||c.isFunction(f[e])&&!1===f[e].apply(this,a)||c.isFunction(this[e])&&!1===this[e].apply(this,a)||!1===l.trigger.apply(l,[this,b].concat(a))?!1:!0},destroy:function(){this.request("destroy",arguments);this.off()},request:g.noop});g.create=k.create=function(b){return new k(b)};return g.Uploader=k});p("runtime/runtime",["base","mediator"],function(g,l){function k(a){this.options=c.extend({container:document.body},
a);this.uid=g.guid("rt_")}var c=g.$,b={},a=function(a){for(var b in a)if(a.hasOwnProperty(b))return b;return null};c.extend(k.prototype,{getContainer:function(){if(this._container)return this._container;var a=c(this.options.container||document.body);var b=c(document.createElement("div"));b.attr("id","rt_"+this.uid);b.css({position:"absolute",top:"0px",left:"0px",width:"1px",height:"1px",overflow:"hidden"});a.append(b);a.addClass("webuploader-container");this._container=b;this._parent=a;return b},
init:g.noop,exec:g.noop,destroy:function(){this._container&&this._container.remove();this._parent&&this._parent.removeClass("webuploader-container");this.off()}});k.orders="html5,flash";k.addRuntime=function(a,e){b[a]=e};k.hasRuntime=function(f){return!(f?!b[f]:!a(b))};k.create=function(f,e){e=e||k.orders;c.each(e.split(/\s*,\s*/g),function(){if(b[this])return d=this,!1});var d=d||a(b);if(!d)throw Error("Runtime Error");return new b[d](f)};l.installTo(k.prototype);return k});p("runtime/client",["base",
"mediator","runtime/runtime"],function(g,l,k){function c(a,f){var e=g.Deferred(),d;this.uid=g.guid("client_");this.runtimeReady=function(a){return e.done(a)};this.connectRuntime=function(a,c){if(d)throw Error("already connected!");e.done(c);"string"===typeof a&&b.get(a)&&(d=b.get(a));(d=d||b.get(null,f))?(g.$.extend(d.options,a),d.__promise.then(e.resolve),d.__client++):(d=k.create(a,a.runtimeOrder),d.__promise=e.promise(),d.once("ready",e.resolve),d.init(),b.add(d),d.__client=1);f&&(d.__standalone=
f);return d};this.getRuntime=function(){return d};this.disconnectRuntime=function(){d&&(d.__client--,0>=d.__client&&(b.remove(d),delete d.__promise,d.destroy()),d=null)};this.exec=function(){if(d){var b=g.slice(arguments);a&&b.unshift(a);return d.exec.apply(this,b)}};this.getRuid=function(){return d&&d.uid};this.destroy=function(a){return function(){a&&a.apply(this,arguments);this.trigger("destroy");this.off();this.exec("destroy");this.disconnectRuntime()}}(this.destroy)}var b=function(){var a={};
return{add:function(b){a[b.uid]=b},get:function(b,e){var d;if(b)return a[b];for(d in a)if(!e||!a[d].__standalone)return a[d];return null},remove:function(b){delete a[b.uid]}}}();l.installTo(c.prototype);return c});p("lib/blob",["base","runtime/client"],function(g,l){function k(c,b){this.source=b;this.ruid=c;this.size=b.size||0;!b.type&&this.ext&&~"jpg,jpeg,png,gif,bmp".indexOf(this.ext)?this.type="image/"+("jpg"===this.ext?"jpeg":this.ext):this.type=b.type||"application/octet-stream";l.call(this,
"Blob");this.uid=b.uid||this.uid;c&&this.connectRuntime(c)}g.inherits(l,{constructor:k,slice:function(c,b){return this.exec("slice",c,b)},getSource:function(){return this.source}});return k});p("lib/file",["base","lib/blob"],function(g,l){function k(a,f){this.name=f.name||"untitled"+c++;var e=b.exec(f.name)?RegExp.$1.toLowerCase():"";!e&&f.type&&(e=/\/(jpg|jpeg|png|gif|bmp)$/i.exec(f.type)?RegExp.$1.toLowerCase():"",this.name+="."+e);this.ext=e;this.lastModifiedDate=f.lastModifiedDate||(new Date).toLocaleString();
l.apply(this,arguments)}var c=1,b=/\.([^.]+)$/;return g.inherits(l,k)});p("lib/filepicker",["base","runtime/client","lib/file"],function(g,l,k){function c(a){a=this.options=b.extend({},c.options,a);a.container=b(a.id);if(!a.container.length)throw Error("\u6309\u94ae\u6307\u5b9a\u9519\u8bef");a.innerHTML=a.innerHTML||a.label||a.container.html()||"";a.button=b(a.button||document.createElement("div"));a.button.html(a.innerHTML);a.container.html(a.button);l.call(this,"FilePicker",!0)}var b=g.$;c.options=
{button:null,container:null,label:null,innerHTML:null,multiple:!0,accept:null,name:"file"};g.inherits(l,{constructor:c,init:function(){var a=this,f=a.options,e=f.button;e.addClass("webuploader-pick");a.on("all",function(d){switch(d){case "mouseenter":e.addClass("webuploader-pick-hover");break;case "mouseleave":e.removeClass("webuploader-pick-hover");break;case "change":d=a.exec("getFiles"),a.trigger("select",b.map(d,function(d){d=new k(a.getRuid(),d);d._refer=f.container;return d}),f.container)}});
a.connectRuntime(f,function(){a.refresh();a.exec("init",f);a.trigger("ready")});this._resizeHandler=g.bindFn(this.refresh,this);b(t).on("resize",this._resizeHandler)},refresh:function(){var a=this.getRuntime().getContainer(),b=this.options.button,e=b.outerWidth?b.outerWidth():b.width(),d=b.outerHeight?b.outerHeight():b.height();b=b.offset();e&&d&&a.css({bottom:"auto",right:"auto",width:e+"px",height:d+"px"}).offset(b)},enable:function(){this.options.button.removeClass("webuploader-pick-disable");
this.refresh()},disable:function(){var a=this.options.button;this.getRuntime().getContainer().css({top:"-99999px"});a.addClass("webuploader-pick-disable")},destroy:function(){var a=this.options.button;b(t).off("resize",this._resizeHandler);a.removeClass("webuploader-pick-disable webuploader-pick-hover webuploader-pick")}});return c});p("widgets/widget",["base","uploader"],function(g,l){function k(a){if(!a)return!1;var d=a.length,h=b.type(a);return 1===a.nodeType&&d?!0:"array"===h||"function"!==h&&
"string"!==h&&(0===d||"number"===typeof d&&0<d&&d-1 in a)}function c(a){this.owner=a;this.options=a.options}var b=g.$,a=l.prototype._init,f=l.prototype.destroy,e={},d=[];b.extend(c.prototype,{init:g.noop,invoke:function(a,d){var h=this.responseMap;return h&&a in h&&h[a]in this&&b.isFunction(this[h[a]])?this[h[a]].apply(this,d):e},request:function(){return this.owner.request.apply(this.owner,arguments)}});b.extend(l.prototype,{_init:function(){var h=this,f=h._widgets=[],e=h.options.disableWidgets||
"";b.each(d,function(a,d){e&&~e.indexOf(d._name)||f.push(new d(h))});return a.apply(h,arguments)},request:function(a,d,b){var h=0,f=this._widgets,c=f&&f.length,n=[],w=[];for(d=k(d)?d:[d];h<c;h++){var y=f[h];y=y.invoke(a,d);y!==e&&(g.isPromise(y)?w.push(y):n.push(y))}return b||w.length?(a=g.when.apply(g,w),d=a.pipe?"pipe":"then",a[d](function(){var a=g.Deferred(),d=arguments;1===d.length&&(d=d[0]);setTimeout(function(){a.resolve(d)},1);return a.promise()})[b?d:"done"](b||g.noop)):n[0]},destroy:function(){f.apply(this,
arguments);this._widgets=null}});l.register=c.register=function(a,f){var h={init:"init",destroy:"destroy",name:"anonymous"};1===arguments.length?(f=a,b.each(f,function(a){"_"===a[0]||"name"===a?"name"===a&&(h.name=f.name):h[a.replace(/[A-Z]/g,"-$&").toLowerCase()]=a})):h=b.extend(h,a);f.responseMap=h;var e=g.inherits(c,f);e._name=h.name;d.push(e);return e};l.unRegister=c.unRegister=function(a){if(a&&"anonymous"!==a)for(var b=d.length;b--;)d[b]._name===a&&d.splice(b,1)};return c});p("widgets/filepicker",
["base","uploader","lib/filepicker","widgets/widget"],function(g,l,k){var c=g.$;c.extend(l.options,{pick:null,accept:null});return l.register({name:"picker",init:function(b){this.pickers=[];return b.pick&&this.addBtn(b.pick)},refresh:function(){c.each(this.pickers,function(){this.refresh()})},addBtn:function(b){var a=this,f=a.options,e=f.accept,d=[];if(b)return c.isPlainObject(b)||(b={id:b}),c(b.id).each(function(){var h=g.Deferred();var n=c.extend({},b,{accept:c.isPlainObject(e)?[e]:e,swf:f.swf,
runtimeOrder:f.runtimeOrder,id:this});n=new k(n);n.once("ready",h.resolve);n.on("select",function(d){a.owner.request("add-file",[d])});n.init();a.pickers.push(n);d.push(h.promise())}),g.when.apply(g,d)},disable:function(){c.each(this.pickers,function(){this.disable()})},enable:function(){c.each(this.pickers,function(){this.enable()})},destroy:function(){c.each(this.pickers,function(){this.destroy()});this.pickers=null}})});p("lib/image",["base","runtime/client","lib/blob"],function(g,l,k){function c(a){this.options=
b.extend({},c.options,a);l.call(this,"Image");this.on("load",function(){this._info=this.exec("info");this._meta=this.exec("meta")})}var b=g.$;c.options={quality:90,crop:!1,preserveHeaders:!1,allowMagnify:!1};g.inherits(l,{constructor:c,info:function(a){return a?(this._info=a,this):this._info},meta:function(a){return a?(this._meta=a,this):this._meta},loadFromBlob:function(a){var b=this,e=a.getRuid();this.connectRuntime(e,function(){b.exec("init",b.options);b.exec("loadFromBlob",a)})},resize:function(){var a=
g.slice(arguments);return this.exec.apply(this,["resize"].concat(a))},crop:function(){var a=g.slice(arguments);return this.exec.apply(this,["crop"].concat(a))},getAsDataUrl:function(a){return this.exec("getAsDataUrl",a)},getAsBlob:function(a){a=this.exec("getAsBlob",a);return new k(this.getRuid(),a)}});return c});p("widgets/image",["base","uploader","lib/image","widgets/widget"],function(g,l,k){var c=g.$;var b=function(a){var b=0,e=[],d=function(){for(var d;e.length&&b<a;)d=e.shift(),b+=d[0],d[1]()};
return function(a,f,c){e.push([f,c]);a.once("destroy",function(){b-=f;setTimeout(d,1)});setTimeout(d,1)}}(5242880);c.extend(l.options,{thumb:{width:110,height:110,quality:70,allowMagnify:!0,crop:!0,preserveHeaders:!1,type:"image/jpeg"},compress:{width:1600,height:1600,quality:90,allowMagnify:!1,crop:!1,preserveHeaders:!0}});return l.register({name:"image",makeThumb:function(a,f,e,d){a=this.request("get-file",a);if(a.type.match(/^image/)){var h=c.extend({},this.options.thumb);c.isPlainObject(e)&&(h=
c.extend(h,e),e=null);e=e||h.width;d=d||h.height;var n=new k(h);n.once("load",function(){a._info=a._info||n.info();a._meta=a._meta||n.meta();1>=e&&0<e&&(e*=a._info.width);1>=d&&0<d&&(d*=a._info.height);n.resize(e,d)});n.once("complete",function(){f(!1,n.getAsDataUrl(h.type));n.destroy()});n.once("error",function(a){f(a||!0);n.destroy()});b(n,a.source.size,function(){a._info&&n.info(a._info);a._meta&&n.meta(a._meta);n.loadFromBlob(a.source)})}else f(!0)},beforeSendFile:function(a){var b=this.options.compress||
this.options.resize,e=b&&b.compressSize||0,d=b&&b.noCompressIfLarger||!1;a=this.request("get-file",a);if(b&&~"image/jpeg,image/jpg".indexOf(a.type)&&!(a.size<e)&&!a._compressed){b=c.extend({},b);var h=g.Deferred();var n=new k(b);h.always(function(){n.destroy();n=null});n.once("error",h.reject);n.once("load",function(){var d=b.width,h=b.height;a._info=a._info||n.info();a._meta=a._meta||n.meta();1>=d&&0<d&&(d*=a._info.width);1>=h&&0<h&&(h*=a._info.height);n.resize(d,h)});n.once("complete",function(){try{var e=
n.getAsBlob(b.type);var f=a.size;if(!d||e.size<f)a.source=e,a.size=e.size,a.trigger("resize",e.size,f);a._compressed=!0;h.resolve()}catch(m){h.resolve()}});a._info&&n.info(a._info);a._meta&&n.meta(a._meta);n.loadFromBlob(a.source);return h.promise()}}})});p("file",["base","mediator"],function(g,l){function k(f){this.name=f.name||"Untitled";this.size=f.size||0;this.type=f.type||"application/octet-stream";this.lastModifiedDate=f.lastModifiedDate||1*new Date;this.id="WU_FILE_"+c++;this.ext=b.exec(this.name)?
RegExp.$1:"";this.statusText="";a[this.id]=k.Status.INITED;this.source=f;this.loaded=0;this.on("error",function(a){this.setStatus(k.Status.ERROR,a)})}var c=0,b=/\.([^.]+)$/,a={};g.$.extend(k.prototype,{setStatus:function(b,e){var d=a[this.id];"undefined"!==typeof e&&(this.statusText=e);b!==d&&(a[this.id]=b,this.trigger("statuschange",b,d))},getStatus:function(){return a[this.id]},getSource:function(){return this.source},destroy:function(){this.off();delete a[this.id]}});l.installTo(k.prototype);k.Status=
{INITED:"inited",QUEUED:"queued",PROGRESS:"progress",ERROR:"error",COMPLETE:"complete",CANCELLED:"cancelled",INTERRUPT:"interrupt",INVALID:"invalid"};return k});p("queue",["base","mediator","file"],function(g,l,k){function c(){this.stats={numOfQueue:0,numOfSuccess:0,numOfCancel:0,numOfProgress:0,numOfUploadFailed:0,numOfInvalid:0,numofDeleted:0,numofInterrupt:0};this._queue=[];this._map={}}var b=g.$,a=k.Status;b.extend(c.prototype,{append:function(a){this._queue.push(a);this._fileAdded(a);return this},
prepend:function(a){this._queue.unshift(a);this._fileAdded(a);return this},getFile:function(a){return"string"!==typeof a?a:this._map[a]},fetch:function(b){var e=this._queue.length,d;b=b||a.QUEUED;for(d=0;d<e;d++){var h=this._queue[d];if(b===h.getStatus())return h}return null},sort:function(a){"function"===typeof a&&this._queue.sort(a)},getFiles:function(){for(var a=[].slice.call(arguments,0),e=[],d=0,h=this._queue.length,c;d<h;d++)c=this._queue[d],a.length&&!~b.inArray(c.getStatus(),a)||e.push(c);
return e},removeFile:function(a){this._map[a.id]&&(delete this._map[a.id],a.destroy(),this.stats.numofDeleted++)},_fileAdded:function(a){var b=this;this._map[a.id]||(this._map[a.id]=a,a.on("statuschange",function(a,h){b._onFileStatusChange(a,h)}))},_onFileStatusChange:function(b,e){var d=this.stats;switch(e){case a.PROGRESS:d.numOfProgress--;break;case a.QUEUED:d.numOfQueue--;break;case a.ERROR:d.numOfUploadFailed--;break;case a.INVALID:d.numOfInvalid--;break;case a.INTERRUPT:d.numofInterrupt--}switch(b){case a.QUEUED:d.numOfQueue++;
break;case a.PROGRESS:d.numOfProgress++;break;case a.ERROR:d.numOfUploadFailed++;break;case a.COMPLETE:d.numOfSuccess++;break;case a.CANCELLED:d.numOfCancel++;break;case a.INVALID:d.numOfInvalid++;break;case a.INTERRUPT:d.numofInterrupt++}}});l.installTo(c.prototype);return c});p("widgets/queue","base uploader queue file lib/file runtime/client widgets/widget".split(" "),function(g,l,k,c,b,a){var f=g.$,e=/\.\w+$/,d=c.Status;return l.register({name:"queue",init:function(d){var b=this,h,e,c,u;f.isPlainObject(d.accept)&&
(d.accept=[d.accept]);if(d.accept){var q=[];var w=0;for(h=d.accept.length;w<h;w++)(e=d.accept[w].extensions)&&q.push(e);q.length&&(c="\\."+q.join(",").replace(/,/g,"$|\\.").replace(/\*/g,".*")+"$");b.accept=new RegExp(c,"i")}b.queue=new k;b.stats=b.queue.stats;if("html5"===this.request("predict-runtime-type")){var y=g.Deferred();this.placeholder=u=new a("Placeholder");u.connectRuntime({runtimeOrder:"html5"},function(){b._ruid=u.getRuid();y.resolve()});return y.promise()}},_wrapFile:function(a){if(!(a instanceof
c)){if(!(a instanceof b)){if(!this._ruid)throw Error("Can't add external files.");a=new b(this._ruid,a)}a=new c(a)}return a},acceptFile:function(a){return!(!a||!a.size||this.accept&&e.exec(a.name)&&!this.accept.test(a.name))},_addFile:function(a){a=this._wrapFile(a);if(this.owner.trigger("beforeFileQueued",a)){if(this.acceptFile(a))return this.queue.append(a),this.owner.trigger("fileQueued",a),a;this.owner.trigger("error","Q_TYPE_DENIED",a)}},getFile:function(a){return this.queue.getFile(a)},addFile:function(a){var d=
this;a.length||(a=[a]);a=f.map(a,function(a){return d._addFile(a)});d.owner.trigger("filesQueued",a);d.options.auto&&setTimeout(function(){d.request("start-upload")},20)},getStats:function(){return this.stats},removeFile:function(a,d){a=a.id?a:this.queue.getFile(a);this.request("cancel-file",a);d&&this.queue.removeFile(a)},getFiles:function(){return this.queue.getFiles.apply(this.queue,arguments)},fetchFile:function(){return this.queue.fetch.apply(this.queue,arguments)},retry:function(a,b){var e;
if(a)a=a.id?a:this.queue.getFile(a),a.setStatus(d.QUEUED),b||this.request("start-upload");else{b=this.queue.getFiles(d.ERROR);var c=0;for(e=b.length;c<e;c++)a=b[c],a.setStatus(d.QUEUED);this.request("start-upload")}},sortFiles:function(){return this.queue.sort.apply(this.queue,arguments)},reset:function(){this.owner.trigger("reset");this.queue=new k;this.stats=this.queue.stats},destroy:function(){this.reset();this.placeholder&&this.placeholder.destroy()}})});p("widgets/runtime",["uploader","runtime/runtime",
"widgets/widget"],function(g,l){g.support=function(){return l.hasRuntime.apply(l,arguments)};return g.register({name:"runtime",init:function(){if(!this.predictRuntimeType())throw Error("Runtime Error");},predictRuntimeType:function(){var k=this.options.runtimeOrder||l.orders,c=this.type,b;if(!c){k=k.split(/\s*,\s*/g);var a=0;for(b=k.length;a<b;a++)if(l.hasRuntime(k[a])){this.type=c=k[a];break}}return c}})});p("lib/transport",["base","runtime/client","mediator"],function(g,l,k){function c(a){var f=
this;a=f.options=b.extend(!0,{},c.options,a||{});l.call(this,"Transport");this._blob=null;this._formData=a.formData||{};this._headers=a.headers||{};this.on("progress",this._timeout);this.on("load error",function(){f.trigger("progress",1);clearTimeout(f._timer)})}var b=g.$;c.options={server:"",method:"POST",withCredentials:!1,fileVal:"file",timeout:12E4,formData:{},headers:{},sendAsBinary:!1};b.extend(c.prototype,{appendBlob:function(a,b,e){var d=this,c=d.options;d.getRuid()&&d.disconnectRuntime();
d.connectRuntime(b.ruid,function(){d.exec("init")});d._blob=b;c.fileVal=a||c.fileVal;c.filename=e||c.filename},append:function(a,c){"object"===typeof a?b.extend(this._formData,a):this._formData[a]=c},setRequestHeader:function(a,c){"object"===typeof a?b.extend(this._headers,a):this._headers[a]=c},send:function(a){this.exec("send",a);this._timeout()},abort:function(){clearTimeout(this._timer);return this.exec("abort")},destroy:function(){this.trigger("destroy");this.off();this.exec("destroy");this.disconnectRuntime()},
getResponse:function(){return this.exec("getResponse")},getResponseAsJson:function(){return this.exec("getResponseAsJson")},getStatus:function(){return this.exec("getStatus")},_timeout:function(){var a=this,b=a.options.timeout;b&&(clearTimeout(a._timer),a._timer=setTimeout(function(){a.abort();a.trigger("error","timeout")},b))}});k.installTo(c.prototype);return c});p("widgets/upload",["base","uploader","file","lib/transport","widgets/widget"],function(g,l,k,c){function b(a,b){var d=[],e=a.source.size,
c=b?Math.ceil(e/b):1,h=0,f=0,q;for(q={file:a,has:function(){return!!d.length},shift:function(){return d.shift()},unshift:function(a){d.unshift(a)}};f<c;){var w=Math.min(b,e-h);d.push({file:a,start:h,end:b?h+w:e,total:e,chunks:c,chunk:f++,cuted:q});h+=w}a.blocks=d.concat();a.remaning=d.length;return q}var a=g.$,f=g.isPromise,e=k.Status;a.extend(l.options,{prepareNextFile:!1,chunked:!1,chunkSize:5242880,chunkRetry:2,threads:3,formData:{}});l.register({name:"upload",init:function(){var d=this.owner,
b=this;this.progress=this.runing=!1;d.on("startUpload",function(){b.progress=!0}).on("uploadFinished",function(){b.progress=!1});this.pool=[];this.stack=[];this.pending=[];this.remaning=0;this.__tick=g.bindFn(this._tick,this);d.on("uploadComplete",function(d){d.blocks&&a.each(d.blocks,function(a,d){d.transport&&(d.transport.abort(),d.transport.destroy());delete d.transport});delete d.blocks;delete d.remaning})},reset:function(){this.request("stop-upload",!0);this.runing=!1;this.pool=[];this.stack=
[];this.pending=[];this.remaning=0;this._trigged=!1;this._promise=null},startUpload:function(d){var b=this;a.each(b.request("get-files",e.INVALID),function(){b.request("remove-file",this)});if(d){d=d.id?d:b.request("get-file",d);if(d.getStatus()===e.INTERRUPT)a.each(b.pool,function(a,b){b.file===d&&b.transport&&b.transport.send()});else if(d.getStatus()===e.PROGRESS)return;d.setStatus(e.QUEUED)}else a.each(b.request("get-files",[e.INITED]),function(){this.setStatus(e.QUEUED)});if(!b.runing){b.runing=
!0;var c=[];for(a.each(b.pool,function(a,d){a=d.file;a.getStatus()===e.INTERRUPT&&(c.push(a),b._trigged=!1,d.transport&&d.transport.send())});d=c.shift();)d.setStatus(e.PROGRESS);d||a.each(b.request("get-files",e.INTERRUPT),function(){this.setStatus(e.PROGRESS)});b._trigged=!1;g.nextTick(b.__tick);b.owner.trigger("startUpload")}},stopUpload:function(d,b){var c=this;!0===d&&(b=d,d=null);if(!1!==c.runing){if(d){d=d.id?d:c.request("get-file",d);if(d.getStatus()!==e.PROGRESS&&d.getStatus()!==e.QUEUED)return;
d.setStatus(e.INTERRUPT);a.each(c.pool,function(a,b){b.file===d&&(b.transport&&b.transport.abort(),c._putback(b),c._popBlock(b))});return g.nextTick(c.__tick)}c.runing=!1;this._promise&&this._promise.file&&this._promise.file.setStatus(e.INTERRUPT);b&&a.each(c.pool,function(a,b){b.transport&&b.transport.abort();b.file.setStatus(e.INTERRUPT)});c.owner.trigger("stopUpload")}},cancelFile:function(b){b=b.id?b:this.request("get-file",b);b.blocks&&a.each(b.blocks,function(a,b){if(a=b.transport)a.abort(),
a.destroy(),delete b.transport});b.setStatus(e.CANCELLED);this.owner.trigger("fileDequeued",b)},isInProgress:function(){return!!this.progress},_getStats:function(){return this.request("get-stats")},skipFile:function(b,c){b=b.id?b:this.request("get-file",b);b.setStatus(c||e.COMPLETE);b.skipped=!0;b.blocks&&a.each(b.blocks,function(a,b){if(a=b.transport)a.abort(),a.destroy(),delete b.transport});this.owner.trigger("uploadSkip",b)},_tick:function(){var a=this,b=a.options,c;if(a._promise)return a._promise.always(a.__tick);
a.pool.length<b.threads&&(c=a._nextBlock())?(a._trigged=!1,b=function(b){a._promise=null;b&&b.file&&a._startSend(b);g.nextTick(a.__tick)},a._promise=f(c)?c.always(b):b(c)):a.remaning||a._getStats().numOfQueue||a._getStats().numofInterrupt||(a.runing=!1,a._trigged||g.nextTick(function(){a.owner.trigger("uploadFinished")}),a._trigged=!0)},_putback:function(a){a.cuted.unshift(a);~this.stack.indexOf(a.cuted)||this.stack.unshift(a.cuted)},_getStack:function(){for(var a=0,b;b=this.stack[a++];){if(b.has()&&
b.file.getStatus()===e.PROGRESS)return b;(!b.has()||b.file.getStatus()!==e.PROGRESS&&b.file.getStatus()!==e.INTERRUPT)&&this.stack.splice(--a,1)}return null},_nextBlock:function(){var a=this,c=a.options,e;if(e=this._getStack())return c.prepareNextFile&&!a.pending.length&&a._prepareNextFile(),e.shift();if(a.runing){!a.pending.length&&a._getStats().numOfQueue&&a._prepareNextFile();var k=a.pending.shift();var g=function(d){if(!d)return null;e=b(d,c.chunked?c.chunkSize:0);a.stack.push(e);return e.shift()};
if(f(k)){var m=k.file;k=k[k.pipe?"pipe":"then"](g);k.file=m;return k}return g(k)}},_prepareNextFile:function(){var b=this,c=b.request("fetch-file"),f=b.pending;if(c){var k=b.request("before-send-file",c,function(){return c.getStatus()===e.PROGRESS||c.getStatus()===e.INTERRUPT?c:b._finishFile(c)});b.owner.trigger("uploadStart",c);c.setStatus(e.PROGRESS);k.file=c;k.done(function(){var b=a.inArray(k,f);~b&&f.splice(b,1,c)});k.fail(function(a){c.setStatus(e.ERROR,a);b.owner.trigger("uploadError",c,a);
b.owner.trigger("uploadComplete",c)});f.push(k)}},_popBlock:function(b){var d=a.inArray(b,this.pool);this.pool.splice(d,1);b.file.remaning--;this.remaning--},_startSend:function(a){var b=this,d=a.file;d.getStatus()!==e.PROGRESS?d.getStatus()===e.INTERRUPT&&b._putback(a):(b.pool.push(a),b.remaning++,a.blob=1===a.chunks?d.source:d.source.slice(a.start,a.end),b.request("before-send",a,function(){d.getStatus()===e.PROGRESS?b._doSend(a):(b._popBlock(a),g.nextTick(b.__tick))}).fail(function(){1===d.remaning?
b._finishFile(d).always(function(){a.percentage=1;b._popBlock(a);b.owner.trigger("uploadComplete",d);g.nextTick(b.__tick)}):(a.percentage=1,b.updateFileProgress(d),b._popBlock(a),g.nextTick(b.__tick))}))},_doSend:function(b){var d=this,f=d.owner,k=d.options,l=b.file,m=new c(k),u=a.extend({},k.formData),q=a.extend({},k.headers),w;b.transport=m;m.on("destroy",function(){delete b.transport;d._popBlock(b);g.nextTick(d.__tick)});m.on("progress",function(a){b.percentage=a;d.updateFileProgress(l)});var y=
function(a){w=m.getResponseAsJson()||{};w._raw=m.getResponse();f.trigger("uploadAccept",b,w,function(b){a=b})||(a=a||"server");return a};m.on("error",function(a,d){b.retried=b.retried||0;1<b.chunks&&~"http,abort".indexOf(a)&&b.retried<k.chunkRetry?(b.retried++,m.send()):(d||"server"!==a||(a=y(a)),l.setStatus(e.ERROR,a),f.trigger("uploadError",l,a),f.trigger("uploadComplete",l))});m.on("load",function(){var a;(a=y())?m.trigger("error",a,!0):1===l.remaning?d._finishFile(l,w):m.destroy()});u=a.extend(u,
{id:l.id,name:l.name,type:l.type,lastModifiedDate:l.lastModifiedDate,size:l.size});1<b.chunks&&a.extend(u,{chunks:b.chunks,chunk:b.chunk});f.trigger("uploadBeforeSend",b,u,q);m.appendBlob(k.fileVal,b.blob,l.name);m.append(u);m.setRequestHeader(q);m.send()},_finishFile:function(a,b,c){var d=this.owner;return d.request("after-send-file",arguments,function(){a.setStatus(e.COMPLETE);d.trigger("uploadSuccess",a,b,c)}).fail(function(b){a.getStatus()===e.PROGRESS&&a.setStatus(e.ERROR,b);d.trigger("uploadError",
a,b)}).always(function(){d.trigger("uploadComplete",a)})},updateFileProgress:function(b){var d=0,c=0;b.blocks&&(a.each(b.blocks,function(a,b){c+=(b.percentage||0)*(b.end-b.start)}),d=c/b.size,this.owner.trigger("uploadProgress",b,d||0))}})});p("lib/md5",["runtime/client","mediator"],function(g,l){function k(){g.call(this,"Md5")}l.installTo(k.prototype);k.prototype.loadFromBlob=function(c){var b=this;b.getRuid()&&b.disconnectRuntime();b.connectRuntime(c.ruid,function(){b.exec("init");b.exec("loadFromBlob",
c)})};k.prototype.getResult=function(){return this.exec("getResult")};return k});p("widgets/md5",["base","uploader","lib/md5","lib/blob","widgets/widget"],function(g,l,k,c){return l.register({name:"md5",md5File:function(b,a,f){var e=new k,d=g.Deferred(),h=b instanceof c?b:this.request("get-file",b).source;e.on("progress load",function(a){a=a||{};d.notify(a.total?a.loaded/a.total:1)});e.on("complete",function(){d.resolve(e.getResult())});e.on("error",function(a){d.reject(a)});1<arguments.length&&(a=
a||0,f=f||0,0>a&&(a=h.size+a),0>f&&(f=h.size+f),f=Math.min(f,h.size),h=h.slice(a,f));e.loadFromBlob(h);return d.promise()}})});p("widgets/log",["base","uploader","widgets/widget"],function(g,l){function k(a){a=c.extend({},b,a);a=" http://static.tieba.baidu.com/tb/pms/img/st.gif??".replace(/^(.*)\?/,"$1"+c.param(a));(new Image).src=a}var c=g.$;g=(location.hostname||location.host||"protected").toLowerCase();if(g&&/baidu/i.exec(g)){var b={dv:3,master:"webuploader",online:/test/.exec(g)?0:1,module:"",
product:g,type:0};return l.register({name:"log",init:function(){var a=0,b=0;this.owner.on("error",function(a){k({type:2,c_error_code:a})}).on("uploadError",function(a,b){k({type:2,c_error_code:"UPLOAD_ERROR",c_reason:""+b})}).on("uploadComplete",function(c){a++;b+=c.size}).on("uploadFinished",function(){k({c_count:a,c_size:b});a=b=0});k({c_usage:1})}})}});p("runtime/compbase",[],function(){return function(g,l){this.owner=g;this.options=g.options;this.getRuntime=function(){return l};this.getRuid=function(){return l.uid};
this.trigger=function(){return g.trigger.apply(g,arguments)}}});p("runtime/html5/runtime",["base","runtime/runtime","runtime/compbase"],function(g,l,k){function c(){var a={},c=this,e=this.destroy;l.apply(c,arguments);c.type="html5";c.exec=function(d,e){var f=this.uid,h=g.slice(arguments,2);if(b[d]&&(f=a[f]=a[f]||new b[d](this,c),f[e]))return f[e].apply(f,h)};c.destroy=function(){return e&&e.apply(this,arguments)}}var b={};g.inherits(l,{constructor:c,init:function(){var a=this;setTimeout(function(){a.trigger("ready")},
1)}});c.register=function(a,c){return b[a]=g.inherits(k,c)};t.Blob&&t.FileReader&&t.DataView&&l.addRuntime("html5",c);return c});p("runtime/html5/blob",["runtime/html5/runtime","lib/blob"],function(g,l){return g.register("Blob",{slice:function(k,c){var b=this.owner.source;b=(b.slice||b.webkitSlice||b.mozSlice).call(b,k,c);return new l(this.getRuid(),b)}})});p("runtime/html5/filepicker",["base","runtime/html5/runtime"],function(g,l){var k=g.$;return l.register("FilePicker",{init:function(){var c=this.getRuntime().getContainer(),
b=this,a=b.owner,f=b.options,e=this.label=k(document.createElement("label")),d=this.input=k(document.createElement("input")),h;d.attr("type","file");d.attr("name",f.name);d.addClass("webuploader-element-invisible");e.on("click",function(){d.trigger("click")});e.css({opacity:0,width:"100%",height:"100%",display:"block",cursor:"pointer",background:"#ffffff"});f.multiple&&d.attr("multiple","multiple");if(f.accept&&0<f.accept.length){var g=[];var l=0;for(h=f.accept.length;l<h;l++)g.push(f.accept[l].mimeTypes);
d.attr("accept",g.join(","))}c.append(d);c.append(e);var r=function(b){a.trigger(b.type)};d.on("change",function(c){var e=arguments.callee;b.files=c.target.files;var f=this.cloneNode(!0);f.value=null;this.parentNode.replaceChild(f,this);d.off();d=k(f).on("change",e).on("mouseenter mouseleave",r);a.trigger("change")});e.on("mouseenter mouseleave",r)},getFiles:function(){return this.files},destroy:function(){this.input.off();this.label.off()}})});p("runtime/html5/util",["base"],function(g){var l=t.createObjectURL&&
t||t.URL&&URL.revokeObjectURL&&URL||t.webkitURL,k=g=g.noop;l&&(g=function(){return l.createObjectURL.apply(l,arguments)},k=function(){return l.revokeObjectURL.apply(l,arguments)});return{createObjectURL:g,revokeObjectURL:k,dataURL2Blob:function(c){var b;var a=c.split(",");var f=~a[0].indexOf("base64")?atob(a[1]):decodeURIComponent(a[1]);c=new ArrayBuffer(f.length);var e=new Uint8Array(c);for(b=0;b<f.length;b++)e[b]=f.charCodeAt(b);f=a[0].split(":")[1].split(";")[0];return this.arrayBufferToBlob(c,
f)},dataURL2ArrayBuffer:function(c){var b;c=c.split(",");c=~c[0].indexOf("base64")?atob(c[1]):decodeURIComponent(c[1]);var a=new Uint8Array(c.length);for(b=0;b<c.length;b++)a[b]=c.charCodeAt(b);return a.buffer},arrayBufferToBlob:function(c,b){var a=t.BlobBuilder||t.WebKitBlobBuilder;return a?(a=new a,a.append(c),a.getBlob(b)):new Blob([c],b?{type:b}:{})},canvasToDataUrl:function(c,b,a){return c.toDataURL(b,a/100)},parseMeta:function(c,b){b(!1,{})},updateImageHead:function(c){return c}}});p("runtime/html5/imagemeta",
["runtime/html5/util"],function(g){var l={parsers:{65505:[]},maxMetaDataSize:262144,parse:function(k,c){var b=this,a=new FileReader;a.onload=function(){c(!1,b._parse(this.result));a=a.onload=a.onerror=null};a.onerror=function(b){c(b.message);a=a.onload=a.onerror=null};k=k.slice(0,b.maxMetaDataSize);a.readAsArrayBuffer(k.getSource())},_parse:function(k,c){if(!(6>k.byteLength)){var b=new DataView(k),a=2,f=b.byteLength-4,e=a,d={};if(65496===b.getUint16(0)){for(;a<f;){var h=b.getUint16(a);if(65504<=h&&
65519>=h||65534===h){var g=b.getUint16(a+2)+2;if(a+g>b.byteLength)break;e=l.parsers[h];if(!c&&e)for(h=0;h<e.length;h+=1)e[h].call(l,b,a,g,d);e=a+=g}else break}6<e&&(d.imageHead=k.slice?k.slice(2,e):(new Uint8Array(k)).subarray(2,e))}return d}},updateImageHead:function(k,c){var b=this._parse(k,!0);var a=2;b.imageHead&&(a=2+b.imageHead.byteLength);b=k.slice?k.slice(a):(new Uint8Array(k)).subarray(a);k=new Uint8Array(c.byteLength+2+b.byteLength);k[0]=255;k[1]=216;k.set(new Uint8Array(c),2);k.set(new Uint8Array(b),
c.byteLength+2);return k.buffer}};g.parseMeta=function(){return l.parse.apply(l,arguments)};g.updateImageHead=function(){return l.updateImageHead.apply(l,arguments)};return l});p("runtime/html5/imagemeta/exif",["base","runtime/html5/imagemeta"],function(g,l){var k={ExifMap:function(){return this}};k.ExifMap.prototype.map={Orientation:274};k.ExifMap.prototype.get=function(c){return this[c]||this[this.map[c]]};k.exifTagTypes={1:{getValue:function(c,b){return c.getUint8(b)},size:1},2:{getValue:function(c,
b){return String.fromCharCode(c.getUint8(b))},size:1,ascii:!0},3:{getValue:function(c,b,a){return c.getUint16(b,a)},size:2},4:{getValue:function(c,b,a){return c.getUint32(b,a)},size:4},5:{getValue:function(c,b,a){return c.getUint32(b,a)/c.getUint32(b+4,a)},size:8},9:{getValue:function(c,b,a){return c.getInt32(b,a)},size:4},10:{getValue:function(c,b,a){return c.getInt32(b,a)/c.getInt32(b+4,a)},size:8}};k.exifTagTypes[7]=k.exifTagTypes[1];k.getExifValue=function(c,b,a,f,e,d){f=k.exifTagTypes[f];if(f){var h=
f.size*e;var l=4<h?b+c.getUint32(a+8,d):a+8;if(l+h>c.byteLength)g.log("Invalid Exif data: Invalid data offset.");else{if(1===e)return f.getValue(c,l,d);b=[];for(a=0;a<e;a+=1)b[a]=f.getValue(c,l+a*f.size,d);if(f.ascii){c="";for(a=0;a<b.length;a+=1){e=b[a];if("\x00"===e)break;c+=e}return c}return b}}else g.log("Invalid Exif data: Invalid tag type.")};k.parseExifTag=function(c,b,a,f,e){var d=c.getUint16(a,f);e.exif[d]=k.getExifValue(c,b,a,c.getUint16(a+2,f),c.getUint32(a+4,f),f)};k.parseExifTags=function(c,
b,a,f,e){var d;if(a+6>c.byteLength)g.log("Invalid Exif data: Invalid directory offset.");else{var h=c.getUint16(a,f);var k=a+2+12*h;if(k+4>c.byteLength)g.log("Invalid Exif data: Invalid directory size.");else{for(d=0;d<h;d+=1)this.parseExifTag(c,b,a+2+12*d,f,e);return c.getUint32(k,f)}}};k.parseExifData=function(c,b,a,f){a=b+10;if(1165519206===c.getUint32(b+4))if(a+8>c.byteLength)g.log("Invalid Exif data: Invalid segment size.");else if(0!==c.getUint16(b+8))g.log("Invalid Exif data: Missing byte alignment offset.");
else{switch(c.getUint16(a)){case 18761:b=!0;break;case 19789:b=!1;break;default:g.log("Invalid Exif data: Invalid byte alignment marker.");return}if(42!==c.getUint16(a+2,b))g.log("Invalid Exif data: Missing TIFF marker.");else{var e=c.getUint32(a+4,b);f.exif=new k.ExifMap;k.parseExifTags(c,a,a+e,b,f)}}};l.parsers[65505].push(k.parseExifData);return k});p("runtime/html5/image",["base","runtime/html5/runtime","runtime/html5/util"],function(g,l,k){return l.register("Image",{modified:!1,init:function(){var c=
this,b=new Image;b.onload=function(){c._info={type:c.type,width:this.width,height:this.height};c._metas||"image/jpeg"!==c.type?c.owner.trigger("load"):k.parseMeta(c._blob,function(a,b){c._metas=b;c.owner.trigger("load")})};b.onerror=function(){c.owner.trigger("error")};c._img=b},loadFromBlob:function(c){var b=this._img;this._blob=c;this.type=c.type;b.src=k.createObjectURL(c.getSource());this.owner.once("load",function(){k.revokeObjectURL(b.src)})},resize:function(c,b){var a=this._canvas||(this._canvas=
document.createElement("canvas"));this._resize(this._img,a,c,b);this._blob=null;this.modified=!0;this.owner.trigger("complete","resize")},crop:function(c,b,a,f,e){var d=this._canvas||(this._canvas=document.createElement("canvas")),h=this.options,k=this._img,g=k.naturalWidth,l=k.naturalHeight,m=this.getOrientation();e=e||1;d.width=a;d.height=f;h.preserveHeaders||this._rotate2Orientaion(d,m);this._renderImageToCanvas(d,k,-c,-b,g*e,l*e);this._blob=null;this.modified=!0;this.owner.trigger("complete",
"crop")},getAsBlob:function(c){var b=this._blob,a=this.options;c=c||this.type;if(this.modified||this.type!==c){b=this._canvas;if("image/jpeg"===c){if(b=k.canvasToDataUrl(b,c,a.quality),a.preserveHeaders&&this._metas&&this._metas.imageHead)return b=k.dataURL2ArrayBuffer(b),b=k.updateImageHead(b,this._metas.imageHead),b=k.arrayBufferToBlob(b,c)}else b=k.canvasToDataUrl(b,c);b=k.dataURL2Blob(b)}return b},getAsDataUrl:function(c){var b=this.options;c=c||this.type;return"image/jpeg"===c?k.canvasToDataUrl(this._canvas,
c,b.quality):this._canvas.toDataURL(c)},getOrientation:function(){return this._metas&&this._metas.exif&&this._metas.exif.get("Orientation")||1},info:function(c){return c?(this._info=c,this):this._info},meta:function(c){return c?(this._meta=c,this):this._meta},destroy:function(){var c=this._canvas;this._img.onload=null;c&&(c.getContext("2d").clearRect(0,0,c.width,c.height),c.width=c.height=0,this._canvas=null);this._img.src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D";this._img=this._blob=
null},_resize:function(c,b,a,f){var e=this.options,d=c.width,h=c.height,k=this.getOrientation();~[5,6,7,8].indexOf(k)&&(a^=f,f^=a,a^=f);var g=Math[e.crop?"max":"min"](a/d,f/h);e.allowMagnify||(g=Math.min(1,g));d*=g;h*=g;e.crop?(b.width=a,b.height=f):(b.width=d,b.height=h);a=(b.width-d)/2;f=(b.height-h)/2;e.preserveHeaders||this._rotate2Orientaion(b,k);this._renderImageToCanvas(b,c,a,f,d,h)},_rotate2Orientaion:function(c,b){var a=c.width,f=c.height,e=c.getContext("2d");switch(b){case 5:case 6:case 7:case 8:c.width=
f,c.height=a}switch(b){case 2:e.translate(a,0);e.scale(-1,1);break;case 3:e.translate(a,f);e.rotate(Math.PI);break;case 4:e.translate(0,f);e.scale(1,-1);break;case 5:e.rotate(.5*Math.PI);e.scale(1,-1);break;case 6:e.rotate(.5*Math.PI);e.translate(0,-f);break;case 7:e.rotate(.5*Math.PI);e.translate(a,-f);e.scale(-1,1);break;case 8:e.rotate(-.5*Math.PI),e.translate(-a,0)}},_renderImageToCanvas:function(){function c(b,a,c){var e=document.createElement("canvas"),d=e.getContext("2d");a=0;var f=c,k=c;e.width=
1;e.height=c;d.drawImage(b,0,0);for(b=d.getImageData(0,0,1,c).data;k>a;)e=b[4*(k-1)+3],0===e?f=k:a=k,k=f+a>>1;c=k/c;return 0===c?1:c}return g.os.ios?7<=g.os.ios?function(b,a,f,e,d,k){var h=a.naturalWidth,g=a.naturalHeight,l=c(a,h,g);return b.getContext("2d").drawImage(a,0,0,h*l,g*l,f,e,d,k)}:function(b,a,f,e,d,k){var h=a.naturalWidth,g=a.naturalHeight;b=b.getContext("2d");var l=a.naturalWidth;if(1048576<l*a.naturalHeight){var m=document.createElement("canvas");m.width=m.height=1;m=m.getContext("2d");
m.drawImage(a,-l+1,0);var u=0===m.getImageData(0,0,1,1).data[3]}else u=!1;var q="image/jpeg"===this.type;m=l=0;var w;u&&(h/=2,g/=2);b.save();u=document.createElement("canvas");u.width=u.height=1024;var y=u.getContext("2d");q=q?c(a,h,g):1;d=Math.ceil(1024*d/h);for(k=Math.ceil(1024*k/g/q);l<g;){for(w=q=0;q<h;)y.clearRect(0,0,1024,1024),y.drawImage(a,-q,-l),b.drawImage(u,0,0,1024,1024,f+w,e+m,d,k),q+=1024,w+=d;l+=1024;m+=k}b.restore()}:function(b){var a=g.slice(arguments,1),c=b.getContext("2d");c.drawImage.apply(c,
a)}}()})});p("runtime/html5/jpegencoder",[],function(g,l,k){function c(b){function a(a,b){for(var d=0,c=0,e=[],f=1;16>=f;f++){for(var k=1;k<=a[f];k++)e[b[c]]=[],e[b[c]][0]=d,e[b[c]][1]=f,c++,d++;d*=2}return e}function c(a){var b=a[0];for(a=a[1]-1;0<=a;)b&1<<a&&(F|=1<<D),a--,D--,0>D&&(255==F?(e(255),e(0)):e(F),D=7,F=0)}function e(a){t.push(H[a])}function d(a){e(a>>8&255);e(a&255)}function k(a,b,d,e,f){var k=f[0],h=f[240],g,q=0;for(g=0;8>g;++g){var u=a[q];var m=a[q+1];var l=a[q+2];var n=a[q+3];var x=
a[q+4];var v=a[q+5];var r=a[q+6];var A=a[q+7];var t=u+A;u-=A;A=m+r;m-=r;r=l+v;l-=v;v=n+x;n-=x;x=t+v;t-=v;v=A+r;A-=r;a[q]=x+v;a[q+4]=x-v;x=.707106781*(A+t);a[q+2]=t+x;a[q+6]=t-x;x=n+l;v=l+m;A=m+u;l=.382683433*(x-A);n=.5411961*x+l;x=1.306562965*A+l;v*=.707106781;l=u+v;u-=v;a[q+5]=u+n;a[q+3]=u-n;a[q+1]=l+x;a[q+7]=l-x;q+=8}for(g=q=0;8>g;++g)u=a[q],m=a[q+8],l=a[q+16],n=a[q+24],x=a[q+32],v=a[q+40],r=a[q+48],A=a[q+56],t=u+A,u-=A,A=m+r,m-=r,r=l+v,l-=v,v=n+x,n-=x,x=t+v,t-=v,v=A+r,A-=r,a[q]=x+v,a[q+32]=x-v,
x=.707106781*(A+t),a[q+16]=t+x,a[q+48]=t-x,x=n+l,v=l+m,A=m+u,l=.382683433*(x-A),n=.5411961*x+l,x=1.306562965*A+l,v*=.707106781,l=u+v,u-=v,a[q+40]=u+n,a[q+24]=u-n,a[q+8]=l+x,a[q+56]=l-x,q++;for(g=0;64>g;++g)q=a[g]*b[g],E[g]=0<q?q+.5|0:q-.5|0;a=E;for(b=0;64>b;++b)p[G[b]]=a[b];a=p[0]-d;d=p[0];0==a?c(e[0]):(g=32767+a,c(e[y[g]]),c(w[g]));for(e=63;0<e&&0==p[e];e--);if(0==e)return c(k),d;for(a=1;a<=e;){for(b=a;0==p[a]&&a<=e;++a);b=a-b;if(16<=b){g=b>>4;for(q=1;q<=g;++q)c(h);b&=15}g=32767+p[a];c(f[(b<<4)+
y[g]]);c(w[g]);a++}63!=e&&c(k);return d}function g(a){0>=a&&(a=1);100<a&&(a=100);if(I!=a){for(var b=50>a?Math.floor(5E3/a):Math.floor(200-2*a),d=[16,11,10,16,24,40,51,61,12,12,14,19,26,58,60,55,14,13,16,24,40,57,69,56,14,17,22,29,51,87,80,62,18,22,37,56,68,109,103,77,24,35,55,64,81,104,113,92,49,64,78,87,103,121,120,101,72,92,95,98,112,100,103,99],c=0;64>c;c++){var e=l((d[c]*b+50)/100);1>e?e=1:255<e&&(e=255);r[G[c]]=e}d=[17,18,24,47,99,99,99,99,18,21,26,66,99,99,99,99,24,26,56,99,99,99,99,99,47,66,
99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99];for(c=0;64>c;c++)e=l((d[c]*b+50)/100),1>e?e=1:255<e&&(e=255),m[G[c]]=e;b=[1,1.387039845,1.306562965,1.175875602,1,.785694958,.5411961,.275899379];for(c=d=0;8>c;c++)for(e=0;8>e;e++)u[d]=1/(r[G[d]]*b[c]*b[e]*8),q[d]=1/(m[G[d]]*b[c]*b[e]*8),d++;I=a}}var l=Math.floor,r=Array(64),m=Array(64),u=Array(64),q=Array(64),w=Array(65535),y=Array(65535),E=Array(64),p=Array(64),t=[],F=0,D=7,C=Array(64),
J=Array(64),K=Array(64),H=Array(256),B=Array(2048),I,G=[0,1,5,6,14,15,27,28,2,4,7,13,16,26,29,42,3,8,12,17,25,30,41,43,9,11,18,24,31,40,44,53,10,19,23,32,39,45,52,54,20,22,33,38,46,51,55,60,21,34,37,47,50,56,59,61,35,36,48,49,57,58,62,63],L=[0,0,1,5,1,1,1,1,1,1,0,0,0,0,0,0,0],M=[0,1,2,3,4,5,6,7,8,9,10,11],N=[0,0,2,1,3,3,2,4,3,5,5,4,4,0,0,1,125],O=[1,2,3,0,4,17,5,18,33,49,65,6,19,81,97,7,34,113,20,50,129,145,161,8,35,66,177,193,21,82,209,240,36,51,98,114,130,9,10,22,23,24,25,26,37,38,39,40,41,42,52,
53,54,55,56,57,58,67,68,69,70,71,72,73,74,83,84,85,86,87,88,89,90,99,100,101,102,103,104,105,106,115,116,117,118,119,120,121,122,131,132,133,134,135,136,137,138,146,147,148,149,150,151,152,153,154,162,163,164,165,166,167,168,169,170,178,179,180,181,182,183,184,185,186,194,195,196,197,198,199,200,201,202,210,211,212,213,214,215,216,217,218,225,226,227,228,229,230,231,232,233,234,241,242,243,244,245,246,247,248,249,250],P=[0,0,3,1,1,1,1,1,1,1,1,1,0,0,0,0,0],Q=[0,1,2,3,4,5,6,7,8,9,10,11],R=[0,0,2,1,
2,4,4,3,4,7,5,4,4,0,1,2,119],S=[0,1,2,3,17,4,5,33,49,6,18,65,81,7,97,113,19,34,50,129,8,20,66,145,161,177,193,9,35,51,82,240,21,98,114,209,10,22,36,52,225,37,241,23,24,25,26,38,39,40,41,42,53,54,55,56,57,58,67,68,69,70,71,72,73,74,83,84,85,86,87,88,89,90,99,100,101,102,103,104,105,106,115,116,117,118,119,120,121,122,130,131,132,133,134,135,136,137,138,146,147,148,149,150,151,152,153,154,162,163,164,165,166,167,168,169,170,178,179,180,181,182,183,184,185,186,194,195,196,197,198,199,200,201,202,210,
211,212,213,214,215,216,217,218,226,227,228,229,230,231,232,233,234,242,243,244,245,246,247,248,249,250];this.encode=function(a,b){b&&g(b);t=[];F=0;D=7;d(65496);d(65504);d(16);e(74);e(70);e(73);e(70);e(0);e(1);e(1);e(0);d(1);d(1);e(0);e(0);d(65499);d(132);e(0);for(b=0;64>b;b++)e(r[b]);e(1);for(b=0;64>b;b++)e(m[b]);b=a.width;var f=a.height;d(65472);d(17);e(8);d(f);d(b);e(3);e(1);e(17);e(0);e(2);e(17);e(1);e(3);e(17);e(1);d(65476);d(418);e(0);for(b=0;16>b;b++)e(L[b+1]);for(b=0;11>=b;b++)e(M[b]);e(16);
for(b=0;16>b;b++)e(N[b+1]);for(b=0;161>=b;b++)e(O[b]);e(1);for(b=0;16>b;b++)e(P[b+1]);for(b=0;11>=b;b++)e(Q[b]);e(17);for(b=0;16>b;b++)e(R[b+1]);for(b=0;161>=b;b++)e(S[b]);d(65498);d(12);e(3);e(1);e(0);e(2);e(17);e(3);e(17);e(0);e(63);e(0);var h=f=b=0;F=0;D=7;this.encode.displayName="_encode_";var w=a.data,l=a.height;a=4*a.width;for(var y,E=0,n,v,p,x,z;E<l;){for(y=0;y<a;){x=a*E+y;for(z=0;64>z;z++)v=z>>3,n=4*(z&7),p=x+v*a+n,E+v>=l&&(p-=a*(E+1+v-l)),y+n>=a&&(p-=y+n-a+4),n=w[p++],v=w[p++],p=w[p++],C[z]=
(B[n]+B[v+256>>0]+B[p+512>>0]>>16)-128,J[z]=(B[n+768>>0]+B[v+1024>>0]+B[p+1280>>0]>>16)-128,K[z]=(B[n+1280>>0]+B[v+1536>>0]+B[p+1792>>0]>>16)-128;b=k(C,u,b,V,W);f=k(J,q,f,T,U);h=k(K,q,h,T,U);y+=32}E+=8}0<=D&&(a=[],a[1]=D+1,a[0]=(1<<D+1)-1,c(a));d(65497);a="data:image/jpeg;base64,"+btoa(t.join(""));t=[];return a};b||(b=50);(function(){for(var a=String.fromCharCode,b=0;256>b;b++)H[b]=a(b)})();var V=a(L,M);var T=a(P,Q);var W=a(N,O);var U=a(R,S);(function(){for(var a=1,b=2,d=1;15>=d;d++){for(var c=a;c<
b;c++)y[32767+c]=d,w[32767+c]=[],w[32767+c][1]=d,w[32767+c][0]=c;for(c=-(b-1);c<=-a;c++)y[32767+c]=d,w[32767+c]=[],w[32767+c][1]=d,w[32767+c][0]=b-1+c;a<<=1;b<<=1}})();(function(){for(var a=0;256>a;a++)B[a]=19595*a,B[a+256>>0]=38470*a,B[a+512>>0]=7471*a+32768,B[a+768>>0]=-11059*a,B[a+1024>>0]=-21709*a,B[a+1280>>0]=32768*a+8421375,B[a+1536>>0]=-27439*a,B[a+1792>>0]=-5329*a})();g(b)}c.encode=function(b,a){return(new c(a)).encode(b)};return c});p("runtime/html5/androidpatch",["runtime/html5/util","runtime/html5/jpegencoder",
"base"],function(g,l,k){var c=g.canvasToDataUrl,b;g.canvasToDataUrl=function(a,f,e){if(!k.os.android)return c.apply(null,arguments);if("image/jpeg"===f&&"undefined"===typeof b){var d=c.apply(null,arguments);d=d.split(",");d=~d[0].indexOf("base64")?atob(d[1]):decodeURIComponent(d[1]);d=d.substring(0,2);b=255===d.charCodeAt(0)&&216===d.charCodeAt(1)}if("image/jpeg"===f&&!b){var h=a.width;var g=a.height;d=a.getContext("2d");return l.encode(d.getImageData(0,0,h,g),e)}return c.apply(null,arguments)}});
p("runtime/html5/transport",["base","runtime/html5/runtime"],function(g,l){var k=g.noop,c=g.$;return l.register("Transport",{init:function(){this._status=0;this._response=null},send:function(){var b=this.owner,a=this.options,f=this._initAjax(),e=b._blob,d=a.server;if(a.sendAsBinary){d+=(/\?/.test(d)?"&":"?")+c.param(b._formData);var k=e.getSource()}else{var l=new FormData;c.each(b._formData,function(a,b){l.append(a,b)});l.append(a.fileVal,e.getSource(),a.filename||b._formData.name||"")}a.withCredentials&&
"withCredentials"in f?(f.open(a.method,d,!0),f.withCredentials=!0):f.open(a.method,d);this._setRequestHeader(f,a.headers);if(k)if(f.overrideMimeType&&f.overrideMimeType("application/octet-stream"),g.os.android){var p=new FileReader;p.onload=function(){f.send(this.result);p=p.onload=null};p.readAsArrayBuffer(k)}else f.send(k);else f.send(l)},getResponse:function(){return this._response},getResponseAsJson:function(){return this._parseJson(this._response)},getStatus:function(){return this._status},abort:function(){var b=
this._xhr;b&&(b.upload.onprogress=k,b.onreadystatechange=k,b.abort(),this._xhr=null)},destroy:function(){this.abort()},_initAjax:function(){var b=this,a=new XMLHttpRequest;!this.options.withCredentials||"withCredentials"in a||"undefined"===typeof XDomainRequest||(a=new XDomainRequest);a.upload.onprogress=function(a){var c=0;a.lengthComputable&&(c=a.loaded/a.total);return b.trigger("progress",c)};a.onreadystatechange=function(){if(4===a.readyState)return a.upload.onprogress=k,a.onreadystatechange=
k,b._xhr=null,b._status=a.status,200<=a.status&&300>a.status?(b._response=a.responseText,b.trigger("load")):500<=a.status&&600>a.status?(b._response=a.responseText,b.trigger("error","server")):b.trigger("error",b._status?"http":"abort")};return b._xhr=a},_setRequestHeader:function(b,a){c.each(a,function(a,c){b.setRequestHeader(a,c)})},_parseJson:function(b){try{var a=JSON.parse(b)}catch(f){a={}}return a}})});p("widgets/validator",["base","uploader","file","widgets/widget"],function(g,l,k){var c=g.$,
b={};var a={addValidator:function(a,c){b[a]=c},removeValidator:function(a){delete b[a]}};l.register({name:"validator",init:function(){var a=this;g.nextTick(function(){c.each(b,function(){this.call(a.owner)})})}});a.addValidator("fileNumLimit",function(){var a=0,b=parseInt(this.options.fileNumLimit,10),d=!0;b&&(this.on("beforeFileQueued",function(c){a>=b&&d&&(d=!1,this.trigger("error","Q_EXCEED_NUM_LIMIT",b,c),setTimeout(function(){d=!0},1));return a>=b?!1:!0}),this.on("fileQueued",function(){a++}),
this.on("fileDequeued",function(){a--}),this.on("reset",function(){a=0}))});a.addValidator("fileSizeLimit",function(){var a=0,b=parseInt(this.options.fileSizeLimit,10),d=!0;b&&(this.on("beforeFileQueued",function(c){var e=a+c.size>b;e&&d&&(d=!1,this.trigger("error","Q_EXCEED_SIZE_LIMIT",b,c),setTimeout(function(){d=!0},1));return e?!1:!0}),this.on("fileQueued",function(b){a+=b.size}),this.on("fileDequeued",function(b){a-=b.size}),this.on("reset",function(){a=0}))});a.addValidator("fileSingleSizeLimit",
function(){var a=this.options.fileSingleSizeLimit;if(a)this.on("beforeFileQueued",function(b){if(b.size>a)return b.setStatus(k.Status.INVALID,"exceed_size"),this.trigger("error","F_EXCEED_SIZE",a,b),!1})});a.addValidator("duplicate",function(){var a={};this.options.duplicate||(this.on("beforeFileQueued",function(b){var c;if(!(c=b.__hash)){c=b.name+b.size+b.lastModifiedDate;for(var e=0,f=0,k=c.length,g;f<k;f++)g=c.charCodeAt(f),e=g+(e<<6)+(e<<16)-e;c=b.__hash=e}if(a[c])return this.trigger("error",
"F_DUPLICATE",b),!1}),this.on("fileQueued",function(b){(b=b.__hash)&&(a[b]=!0)}),this.on("fileDequeued",function(b){(b=b.__hash)&&delete a[b]}),this.on("reset",function(){a={}}))});return a});p("runtime/html5/md5",["runtime/html5/runtime"],function(g){var l=function(a,b){return a+b&4294967295},k=function(a,b,c,d,e,f){b=l(l(b,a),l(d,f));return l(b<<e|b>>>32-e,c)},c=function(a,b,c,d,e,f,g){return k(b&c|~b&d,a,b,e,f,g)},b=function(a,b,c,d,e,f,g){return k(b&d|c&~d,a,b,e,f,g)},a=function(a,b,c,d,e,f,g){return k(c^
(b|~d),a,b,e,f,g)},f=function(d,e){var f=d[0],g=d[1],h=d[2],m=d[3];f=c(f,g,h,m,e[0],7,-680876936);m=c(m,f,g,h,e[1],12,-389564586);h=c(h,m,f,g,e[2],17,606105819);g=c(g,h,m,f,e[3],22,-1044525330);f=c(f,g,h,m,e[4],7,-176418897);m=c(m,f,g,h,e[5],12,1200080426);h=c(h,m,f,g,e[6],17,-1473231341);g=c(g,h,m,f,e[7],22,-45705983);f=c(f,g,h,m,e[8],7,1770035416);m=c(m,f,g,h,e[9],12,-1958414417);h=c(h,m,f,g,e[10],17,-42063);g=c(g,h,m,f,e[11],22,-1990404162);f=c(f,g,h,m,e[12],7,1804603682);m=c(m,f,g,h,e[13],12,
-40341101);h=c(h,m,f,g,e[14],17,-1502002290);g=c(g,h,m,f,e[15],22,1236535329);f=b(f,g,h,m,e[1],5,-165796510);m=b(m,f,g,h,e[6],9,-1069501632);h=b(h,m,f,g,e[11],14,643717713);g=b(g,h,m,f,e[0],20,-373897302);f=b(f,g,h,m,e[5],5,-701558691);m=b(m,f,g,h,e[10],9,38016083);h=b(h,m,f,g,e[15],14,-660478335);g=b(g,h,m,f,e[4],20,-405537848);f=b(f,g,h,m,e[9],5,568446438);m=b(m,f,g,h,e[14],9,-1019803690);h=b(h,m,f,g,e[3],14,-187363961);g=b(g,h,m,f,e[8],20,1163531501);f=b(f,g,h,m,e[13],5,-1444681467);m=b(m,f,g,
h,e[2],9,-51403784);h=b(h,m,f,g,e[7],14,1735328473);g=b(g,h,m,f,e[12],20,-1926607734);f=k(g^h^m,f,g,e[5],4,-378558);m=k(f^g^h,m,f,e[8],11,-2022574463);h=k(m^f^g,h,m,e[11],16,1839030562);g=k(h^m^f,g,h,e[14],23,-35309556);f=k(g^h^m,f,g,e[1],4,-1530992060);m=k(f^g^h,m,f,e[4],11,1272893353);h=k(m^f^g,h,m,e[7],16,-155497632);g=k(h^m^f,g,h,e[10],23,-1094730640);f=k(g^h^m,f,g,e[13],4,681279174);m=k(f^g^h,m,f,e[0],11,-358537222);h=k(m^f^g,h,m,e[3],16,-722521979);g=k(h^m^f,g,h,e[6],23,76029189);f=k(g^h^m,
f,g,e[9],4,-640364487);m=k(f^g^h,m,f,e[12],11,-421815835);h=k(m^f^g,h,m,e[15],16,530742520);g=k(h^m^f,g,h,e[2],23,-995338651);f=a(f,g,h,m,e[0],6,-198630844);m=a(m,f,g,h,e[7],10,1126891415);h=a(h,m,f,g,e[14],15,-1416354905);g=a(g,h,m,f,e[5],21,-57434055);f=a(f,g,h,m,e[12],6,1700485571);m=a(m,f,g,h,e[3],10,-1894986606);h=a(h,m,f,g,e[10],15,-1051523);g=a(g,h,m,f,e[1],21,-2054922799);f=a(f,g,h,m,e[8],6,1873313359);m=a(m,f,g,h,e[15],10,-30611744);h=a(h,m,f,g,e[6],15,-1560198380);g=a(g,h,m,f,e[13],21,1309151649);
f=a(f,g,h,m,e[4],6,-145523070);m=a(m,f,g,h,e[11],10,-1120210379);h=a(h,m,f,g,e[2],15,718787259);g=a(g,h,m,f,e[9],21,-343485551);d[0]=l(f,d[0]);d[1]=l(g,d[1]);d[2]=l(h,d[2]);d[3]=l(m,d[3])},e=function(a){var b=[],d;for(d=0;64>d;d+=4)b[d>>2]=a.charCodeAt(d)+(a.charCodeAt(d+1)<<8)+(a.charCodeAt(d+2)<<16)+(a.charCodeAt(d+3)<<24);return b},d=function(a){var b=[],d;for(d=0;64>d;d+=4)b[d>>2]=a[d]+(a[d+1]<<8)+(a[d+2]<<16)+(a[d+3]<<24);return b},h=function(a){var b=a.length,d=[1732584193,-271733879,-1732584194,
271733878],c;for(c=64;c<=b;c+=64)f(d,e(a.substring(c-64,c)));a=a.substring(c-64);var g=a.length;var h=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(c=0;c<g;c+=1)h[c>>2]|=a.charCodeAt(c)<<(c%4<<3);h[c>>2]|=128<<(c%4<<3);if(55<c)for(f(d,h),c=0;16>c;c+=1)h[c]=0;b=(8*b).toString(16).match(/(.*?)(.{0,8})$/);a=parseInt(b[2],16);b=parseInt(b[1],16)||0;h[14]=a;h[15]=b;f(d,h);return d},n="0123456789abcdef".split(""),p=function(a){var b;for(b=0;b<a.length;b+=1){var d=b,c,e=a[b],f="";for(c=0;4>c;c+=1)f+=n[e>>8*c+4&
15]+n[e>>8*c&15];a[d]=f}return a.join("")},r=function(){this.reset()};"5d41402abc4b2a76b9719d911017c592"!==p(h("hello"))&&(l=function(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535});r.prototype.append=function(a){/[\u0080-\uFFFF]/.test(a)&&(a=unescape(encodeURIComponent(a)));this.appendBinary(a);return this};r.prototype.appendBinary=function(a){this._buff+=a;this._length+=a.length;a=this._buff.length;var b;for(b=64;b<=a;b+=64)f(this._state,e(this._buff.substring(b-64,b)));
this._buff=this._buff.substr(b-64);return this};r.prototype.end=function(a){var b=this._buff,c=b.length,d,e=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(d=0;d<c;d+=1)e[d>>2]|=b.charCodeAt(d)<<(d%4<<3);this._finish(e,c);a=a?this._state:p(this._state);this.reset();return a};r.prototype._finish=function(a,b){a[b>>2]|=128<<(b%4<<3);if(55<b)for(f(this._state,a),b=0;16>b;b+=1)a[b]=0;var c=8*this._length;c=c.toString(16).match(/(.*?)(.{0,8})$/);b=parseInt(c[2],16);c=parseInt(c[1],16)||0;a[14]=b;a[15]=c;f(this._state,
a)};r.prototype.reset=function(){this._buff="";this._length=0;this._state=[1732584193,-271733879,-1732584194,271733878];return this};r.prototype.destroy=function(){delete this._state;delete this._buff;delete this._length};r.hash=function(a,b){/[\u0080-\uFFFF]/.test(a)&&(a=unescape(encodeURIComponent(a)));a=h(a);return b?a:p(a)};r.hashBinary=function(a,b){a=h(a);return b?a:p(a)};r.ArrayBuffer=function(){this.reset()};r.ArrayBuffer.prototype.append=function(a){var b=this._concatArrayBuffer(this._buff,
a),c=b.length;this._length+=a.byteLength;for(a=64;a<=c;a+=64)f(this._state,d(b.subarray(a-64,a)));this._buff=a-64<c?b.subarray(a-64):new Uint8Array(0);return this};r.ArrayBuffer.prototype.end=function(a){var b=this._buff,c=b.length,d=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],e;for(e=0;e<c;e+=1)d[e>>2]|=b[e]<<(e%4<<3);this._finish(d,c);a=a?this._state:p(this._state);this.reset();return a};r.ArrayBuffer.prototype._finish=r.prototype._finish;r.ArrayBuffer.prototype.reset=function(){this._buff=new Uint8Array(0);
this._length=0;this._state=[1732584193,-271733879,-1732584194,271733878];return this};r.ArrayBuffer.prototype.destroy=r.prototype.destroy;r.ArrayBuffer.prototype._concatArrayBuffer=function(a,b){var c=a.length,d=new Uint8Array(c+b.byteLength);d.set(a);d.set(new Uint8Array(b),c);return d};r.ArrayBuffer.hash=function(a,b){var c=new Uint8Array(a),e=c.length;a=[1732584193,-271733879,-1732584194,271733878];var g;for(g=64;g<=e;g+=64)f(a,d(c.subarray(g-64,g)));c=g-64<e?c.subarray(g-64):new Uint8Array(0);
var h=c.length;var k=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(g=0;g<h;g+=1)k[g>>2]|=c[g]<<(g%4<<3);k[g>>2]|=128<<(g%4<<3);if(55<g)for(f(a,k),g=0;16>g;g+=1)k[g]=0;e=(8*e).toString(16).match(/(.*?)(.{0,8})$/);c=parseInt(e[2],16);e=parseInt(e[1],16)||0;k[14]=c;k[15]=e;f(a,k);return b?a:p(a)};return g.register("Md5",{init:function(){},loadFromBlob:function(a){var b=a.getSource(),c=Math.ceil(b.size/2097152),d=0,e=this.owner,f=new r.ArrayBuffer,g=this,h=b.mozSlice||b.webkitSlice||b.slice;var k=new FileReader;
var l=function(){var m=2097152*d;var n=Math.min(m+2097152,b.size);k.onload=function(b){f.append(b.target.result);e.trigger("progress",{total:a.size,loaded:n})};k.onloadend=function(){k.onloadend=k.onload=null;++d<c?setTimeout(l,1):setTimeout(function(){e.trigger("load");g.result=f.end();l=a=b=f=null;e.trigger("complete")},50)};k.readAsArrayBuffer(h.call(b,m,n))};l()},getResult:function(){return this.result}})});p("webuploader","base widgets/filepicker widgets/image widgets/queue widgets/runtime widgets/upload widgets/validator widgets/md5 widgets/log runtime/html5/blob runtime/html5/filepicker runtime/html5/imagemeta/exif runtime/html5/image runtime/html5/androidpatch runtime/html5/transport runtime/html5/md5".split(" "),
function(g){return g});return C("webuploader")});
