var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,k,e){b instanceof String&&(b=String(b));for(var g=b.length,n=0;n<g;n++){var K=b[n];if(k.call(e,K,n,b))return{i:n,v:K}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,k,e){b!=Array.prototype&&b!=Object.prototype&&(b[k]=e.value)};$jscomp.getGlobal=function(b){b=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,b];for(var k=0;k<b.length;++k){var e=b[k];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,k,e,g){if(k){e=$jscomp.global;b=b.split(".");for(g=0;g<b.length-1;g++){var n=b[g];n in e||(e[n]={});e=e[n]}b=b[b.length-1];g=e[b];k=k(g);k!=g&&null!=k&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:k})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,e){return $jscomp.findInternal(this,b,e).v}},"es6","es3");
$jscomp.checkStringArgs=function(b,k,e){if(null==b)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(k instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return b+""};
$jscomp.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,e){var g=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var n=g.length,k=b.length;e=Math.max(0,Math.min(e|0,g.length));for(var v=0;v<k&&e<n;)if(g[e++]!=b[v++])return!1;return v>=k}},"es6","es3");
(function(b){var k=function(e,g){function n(a,d,B,e){if(""!=c.bizType){w.push(a);b("#"+h).val(w.join(",")).change();try{b("#"+h).resetValid()}catch(l){}}if(c.returnPath){x.push(d);A.push(B);b("#"+c.filePathInputId).val(x.join("|")).change();b("#"+c.fileNameInputId).val(A.join("|")).change();try{b("#"+c.filePathInputId).resetValid()}catch(l){}try{b("#"+c.fileNameInputId).resetValid()}catch(l){}}"function"==typeof c.callback&&c.callback(c.id,"addFile",g,a,d,B,e)}function k(a){var d=a.attr("fileUploadId"),
B=a.attr("fileUrl");a=a.attr("fileName");if(d&&null!=d){if(""!=c.bizType){w.splice(b.inArray(d,w),1);Q.push(d);b("#"+h).val(w.join(","));b("#"+h+"__del").val(Q.join(","));try{b("#"+h).resetValid()}catch(N){}try{b("#"+h+"__del").resetValid()}catch(N){}}if(c.returnPath){x.splice(b.inArray(B,x),1);A.splice(b.inArray(a,A),1);b("#"+c.filePathInputId).val(x.join("|"));b("#"+c.fileNameInputId).val(A.join("|"));try{b("#"+c.filePathInputId).resetValid()}catch(N){}try{b("#"+c.fileNameInputId).resetValid()}catch(N){}}}"function"==
typeof c.callback&&c.callback(c.id,"delFile",g,d,B,a)}function v(a){if(""!=c.bizType){w=[];a.each(function(){w.push(b(this).attr("fileUploadId"))});b("#"+h).val(w.join(",")).change();try{b("#"+h).resetValid()}catch(d){}}if(c.returnPath){x=[];A=[];a.each(function(){x.push(b(this).attr("fileUrl"));A.push(b(this).attr("fileName"))});b("#"+c.filePathInputId).val(x.join("|")).change();b("#"+c.fileNameInputId).val(A.join("|")).change();try{b("#"+c.filePathInputId).resetValid()}catch(d){}try{b("#"+c.fileNameInputId).resetValid()}catch(d){}}}
function t(){var a=m.getStats();if("confirm"===u&&a.uploadFailNum)var d=a.uploadFailNum+f(r?"\u5f20\u56fe\u7247":"\u4e2a\u6587\u4ef6")+f("\u4e0a\u4f20\u5931\u8d25")+', <a class="retry" href="#">'+f("\u91cd\u65b0\u4e0a\u4f20")+"</a>"+f("\u6216")+'<a class="ignore" href="#">'+f("\u5ffd\u7565")+"</a>";else"confirm"===u||"ready"===u?d=f("\u603b\u5171")+y+f(r?"\u5f20\u56fe\u7247":"\u4e2a\u6587\u4ef6")+(0>=C?"":"\uff08"+WebUploader.formatSize(C)+"\uff09"):(d=f("\u5df2\u4e0a\u4f20")+y+f(r?"\u5f20\u56fe\u7247":
"\u4e2a\u6587\u4ef6")+(0>=C?"":"\uff08"+WebUploader.formatSize(C)+"\uff09"),a.uploadFailNum&&(d+=", "+f("\u5931\u8d25{0}\u4e2a",a.uploadFailNum)));O.html(d);y<c.maxUploadNum?b("#"+h+"filePicker2").show():b("#"+h+"filePicker2").hide();"function"==typeof window.webuploaderRefresh&&window.webuploaderRefresh()}function E(){var a=0,d=0,c=0,e=L.children();b.each(z,function(b,d){c+=d[0];a+=d[0]*d[1]});d=c?a/c:0;e.eq(0).text(Math.round(100*d)+"%");e.eq(1).css("width",Math.round(100*d)+"%");t()}function D(a){if(a!==
u){F.removeClass("state-"+u);F.addClass("state-"+a);u=a;switch(u){case "pedding":P.removeClass("element-invisible");p.hide();H.addClass("element-invisible");break;case "ready":P.addClass("element-invisible");b("#"+h+"filePicker2").removeClass("element-invisible");p.show();H.removeClass("element-invisible");break;case "uploading":b("#"+h+"filePicker2").addClass("element-invisible");L.show();F.text(f("\u6682\u505c\u4e0a\u4f20"));break;case "paused":L.show();F.text(f("\u7ee7\u7eed\u4e0a\u4f20"));break;
case "confirm":L.hide();b("#"+h+"filePicker2").removeClass("element-invisible");F.text(f("\u5f00\u59cb\u4e0a\u4f20"));a=m.getStats();if(a.successNum&&!a.uploadFailNum){D("finish");return}break;case "finish":a=m.getStats(),a.successNum||(u="done")}t()}}function I(a,b){switch(b){case "exceed_size":b=f("\u6587\u4ef6\u5927\u5c0f\u8d85\u51fa");break;case "interrupt":b=f("\u6587\u4ef6\u4f20\u8f93\u4e2d\u65ad");break;case "http":b=f("HTTP\u8bf7\u6c42\u9519\u8bef");break;case "not_allow_type":b=f("\u6587\u4ef6\u683c\u5f0f\u4e0d\u5141\u8bb8");
break;default:b=f("\u4e0a\u4f20\u5931\u8d25\uff0c\u8bf7\u91cd\u8bd5")}null!=b&&(r?a.text(b):a.html('<span class="label label-sm label-danger">'+b+"</span>"))}function J(a){y--;y||D("pedding");C-=a.size;delete z[a.id];E();r?b("#"+h+a.id).off().find(".file-panel").off().end().remove():b("#"+h+a.id).off().find(".btncancel").off().end().remove()}var c=b.extend(!0,{},b.fn.webuploader.defaults,e),h=c.id,r="image"==c.uploadType,G=b("#"+h+"Uploader"),p=G.find("#"+h+"fileLists"),f=function(a,b){if(a){c.i18n=
c.i18n||{};var d=c.i18n[a];d&&""!=d||(d=a);if(b)for(var e=1;e<arguments.length;e++)d=d.replace(new RegExp("\\{"+(e-1)+"\\}","gm"),arguments[e]);return d}return a};r&&p.appendTo(G.find(".queueList"));var H=G.find(".statusBar"),O=H.find(".info"),F=G.find(".uploadBtn"),P=G.find(".placeholder"),L=H.find(".progress").hide(),y=0,C=0,M=window.devicePixelRatio||1,S=110*M,T=110*M,u="pedding",z={};M=function(){try{var a=navigator.plugins["Shockwave Flash"];a=a.description}catch(d){try{a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version")}catch(B){a=
"0.0"}}a=a.match(/\d+/g);return parseFloat(a[0]+"."+a[1],10)}();var R=function(){var a=document.createElement("p").style;return"transition"in a||"WebkitTransition"in a||"MozTransition"in a||"msTransition"in a||"OTransition"in a}(),w=[],Q=[],x=[],A=[];"false"===c.preview&&(c.preview="");if(WebUploader.browser.ie&&!WebUploader.Uploader.support("flash"))M?function(a){window.expressinstallcallback=function(a){switch(a){case "Download.Cancelled":alert(f("\u5b89\u88c5\u5931\u8d25\uff01"));break;case "Download.Failed":alert(f("\u5b89\u88c5\u5931\u8d25\uff01"));
break;default:alert(f("\u5b89\u88c5\u5df2\u6210\u529f\uff0c\u8bf7\u5237\u65b0\uff01"))}delete window.expressinstallcallback};var b=ctxStatic+"/webuploader/0.1/expressInstall.swf",c='<object type="application/x-shockwave-flash" data="'+b+'" ';WebUploader.browser.ie&&(c+='classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" ');a.html(c+('width="100%" height="100%" style="outline:0"><param name="movie" value="'+b+'" /><param name="wmode" value="transparent" /><param name="allowscriptaccess" value="always" /></object>'))}(G):
G.html('<a href="https://get.adobe.com/flashplayer" target="_blank" border="0"><img alt="Get Flash Player" src="http://www.adobe.com/macromedia/style_guide/images/160x41_Get_Flash_Player.jpg" /></a>');else{if(WebUploader.Uploader.support()){e={disableGlobalDnd:!0,swf:ctxStatic+"/webuploader/0.1/Uploader.swf",server:c.service.upload,id:h,imageFlag:r,formData:{bizKey:c.bizKey,bizType:c.bizType,uploadType:c.uploadType,imageMaxWidth:c.imageMaxWidth,imageMaxHeight:c.imageMaxHeight,chunkSize:c.chunkSize,
__ajax:"json"},chunked:c.chunked,chunkSize:c.chunkSize,threads:c.threads,fileNumLimit:c.maxUploadNum,fileSingleSizeLimit:c.maxFileSize,compress:!1};b.each(c.extendParams,function(a,b){e.formData["extend["+a+"]"]=b});c.readonly?P.hide():(e=b.extend(!0,{},{pick:{id:"#"+h+"filePicker",label:f("\u70b9\u51fb\u9009\u62e9\u6587\u4ef6"),multiple:1<c.maxUploadNum},dnd:"#"+h+"Uploader .queueList",paste:"#"+h+"Uploader .queueList"},e),"image"==c.uploadType?(e.pick.label=f("\u70b9\u51fb\u9009\u62e9\u56fe\u7247"),
e.accept={title:"Images",extensions:c.imageAllowSuffixes.replace(/\./g,""),mimeTypes:"image/*"}):"media"==c.uploadType?(e.pick.label=f("\u70b9\u51fb\u9009\u62e9\u89c6\u9891"),e.accept={title:"Medias",extensions:c.mediaAllowSuffixes.replace(/\./g,""),mimeTypes:"*/*"}):e.accept="file"==c.uploadType?{title:"Files",extensions:c.fileAllowSuffixes.replace(/\./g,""),mimeTypes:"*/*"}:{title:"All",extensions:(c.imageAllowSuffixes+","+c.mediaAllowSuffixes+","+c.fileAllowSuffixes).replace(/\./g,""),mimeTypes:"*/*"});
g.uploaderOptions=e;"function"==typeof c.callback&&c.callback(c.id,"create",g);var m=WebUploader.create(g.uploaderOptions);window.webuploader||(window.webuploader=[]);window.webuploader.push(m);g.uploader=m;g.options=c;window.webuploaderRefresh||(window.webuploaderRefresh=function(){setTimeout(function(){window.webuploader||(window.webuploader=[]);for(var a in window.webuploader)window.webuploader[a].refresh()},200)});m.addButton({id:"#"+h+"filePicker2",label:f("\u7ee7\u7eed\u6dfb\u52a0")});c.isLazy||
F.hide();m.on("uploadProgress",function(a,c){if(r){var d=b("#"+h+a.id);$percent=d.find(".progress span");$percent.css("width",100*c+"%")}else d=b("#"+h+a.id).find(".prog_bar"),$percent=d.find(".progress-bar"),$percent.css("width",Math.round(100*c)+"%"),$percent.text(Math.round(100*c)+"%");"undefined"==typeof z[a.id]&&(z[a.id]=[a.size,0]);z[a.id][1]=c;E()});m.on("beforeFileQueued",function(a){if(y>=c.maxUploadNum)return js.showMessage(f("\u60a8\u53ea\u80fd\u4e0a\u4f20{0}\u4e2a\u6587\u4ef6",c.maxUploadNum)),
!1});m.on("fileQueued",function(a){y++;C+=a.size;1!==y||c.readonly||H.show();if(r){var d=b('<li id="'+h+a.id+'"><p class="title" title="'+a.name+'">'+a.name+'</p><p class="imgWrap"></p><p class="progress"><span></span></p><p class="error"></p><div class="file-panel"><span class="cancel">'+f("\u5220\u9664")+"</span></div></li>"),e=d.find("div.file-panel"),g=d.find("p.progress-bar"),l=d.find("p.imgWrap"),q=d.find("p.error");"invalid"===a.getStatus()?I(q,a.statusText):(q.text(f("\u7b49\u5f85\u4e0a\u4f20")),
l.text(f("\u9884\u89c8\u751f\u6210\u4e2d")),m.makeThumb(a,function(a,c){a?l.text(f("\u4e0d\u80fd\u9884\u89c8")):(a=b('<img src="'+c+'">'),l.empty().append(a))},S,T),z[a.id]=[a.size,0],a.rotation=0);a.on("statuschange",function(b,c){"progress"===c&&g.hide().width(0);"error"===b||"invalid"===b?(I(q,a.statusText),z[a.id][1]=1):"interrupt"===b?I(q,"interrupt"):"queued"===b?z[a.id][1]=0:"progress"===b&&(q.text(f("\u6b63\u5728\u4e0a\u4f20")+"..."),g.css("display","block"));d.removeClass("state-"+c).addClass("state-"+
b)});d.on("mouseenter",function(){e.stop().animate({height:30})});d.on("mouseleave",function(){e.stop().animate({height:0})});e.on("click","span",function(){switch(b(this).index()){case 0:var c=b(this);js.confirm(f("\u786e\u5b9a\u5220\u9664\u8be5\u56fe\u7247\u5417\uff1f"),function(b){k(c);m.removeFile(a)});return;case 1:a.rotation+=90;break;case 2:a.rotation-=90}if(R){var d="rotate("+a.rotation+"deg)";l.css({"-webkit-transform":d,"-mos-transform":d,"-o-transform":d,transform:d})}else l.css("filter",
"progid:DXImageTransform.Microsoft.BasicImage(rotation="+~~(a.rotation/90%4+4)%4+")")})}else d=b('<tr id="'+h+a.id+'" class="template-upload"><td class="name" title="'+a.name+'"><i class="fa fa-file-text-o"></i>'+a.name+'</td><td class="size">'+WebUploader.formatSize(a.size)+'</td><td class="prog_bar"><p class="progress"><span class="progress-bar">0%</span></p></td><td class="msg"></td><td class="btncancel"><a class="btn btn-default btn-xs yellow delete"><i class="fa fa-ban"></i> '+f("\u5220\u9664")+
" </a></td></tr>"),e=d.find("td.btncancel"),g=d.find("td.progress-bar"),q=d.find("td.msg"),"invalid"===a.getStatus()?I(q,a.statusText):(q.text(f("\u7b49\u5f85\u4e0a\u4f20")),z[a.id]=[a.size,0],a.rotation=0),a.on("statuschange",function(b,c){"error"===b||"invalid"===b?(I(q,a.statusText),z[a.id][1]=1,g.text("0%").css("width","0%")):"interrupt"===b?(I(q,"interrupt"),g.text("0%").css("width","0%")):"progress"===b&&(q.text(f("\u6b63\u5728\u4e0a\u4f20")+"..."),g.css("display","block"));d.removeClass("state-"+
c).addClass("state-"+b)}),e.on("click","a.delete",function(){var c=b(this);js.confirm(f("\u786e\u5b9a\u5220\u9664\u8be5\u6587\u4ef6\u5417\uff1f"),function(b){k(c);m.removeFile(a)})});d.appendTo(p);D("ready");E();c.isLazy||m.upload()});m.on("fileDequeued",function(a){J(a)});m.on("uploadAccept",function(a,c,e){a=b("#"+h+a.file.id);try{var d=JSON.parse(c._raw||c);"false"==d.result&&e(d.code);if(r)a.find("p.error").html('<span title="'+d.message+'">'+d.message+"</span>").delay(4E3).slideUp(500);else{var B=
"true"==d.result?"success":"danger";a.find(".msg").html('<span class="label label-sm label-'+B+'" title="'+d.message+'">'+d.message+"</span>")}}catch(q){r?a.find("p.error").html("<span>"+f("\u670d\u52a1\u5668\u8fd4\u56de\u51fa\u9519")+"</span>"):a.find(".msg").html('<span class="label label-sm label-danger">'+f("\u670d\u52a1\u5668\u8fd4\u56de\u51fa\u9519")+"</span>")}});m.on("uploadError",function(a,b){a.fileUpload&&(0<p.find("[fileMd5="+a.md5+"]").length?r?p.find("#"+h+a.id+" .error").html(f("\u4e0d\u8981\u9009\u62e9\u91cd\u590d\u6587\u4ef6")):
p.find("#"+h+a.id+" .msg .label").html(f("\u4e0d\u8981\u9009\u62e9\u91cd\u590d\u6587\u4ef6")):(m.removeFile(a),g.refreshFileList([a.fileUpload],!1)))});m.on("uploadSuccess",function(a,d){a=b("#"+h+a.id);var e=a.find(".progress-bar");try{var g=JSON.parse(d._raw||d);if("true"==g.result){var l=g.fileUpload,q=(js.startWith(l.fileUrl,ctxPath)||js.startWith(l.fileUrl,"http://")||js.startWith(l.fileUrl,"https://")?"":ctxPath)+l.fileUrl,k=c.returnPath?q:c.service.download+l.id;r?(a.find(".imgWrap img").attr("src",
q),a.find(".file-panel .cancel").attr("fileUploadId",l.id).attr("fileUrl",q).attr("fileName",l.fileName).attr("fileSize",l.fileEntity.fileSize).attr("fileMd5",l.fileEntity.fileMd5)):(""!=c.preview?a.find(".name").html('<i class="fa fa-file-text-o"></i><a class="preview" href="javascript:">'+l.fileName+"</a>"):a.find(".name").html('<i class="fa fa-file-text-o"></i><a target="_blank" href="'+k+'">'+l.fileName+"</a>"),a.find(".btncancel").empty().append((""!=c.preview?'<a class="btn btn-default btn-xs preview" href="javascript:"><i class="fa fa-eye"></i> '+
f("\u9884\u89c8")+"</a> &nbsp;":"")+'<a class="btn btn-danger btn-xs delete" fileUploadId="'+l.id+'" fileUrl="'+q+'" fileName="'+l.fileName+'" fileSize="'+l.fileEntity.fileSize+'" fileMd5="'+l.fileEntity.fileMd5+'"><i class="fa fa-trash-o"></i> '+f("\u5220\u9664")+'</a> &nbsp;<a class="btn btn-info btn-xs" target="_blank" href="'+k+'" ><i class="fa fa-download"></i> '+f("\u4e0b\u8f7d")+"</a>"));n(l.id,q,l.fileName,l)}else e.css("width","0%").text("0%")}catch(U){e.css("width","0%").text("0%"),error(U)}t()});
m.on("error",function(a){switch(a){case "Q_EMPTY_FILE":a=f("\u4e0d\u80fd\u4e0a\u4f20\u7a7a\u6587\u4ef6");break;case "Q_TYPE_DENIED":a=f("\u6587\u4ef6\u7c7b\u578b\u4e0d\u5bf9");break;case "F_EXCEED_SIZE":a=f("\u6587\u4ef6\u5927\u5c0f\u8d85\u51fa");break;case "F_DUPLICATE":a=f("\u4e0d\u8981\u9009\u62e9\u91cd\u590d\u6587\u4ef6");break;case "Q_EXCEED_NUM_LIMIT":a=f("\u60a8\u53ea\u80fd\u4e0a\u4f20{0}\u4e2a\u6587\u4ef6",c.maxUploadNum);break;case "Q_EXCEED_SIZE_LIMIT":a=f("\u6587\u4ef6\u5927\u5c0f\u8d85\u51fa");
break;default:a=f("\u4e0a\u4f20\u5931\u8d25\uff0c\u8bf7\u91cd\u8bd5")}js.showMessage(a)});m.on("all",function(a,b){switch(a){case "uploadFinished":D("confirm");break;case "startUpload":D("uploading");break;case "stopUpload":D("paused")}});F.on("click",function(){if(b(this).hasClass("disabled"))return!1;"ready"===u?m.upload():"paused"===u?m.upload():"uploading"===u&&m.stop()});O.on("click",".retry",function(){m.retry();return!1});O.on("click",".ignore",function(){var a,b,c=m.getFiles("error");for(b=
0;a=c[b++];)m.removeFile(a);D("finish");E();return!1});p.sortable&&(r?p.sortable({connectWith:"li",handle:".imgWrap img",placeholder:"sort-highlight",forcePlaceholderSize:!0,zIndex:999999,update:function(a,b){v(p.find("li .file-panel .cancel"))}}):p.sortable({connectWith:"tr",handle:".name i",placeholder:"sort-highlight",forcePlaceholderSize:!0,zIndex:999999,update:function(a,b){v(p.find("tr .btncancel .delete"))}}));if(""!=c.preview)p.on("click",".imgWrap img, a.preview",function(){var a=b(this);
if(js.startsWith(d,"data:"))js.showMessage(f("\u4e0d\u80fd\u9884\u89c8"));else if(a="IMG"==a.prop("tagName")?a.closest("li").find(".file-panel .cancel"):a.closest("tr").find(".btncancel .delete"),0==a.length)js.showMessage(f("\u4e0d\u80fd\u9884\u89c8"));else{var d=a.attr("fileUrl");if(js.startsWith(d,"http://")||js.startsWith(d,"https://"))d=ctxPath+"/userfiles/?url="+js.encodeUrl(d),d+="&uid="+a.attr("fileUploadId");d+=-1==d.indexOf("?")?"?":"&";d+="fileName="+js.encodeUrl(a.attr("fileName"));d+=
"&preview="+c.preview;if(js.layer){a=b(js.window).width();a=800>a?a-30:a-200;var e=b(js.window).height();js.layer.open({type:2,maxmin:!0,shadeClose:!0,title:!1,area:[a+"px",(500>e?e-30:e-50)+"px"],content:d})}else js.windowOpen(d)}});else if(r)p.on("click",".imgWrap img",function(){var a=b(this).attr("src");0==b("#outerdiv").length&&b('<div id="outerdiv" style="position:fixed;top:0;left:0;background:rgba(0,0,0,0.7);z-index:99999;width:100%;height:100%;display:none;"><div id="innerdiv" style="position:fixed;"><img id="bigimg" style="border:2px solid #fff;" src="" /></div></div>').appendTo(document.body);
b("#bigimg").attr("src",a);b("<img/>").attr("src",a).load(function(){var a=b(window).width(),c=b(window).height(),e=this.width,g=this.height;if(g>.8*c){var f=.8*c;var h=f/g*e;h>.8*a&&(h=.8*a)}else e>.8*a?(h=.8*a,f=h/e*g):(h=e,f=g);b("#bigimg").css("width",h);a=(a-h)/2;c=(c-f)/2;b("#innerdiv").css({top:c,left:a});b("#outerdiv").fadeIn("fast")});b("#outerdiv").click(function(){b(this).fadeOut("fast")})});g.refreshFileList=function(a,e){e&&(p.empty(),C=y=0,w=[],x=[],A=[]);if(a&&0<a.length)for(e=0;e<
a.length;e++){var d=a[e],h=(js.startWith(d.fileUrl,ctxPath)||js.startWith(d.fileUrl,"http://")||js.startWith(d.fileUrl,"https://")?"":ctxPath)+d.fileUrl,l=c.returnPath?h:c.service.download+d.id;if(r)$li=b('<li id="'+d.id+'"><p class="title"><a target="_blank" href="'+l+'" title="'+d.fileName+" | "+d.createByName+" | "+d.createDate+'">'+d.fileName+'</a></p><p class="imgWrap"><img src="'+h+'"/></p><p class="progress"><span></span></p><div class="file-panel"><span class="cancel '+(c.readonly?"hide":
"")+'" fileUploadId="'+d.id+'" fileUrl="'+h+'" fileName="'+d.fileName+'" fileSize="'+d.fileEntity.fileSize+'" fileMd5="'+d.fileEntity.fileMd5+'">'+f("\u5220\u9664")+"</span></div></li>"),d.message&&$li.append(d.message).find("p.error").delay(4E3).slideUp(500),$li.on("mouseenter",function(){var a=b(this).index();p.find(".file-panel").eq(a).stop().animate({height:30})}),$li.on("mouseleave",function(){var a=b(this).index();p.find(".file-panel").eq(a).stop().animate({height:0})}),$li.on("click","span",
function(){var a=b(this),d=b(this).closest("li"),e=b(this).parent().data("fileRotation");e||(e=0);switch(a.index()){case 0:if(!c.readonly){var g=b(this);js.confirm(f("\u786e\u5b9a\u5220\u9664\u8be5\u56fe\u7247\u5417\uff1f"),function(a){k(g);c.returnPath?J({id:0,size:0}):(a=g.attr("fileSize"),J({id:0,size:a}));d.remove()})}return;case 1:e+=90;break;case 2:e-=90}a=b(this).parent().parent().index();a=p.find(".imgWrap :eq("+a+")");if(R){var h="rotate("+e+"deg)";a.css({"-webkit-transform":h,"-mos-transform":h,
"-o-transform":h,transform:h})}else a.css("filter","progid:DXImageTransform.Microsoft.BasicImage(rotation="+~~(e/90%4+4)%4+")");b(this).parent().data("fileRotation",e)});else if($li=b('<tr id="'+d.id+'" class="template-upload"><td class="name" title="'+d.fileName+'"><i class="fa fa-file-text-o"></i>'+d.fileName+'</td><td class="size">'+(c.returnPath?"":WebUploader.formatSize(d.fileEntity.fileSize))+'</td><td class="prog_bar">'+(d.progress?d.progress:d.createByName?d.createByName:"")+'</td><td class="msg">'+
(d.message?d.message:d.createDate?d.createDate:"")+'</td><td class="btncancel">'+(""!=c.preview?'<a class="btn btn-default btn-xs preview" href="javascript:"><i class="fa fa-eye"></i> '+f("\u9884\u89c8")+"</a> &nbsp;":"")+'<a class="btn btn-danger btn-xs delete'+(c.readonly?" hide":"")+'" fileUploadId="'+d.id+'" fileUrl="'+h+'" fileName="'+d.fileName+'" fileSize="'+d.fileEntity.fileSize+'" fileMd5="'+d.fileEntity.fileMd5+'"><i class="fa fa-trash-o"></i> '+f("\u5220\u9664")+" </a>"+(c.readonly?"":
" &nbsp;")+'<a class="btn btn-info btn-xs blue" target="_blank" href="'+l+'"><i class="fa fa-download"></i> '+f("\u4e0b\u8f7d")+" </a></td></tr>"),""!=c.preview?$li.find(".name").html('<i class="fa fa-file-text-o"></i><a class="preview" href="javascript:">'+d.fileName+"</a>"):$li.find(".name").html('<i class="fa fa-file-text-o"></i><a target="_blank" href="'+l+'">'+d.fileName+"</a>"),!c.readonly)$li.on("click","a.delete",function(){var a=b(this),d=b(this).closest("tr");js.confirm(f("\u786e\u5b9a\u5220\u9664\u8be5\u6587\u4ef6\u5417\uff1f"),
function(b){k(a);c.returnPath?J({id:0,size:0}):(b=a.attr("fileSize"),J({id:0,size:b}));d.remove()})});y++;C+=d.fileEntity.fileSize;p.append($li);n(d.id,h,d.fileName,d)}if(0<w.length||0<x.length)c.readonly||H.show(),D("ready");E();"function"==typeof c.callback&&c.callback(c.id,"ready",g)};g.refreshFileListByPath=function(){var a=[],d=[],e,f=b("#"+c.filePathInputId).val(),h=b("#"+c.fileNameInputId).val();void 0!=f&&""!=f&&(d=f.split("|"));void 0!=h&&""!=h&&(e=h.split("|"));if(void 0==e||e.length!=d.length)e=
d;b.each(d,function(b,c){b=e[b].split("/");b=b[b.length-1];a.push({id:String(Math.random()).replace(".",""),fileName:b,fileUrl:c,fileEntity:{fileSize:0}})});g.refreshFileList(a,!0)};g.refreshFileListByBizData=function(){b.ajax({url:c.service.fileList+(-1==c.service.fileList.indexOf("?")?"?":"&")+"__t="+(new Date).getTime(),data:{bizKey:c.bizKey,bizType:c.bizType},xhrFields:{withCredentials:!0},dataType:"json",success:function(a){"false"!=a.result&&g.refreshFileList(a,!0)}})};""!=c.bizKey&&""!=c.bizType?
g.refreshFileListByBizData():c.returnPath&&g.refreshFileListByPath();return g}js.showMessage(f("\u6587\u4ef6\u4e0a\u4f20\u7ec4\u4ef6\u4e0d\u652f\u6301\u60a8\u7684\u6d4f\u89c8\u5668\uff0c\u8bf7\u4f7f\u7528\u9ad8\u7248\u672c\u6d4f\u89c8\u5668\uff01"))}};window.webuploaderRegister||(window.webuploaderRegister=!0,WebUploader.Uploader.register({name:"fileupload","before-send-file":"beforeSendFile","before-send":"beforeSend","after-send-file":"afterSendFile"},{beforeSendFile:function(e){var g=this.owner,
k=WebUploader.Deferred();g.md5File(e,0,10485760).then(function(n){e.md5=n;b.ajax({type:"POST",url:g.options.server,data:{fileMd5:n,fileName:e.name},cache:!1,async:!1,timeout:1E4,dataType:"json",error:function(b){js.error(js.abbr(b.responseText,500));k.reject()},success:function(b){"true"==b.result?(e.fileUpload=b.fileUpload,g.options.imageFlag?e.fileUpload.message='<p class="error" title="'+b.message+'">'+b.message+"</p>":(e.fileUpload.progress='<p class="progress"><span class="progress-bar" style="display:block;width:100%;">100%</span></p>',
e.fileUpload.message='<span class="label label-sm label-success" title="'+b.message+'">'+b.message+"</span>"),g.skipFile(e),k.reject()):(e.fileUploadId=b.fileUploadId,e.fileEntityId=b.fileEntityId,k.resolve())}})});return k.promise()},beforeSend:function(b){var e=this.owner;b=b.file;e.options.formData.fileMd5=b.md5;e.options.formData.fileName=b.name;e.options.formData.fileUploadId=b.fileUploadId;e.options.formData.fileEntityId=b.fileEntityId},afterSendFile:function(b){}}),b("textarea").each(function(){var e=
b(this);e.data("x",e.outerWidth());e.data("y",e.outerHeight());e.mouseup(function(){var e=b(this);e.outerWidth()==e.data("x")&&e.outerHeight()==e.data("y")||"function"!=typeof window.webuploaderRefresh||window.webuploaderRefresh();e.data("x",e.outerWidth());e.data("y",e.outerHeight())})}));b.fn.webuploader=function(e,g){var n,K=this.each(function(){var v=b(this),t=v.data("webuploader"),E="object"===typeof e&&e;t||(t=new k(E,v),v.data("webuploader",t));"string"===typeof e&&"function"===typeof t[e]&&
(n=g instanceof Array?t[e].apply(t,g):t[e](g))});return void 0===n?K:n};b.fn.webuploader.defaults={id:"",bizKey:"",bizType:"",readonly:!1,returnPath:!1,filePathInputId:"",fileNameInputId:"",uploadType:"",imageAllowSuffixes:".gif,.bmp,.jpeg,.jpg,.ico,.png,.tif,.tiff,",mediaAllowSuffixes:".flv,.swf,.mkv,webm,.mid,.mov,.mp3,.mp4,.m4v,.mpc,.mpeg,.mpg,.swf,.wav,.wma,.wmv,.avi,.rm,.rmi,.rmvb,.aiff,.asf,.ogg,.ogv,",fileAllowSuffixes:".doc,.docx,.rtf,.xls,.xlsx,.csv,.ppt,.pptx,.pdf,.vsd,.txt,.md,.xml,.rar,.zip,7z,.tar,.tgz,.jar,.gz,.gzip,.bz2,.cab,.iso,",
maxFileSize:104857600,maxUploadNum:300,imageMaxWidth:1024,imageMaxHeight:768,service:{upload:ctxAdmin+"/file/upload",download:ctxAdmin+"/file/download/",fileList:ctxAdmin+"/file/fileList"},extendParams:{},chunked:!1,chunkSize:10485760,threads:3,isLazy:!1,preview:""}})(jQuery);
