var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,f=0;f<d;f++){var e=a[f];if(b.call(c,e,f,a))return{i:f,v:e}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
TabPanel=function(a,b){this.renderTo=a.renderTo||$(document.body);this.border=a.border||"none";this.render="undefined"!=typeof b?b:"string"==typeof this.renderTo?$("#"+this.renderTo):this.renderTo;this.widthResizable=a.widthResizable;this.heightResizable=a.heightResizable;this.autoResizable=a.autoResizable?!0:!1;this.width=a.width||"100%";this.height=a.height||"100%";this.items=a.items;this.active=a.active||0;this.tabs=[];this.scrolled=!1;this.tabWidth=a.tabWidth||-1;this.fixNum=2;this.scrollFinish=
!0;this.maxzindex=0;this.maxLength=a.maxLength||20;this.rightMenu=a.rightMenu||!0;this.init()};
TabPanel.prototype={init:function(){var a=this;this.autoResizable&&(this.widthResizable=this.heightResizable=!0,this.render.css("overflow","hidden"),$(window).resize(function(){a.resize();window.setTimeout(function(){a.resize()},200)}));"function"==typeof this.width?this.render.width=this.width:this.render.width(this.width);"function"==typeof this.height?this.render.height=this.height:this.render.height(this.height);var b="none"!=this.border?2:0;this.tabpanel=$("<DIV></DIV>");this.tabpanel.addClass("tabpanel");
this.tabpanel.width(this.render.width()-b);this.tabpanel.height(this.render.height()-b);this.render.append(this.tabpanel);this.tabpanel_tab_content=$("<DIV></DIV>");this.tabpanel_tab_content.addClass("tabpanel_tab_content");1==this.maxLength&&this.tabpanel_tab_content.addClass("hide");this.tabpanel_tab_content.appendTo(this.tabpanel);this.tabpanel_left_scroll=$("<DIV></DIV>");this.tabpanel_left_scroll.bind("click",function(){a.moveLeft()});this.tabpanel_left_scroll.addClass("tabpanel_left_scroll");
this.tabpanel_left_scroll.addClass("display_none");this.tabpanel_left_scroll.bind("mouseover",function(){var a=$(this);a.addClass("tabpanel_scroll_over");a.bind("mouseout",function(){a.unbind("mouseout");a.removeClass("tabpanel_scroll_over")})});this.tabpanel_left_scroll.appendTo(this.tabpanel_tab_content);this.tabpanel_right_scroll=$("<DIV></DIV>");this.tabpanel_right_scroll.bind("click",function(){a.moveRight()});this.tabpanel_right_scroll.addClass("tabpanel_right_scroll");this.tabpanel_right_scroll.addClass("display_none");
this.tabpanel_right_scroll.bind("mouseover",function(){var a=$(this);a.addClass("tabpanel_scroll_over");a.bind("mouseout",function(){a.unbind("mouseout");a.removeClass("tabpanel_scroll_over")})});this.tabpanel_right_scroll.appendTo(this.tabpanel_tab_content);this.tabpanel_move_content=$("<DIV></DIV>");this.tabpanel_move_content.addClass("tabpanel_move_content");this.tabpanel_move_content.appendTo(this.tabpanel_tab_content);this.tabpanel_mover=$("<UL></UL>");this.tabpanel_mover.addClass("tabpanel_mover");
this.tabpanel_mover.appendTo(this.tabpanel_move_content);this.tabpanel_tab_spacer=$("<DIV></DIV>");this.tabpanel_tab_spacer.addClass("tabpanel_tab_spacer");this.tabpanel_tab_spacer.appendTo(this.tabpanel_tab_content);this.tabpanel_content=$("<DIV></DIV>");this.tabpanel_content.addClass("tabpanel_content");this.tabpanel_content.appendTo(this.tabpanel);b=this.tabpanel.width();var c=this.tabpanel.height();"none"==this.border&&this.tabpanel.css("border","none");this.tabpanel_tab_content.width(b);this.tabpanel_content.width(b);
this.tabpanel_content.height(c-this.tabpanel_tab_content.get(0).offsetHeight);this.update();for(b=0;b<this.items.length;b++)this.items[b].notExecuteMoveSee=!0,this.addTab(this.items[b]);0<=this.active&&this.show(this.active,!1)},moveLeft:function(){this.scrollFinish&&(this.disableScroll(),this.scrollFinish=!1,Fader.apply(this,Array({element:this.tabpanel_mover,style:"marginLeft",num:this.tabWidth,maxMove:this.maxMove,onFinish:this.useableScroll})),this.run())},moveRight:function(){this.scrollFinish&&
(this.disableScroll(),this.scrollFinish=!1,Fader.apply(this,Array({element:this.tabpanel_mover,style:"marginLeft",num:-1*this.tabWidth,maxMove:this.maxMove,onFinish:this.useableScroll})),this.run())},moveToLeft:function(){if(this.scrolled&&this.scrollFinish){this.disableScroll();this.scrollFinish=!1;var a=-1*parseInt(this.tabpanel_mover.css("marginLeft"));Fader.apply(this,Array({element:this.tabpanel_mover,style:"marginLeft",num:a,maxMove:this.maxMove,interval:20,step:10>a/10?10:a/10,onFinish:this.useableScroll}));
this.run()}},moveToRight:function(){if(this.scrolled&&this.scrollFinish){this.disableScroll();this.scrollFinish=!1;var a=-1*parseInt(this.tabpanel_mover.css("marginLeft")),b=this.tabpanel_mover.children().length*this.tabWidth,c=this.tabpanel_move_content.width();a=-1*(b-c-a+this.fixNum);Fader.apply(this,Array({element:this.tabpanel_mover,style:"marginLeft",num:a,maxMove:this.maxMove,step:10>-1*a/10?10:-1*a/10,onFinish:this.useableScroll}));this.run()}},moveToSee:function(a){if(this.scrolled){var b=
this.tabWidth*a;a=parseInt(this.tabpanel_mover.css("marginLeft"));0>=a?(b=-1*(a+b),-1*(b+a)>=this.maxMove?this.moveToRight():(this.disableScroll(),this.scrollFinish=!1,Fader.apply(this,Array({element:this.tabpanel_mover,style:"marginLeft",num:b,maxMove:this.maxMove,step:10>b/10?10:b/10,onFinish:this.useableScroll})),this.run())):(b=-1*(b-a),-1*b>=this.maxMove?this.moveToRight():(this.disableScroll(),this.scrollFinish=!1,Fader.apply(this,Array({element:this.tabpanel_mover,style:"marginLeft",num:b,
maxMove:this.maxMove,onFinish:this.useableScroll})),this.run()))}},disableScroll:function(){this.tabpanel_left_scroll.addClass("tabpanel_left_scroll_disabled");this.tabpanel_left_scroll.attr("disabled",!0);this.tabpanel_right_scroll.addClass("tabpanel_right_scroll_disabled");this.tabpanel_right_scroll.attr("disabled",!0)},useableScroll:function(){this.scrolled&&(0==parseInt(this.tabpanel_mover.css("marginLeft"))?(this.tabpanel_left_scroll.addClass("tabpanel_left_scroll_disabled"),this.tabpanel_left_scroll.attr("disabled",
!0),this.tabpanel_right_scroll.removeClass("tabpanel_right_scroll_disabled"),this.tabpanel_right_scroll.removeAttr("disabled")):-1*parseInt(this.tabpanel_mover.css("marginLeft"))==this.maxMove?(this.tabpanel_left_scroll.removeClass("tabpanel_left_scroll_disabled"),this.tabpanel_left_scroll.removeAttr("disabled",!0),this.tabpanel_right_scroll.addClass("tabpanel_right_scroll_disabled"),this.tabpanel_right_scroll.attr("disabled")):(this.tabpanel_left_scroll.removeClass("tabpanel_left_scroll_disabled"),
this.tabpanel_left_scroll.removeAttr("disabled",!0),this.tabpanel_right_scroll.removeClass("tabpanel_right_scroll_disabled"),this.tabpanel_right_scroll.removeAttr("disabled")));this.scrollFinish=!0},update:function(){var a=this.tabpanel_tab_content.width();this.scrolled&&(a-=this.tabpanel_left_scroll.width()+this.tabpanel_right_scroll.width());this.tabpanel_move_content.width(a);this.maxMove=this.tabpanel_mover.children().length*this.tabWidth-a+this.fixNum},showScroll:function(){var a=this.tabpanel_mover.children().length*
this.tabWidth,b=this.tabpanel_tab_content.width();a>b&&!this.scrolled?(this.tabpanel_move_content.addClass("tabpanel_move_content_scroll"),this.tabpanel_left_scroll.removeClass("display_none"),this.tabpanel_right_scroll.removeClass("display_none"),this.scrolled=!0):a<b&&this.scrolled&&(this.moveToLeft(),this.tabpanel_move_content.removeClass("tabpanel_move_content_scroll"),this.tabpanel_left_scroll.addClass("display_none"),this.tabpanel_right_scroll.addClass("display_none"),this.scrolled=!1,this.scrollFinish=
!0)},addTab:function(a){a.id=a.id||Math.uuid();if(0<$("#"+a.id).length)this.show(a.id,!1),1==a.refresh&&$("#"+a.id+" .refresher").click();else if(this.scrollFinish){var b=this;if(-1!=this.maxLength&&this.maxLength<=this.tabs.length)for(var c=0;c<this.tabs.length;c++)if(this.tabs[c].closable){b.kill(c,!0);break}c=$("<LI></LI>");c.attr("id",a.id);c.attr("unselectable","on");c.attr("style","-moz-user-select:none;");c.attr("onselectstart","return false;");c.appendTo(this.tabpanel_mover);-1==this.tabWidth&&
(this.tabWidth=c.outerWidth(!0));var d=$("<DIV></DIV>");d.html(a.title);d.appendTo(c);a.icon?(d.addClass("icon_title"),d.css("background-image",'url("'+a.icon+'")')):d.addClass("title");d.attr("title",$("<div>"+a.title+"</div>").text());var f=$("<DIV></DIV>");f.addClass("refresher");f.appendTo(c);var e=$("<DIV></DIV>");e.addClass("closer");e.attr("title",TabPanel.i18n.close);e.appendTo(c);var g=$("<DIV></DIV>");g.addClass("html_content");navigator.userAgent.match(/iPad|iPhone/i)&&g.addClass("iframe-ios");
g.appendTo(this.tabpanel_content);var h=this.tabpanel_mover.children().index(this.tabpanel_mover.find(".active")[0]);0>h&&(h=0);a.preTabId=this.tabs.length>h?this.tabs[h].id:"";a.tab=c;a.title=d;a.refresher=f;a.closer=e;a.content=g;a.disable=void 0==a.disable?!1:a.disable;a.closable=void 0==a.closable?!0:a.closable;0==a.closable&&e.addClass("display_none");1==a.disabled&&(c.attr("disabled",!0),d.addClass("disabled"));this.tabs.push(a);c.bind("click",function(a){return function(){b.show(a,!1)}}(this.tabs.length-
1));f.bind("click",function(a){return function(){b.refresh(a)}}(this.tabs.length-1));e.bind("click",function(a){return function(){b.kill(a)}}(this.tabs.length-1));a.closable&&c.bind("dblclick",function(a){return function(){b.kill(a)}}(this.tabs.length-1));a.lazyload||this.show(this.tabs.length-1,a.notExecuteMoveSee);this.showScroll();this.update();a.lazyload||a.notExecuteMoveSee||this.moveToRight();this.rightMenu&&(c=$(b.render).attr("id"),$("#"+a.id).RightMenu(a.id+"-rightmenu",{tabId:c,tabitemId:a.id,
menuList:[{menuName:TabPanel.i18n.refreshTab,menuClass:"",clickEvent:"$('#"+a.id+" .refresher').click();"},{menuName:TabPanel.i18n.closeOther,menuClass:"",clickEvent:"$('#"+a.id+"').click();$('#"+c+" .tabpanel_tab_content li:not(.active) .closer:not(.display_none)').addClass('batch').click();"},{menuName:TabPanel.i18n.closeLeft,menuClass:"",clickEvent:"$('#"+a.id+"').click();$('#"+c+" .tabpanel_tab_content li:lt('+$('#"+$(b.render).attr("id")+" .tabpanel_tab_content li.active').index()+') .closer:not(.display_none)').addClass('batch').click();"},
{menuName:TabPanel.i18n.closeRight,menuClass:"",clickEvent:"$('#"+a.id+"').click();$('#"+c+" .tabpanel_tab_content li:gt('+$('#"+$(b.render).attr("id")+" .tabpanel_tab_content li.active').index()+') .closer:not(.display_none)').addClass('batch').click();"},{menuName:TabPanel.i18n.detachTab,menuClass:"",clickEvent:"$('#"+a.id+"').click();window.open($('#"+a.id+"-frame').attr('src'));"}]}))}},getTabPosision:function(a){if("string"==typeof a)for(var b=0;b<this.tabs.length;b++)if(a==this.tabs[b].id){a=
b;break}return a},refresh:function(a){a=this.getTabPosision(a);if("string"==typeof a)return!1;this.tabs[a].tab.removeClass("active");this.tabs[a].content.html("");this.show(a)},iterateFlush:function(a){if(0<a.window.frames.length)for(var b=0;b<a.window.frames.length;b++)this.iterateFlush(a.window.frames[b]);else if(0<a.document.forms.length)for(b=0;b<a.document.forms.length;b++)try{a.document.forms[b].submit()}catch(c){a.location.reload()}else a.location.reload()},show:function(a,b){if(1>this.tabs.length)return!1;
a=this.getTabPosision(a);"string"==typeof a&&(a=0);this.scrollFinish&&(a>=this.tabs.length&&(a=0),this.render.find(".html_content").css("visibility","hidden"),this.tabs[a].content.css("visibility","visible"),this.tabs[a].content.css("z-index",++this.maxzindex),this.tabs[a].tab.hasClass("active")||(""==this.tabs[a].content.html()&&this.tabs[a].content.html(this.tabs[a].html),this.tabpanel_mover.find(".active").removeClass("active"),this.tabs[a].tab.addClass("active")),b||this.moveToSee(a),"function"==
typeof this.tabs[a].onActiveTab&&this.tabs[a].onActiveTab(a))},kill:function(a,b){var c=this;a=this.getTabPosision(a);if("function"!=typeof this.tabs[a].onPreClose||0!=this.tabs[a].onPreClose(a)){var d=this.tabs[a].preTabId;0>=$("#"+d).length&&this.tabs[a-1]&&(d=this.tabs[a-1].id);var f=$("#"+this.tabs[a].id+" .closer").hasClass("batch");f||$("#"+this.tabs[a].id).hasClass("active")||(b=!0);this.tabs[a].closer.remove();this.tabs[a].title.remove();this.tabs[a].tab.remove();this.tabs[a].content.remove();
$("#"+this.tabs[a].id+"-rightmenu").remove();this.tabs.splice(a,1);for(a=0;a<this.tabs.length;a++)this.tabs[a].tab.unbind("click"),this.tabs[a].tab.bind("click",function(a){return function(){c.show(a,!1)}}(a)),this.tabs[a].refresher.unbind("click"),this.tabs[a].refresher.bind("click",function(a){return function(){c.refresh(a)}}(a)),this.tabs[a].closer.unbind("click"),this.tabs[a].closer.bind("click",function(a){return function(){c.kill(a)}}(a)),this.tabs[a].closable&&(this.tabs[a].tab.unbind("dblclick"),
this.tabs[a].tab.bind("dblclick",function(a){return function(){c.kill(a)}}(a)));if(1!=b){var e=this;setTimeout(function(){e.update();e.showScroll();e.show(d,!1)},f?500:0)}}},getTabsCount:function(){return this.tabs.length},setTitle:function(a,b){a=this.getTabPosision(a);a<this.tabs.length&&this.tabs[a].title.text(b)},getTitle:function(a){a=this.getTabPosision(a);return this.tabs[a].title.text()},setContent:function(a,b){a=this.getTabPosision(a);a<this.tabs.length&&this.tabs[a].content.html(b)},getContent:function(a){a=
this.getTabPosision(a);return this.tabs[a].content.html()},setDisable:function(a,b){a=this.getTabPosision(a);a<this.tabs.length&&((this.tabs[a].disable=b)?(this.tabs[a].tab.attr("disabled",!0),this.tabs[a].title.addClass("disabled")):(this.tabs[a].tab.removeAttr("disabled"),this.tabs[a].title.removeClass("disabled")))},getDisable:function(a){a=this.getTabPosision(a);return this.tabs[a].disable},setClosable:function(a,b){a=this.getTabPosision(a);a<this.tabs.length&&((this.tabs[a].closable=b)?this.tabs[a].closer.addClass("display_none"):
(this.tabs[a].closer.addClass("closer"),this.tabs[a].closer.removeClass("display_none")))},getClosable:function(a){a=this.getTabPosision(a);return this.tabs[a].closable},getActiveIndex:function(){return this.tabpanel_mover.children().index(this.tabpanel_mover.find(".active")[0])},getActiveTab:function(){var a=this.tabpanel_mover.children().index(this.tabpanel_mover.find(".active")[0]);return this.tabs.length>a?this.tabs[a]:null},resize:function(){var a="none"==this.border?0:2;this.widthResizable&&
(this.width=this.render.width(),this.tabpanel.width(this.width-a),this.tabpanel_tab_content.width(this.width-a),this.tabpanel_content.width(this.width-a));this.heightResizable&&(this.height=this.render.height(),this.tabpanel.height(this.height-a),this.tabpanel_content.height(this.height-this.tabpanel_tab_content.get(0).offsetHeight));this.showScroll();this.useableScroll();this.update()},setRenderWH:function(a){a&&(void 0!=a.width&&this.render.width(a.width),void 0!=a.height&&this.render.height(a.height),
this.resize())}};TabPanel.i18n={closeTab:"\u5173\u95ed\u9875\u7b7e",refreshTab:"\u5237\u65b0\u9875\u7b7e",closeOther:"\u5173\u95ed\u5176\u4ed6",closeLeft:"\u5173\u95ed\u5de6\u4fa7",closeRight:"\u5173\u95ed\u53f3\u4fa7",detachTab:"\u65b0\u7a97\u53e3\u6253\u5f00"};
Fader=function(a){this.element=a.element;this.elementID=a.elementID;this.style=a.style;this.num=a.num;this.maxMove=a.maxMove;this.finishNum="string";this.interval=a.interval||10;this.step=a.step||20;this.onFinish=a.onFinish;this.isFinish=!1;this.timer=null;this.method=0<=this.num;this.c=this.elementID?$("#"+this.elementID):this.element;this.run=function(){clearInterval(this.timer);this.fade();if(this.isFinish)this.onFinish&&this.onFinish();else{var a=this;this.timer=setInterval(function(){a.run()},
this.interval)}};this.fade=function(){"string"==this.finishNum&&(this.finishNum=(parseInt(this.c.css(this.style))||0)+this.num);var a=parseInt(this.c.css(this.style))||0;this.finishNum>a&&this.method?(a+=this.step,0<=a&&(this.finishNum=a=0)):this.finishNum<a&&!this.method&&(a-=this.step,-1*a>=this.maxMove&&(this.finishNum=a=-1*this.maxMove));this.finishNum<=a&&this.method||this.finishNum>=a&&!this.method?(this.c.css(this.style,this.finishNum+"px"),this.isFinish=!0,this.finishNum="string"):this.c.css(this.style,
a+"px")}};Math.uuid=function(){var a="0123456789abcdefghijklmnopqrstuvwxyz".split("");return function(b,c){var d=[],f=Math.random;c=c||a.length;if(b)for(var e=0;e<b;e++)d[e]=a[0|f()*c];else for(d[8]=d[13]=d[18]=d[23]="-",d[14]="4",e=0;36>e;e++)d[e]||(b=0|16*f(),d[e]=a[19==e?b&3|8:b&15]);return d.join("").replace(/-/ig,"").substring(0,10)}}();
$.fn.tabPanel=function(a,b,c,d,f,e){var g,h=this.each(function(){var h=$(this),k=h.data("tabPanel"),l="object"===typeof a&&a;k||h.data("tabPanel",k=new TabPanel(l,h));"string"===typeof a&&"function"===typeof k[a]&&(g=b instanceof Array?k[a].apply(k,b,c,d,f,e):k[a](b,c,d,f,e))});return void 0===g?h:g};var pos_mx=0,pos_my=0;
$(function(){document.oncontextmenu=function(){return!1};document.onmousemove=function(a){var b,c;ev=a||window.event;ev.pageX||ev.pageY?(b=ev.pageX,c=ev.pageY):(b=ev.clientX,c=ev.clientY+$(document).scrollTop());pos_mx=b;pos_my=c}});
$.fn.RightMenu=function(a,b){b=$.extend({menuList:[]},b);var c=b.menuList.length;if(!$("#"+a)[0]){for(var d='<div id="'+a+'" class="div_RightMenu"><div><ul class=\'ico\'>',f=0;f<c;f++)d+='<li class="'+b.menuList[f].menuClass+'" onclick="'+b.menuList[f].clickEvent+'">'+b.menuList[f].menuName+"</li>";d+="</ul></div><div>";$("body").append(d);var e=$("#"+a),g;e.find("li").bind("mouseover",function(){$(this).addClass("RM_mouseover")}).bind("mouseout",function(){$(this).removeClass("RM_mouseover")}).bind("click",
function(){window.clearTimeout(g);e.hide()});e.hover(function(){window.clearTimeout(g)},function(){window.clearTimeout(g);g=window.setTimeout(function(){e.hide()},500)})}return this.each(function(){this.oncontextmenu=function(){$(".div_RightMenu").hide();var b=$("body").width(),c=$("html").height(),d=$("body").height(),e=$("#"+a).width(),f=$("#"+a).height();c=c>d?c:d;c<f+pos_my&&(pos_my=c-f);b<e+pos_mx&&(pos_mx=b-e);$("#"+a).hide().css({top:pos_my,left:pos_mx}).show()}})};
