/*
 ??Tab??????
 @author ThinkGem
 @version 2017-3-26
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var g=a[d];if(b.call(c,g,d,a))return{i:d,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
(function(a){window.tabPage={tabPageId:null,initTabPage:function(b,c){this.tabPageId=b;b=a.extend(!0,{autoResizable:!0,height:function(){return a(window).height()},items:[]},c);c=a("#"+this.tabPageId).tabPanel(b);c.sortable&&!1!==b.sortable&&c.find("ul.tabpanel_mover").sortable({handle:".title"});return c},addTabPage:function(b,c,e,d,g){var f=b?b.attr("data-tab-id"):null;void 0==f&&(f="tabpanel-"+Math.uuid());if(b){b.attr("data-tab-id",f);var k=b.attr("data-closeable");void 0==d&&k&&(d="true"==k);
b=b.attr("data-refresh");void 0==g&&b&&(g="true"==b)}/^(javascript:|vbscript:)/i.test(e)&&(e="");a("#"+this.tabPageId).tabPanel("addTab",{id:f,title:c,html:'<script>js.loading();\x3c/script><iframe id="'+f+'-frame" src="'+e+'" width="100%" height="100%" frameborder="0" onload="js.closeLoading();"></iframe>',closable:void 0==d?!0:d,refresh:void 0==g?!1:g,onPreClose:function(b){js.closeLoading(1E3,!0);try{var e=a("#"+f+"-frame");if(0<e.length){var d=e[0].contentWindow;if(d&&"function"==typeof d.onTabPageClose)return d.onTabPageClose(f,
c);if(d&&"function"==typeof d.onTablePageClose)return d.onTablePageClose(f,c)}}catch(h){js.error(h)}},onActiveTab:function(b){try{var d=a("#"+f+"-frame");if(0<d.length){var e=d[0].contentWindow;if(e&&"function"==typeof e.onTabPageActive)return e.onTabPageActive(f,c)}}catch(h){js.error(h)}}});return f},getCurrentTabPage:function(b){var c=a("#"+this.tabPageId).tabPanel("getActiveTab");c=a("#"+c.id+"-frame");if(0<c.length&&"function"==typeof b)try{b(c[0].contentWindow)}catch(e){js.error(e)}return c},
getPrevTabPage:function(b,c){var e=a("#"+this.tabPageId).tabPanel("getActiveTab"),d=a("#"+e.preTabId+"-frame");if(0<d.length&&"function"==typeof b)try{b(d[0].contentWindow)}catch(g){js.error(g)}1==c&&a("#"+this.tabPageId).tabPanel("kill",e.id);return d},closeCurrentTabPage:function(a){return this.getPrevTabPage(a,!0)}}})(window.jQuery);
