var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");
(function(a){a.validator.messages.errorMessage&&""!=a.validator.messages.errorMessage&&a("#inputForm .box-footer [class*=col-sm-offset]").append('<div class="form-error">'+a.validator.messages.errorMessage+"</div>");a.extend(a.validator.defaults,{ignore:":hidden:not(.required),input.select2-focusser",errorClass:"has-error",errorContainer:".form-error",errorPlacement:function(a,b){if(0<b.closest(".icheck").length){b=b.closest(".icheck");b.parent().css("position","relative");a.insertAfter(b);var d=
b.position1x();a.css({top:d.top+b.outerHeight()+2,left:d.left+5})}else b.next().hasClass("select2")?(b=b.next(),b.parent().css("position","relative")):0<b.closest(".input-group").length&&(b=b.closest(".input-group"),b.parent().css("position","relative")),a.insertAfter(b),d=b.position1x(),a.css({top:d.top+b.outerHeight()-5,left:d.left+5})},highlight:function(c){a(c).closest(".form-group").addClass("has-error")},unhighlight:function(c){a(c).closest(".form-group").removeClass("has-error")},success:function(a){a.remove()}});
a.extend(a.fn,{resetValid:function(){var c=a(this);var b=0<c.closest(".icheck").length?c.closest(".icheck").parent():0<c.closest(".input-group").size()?c.closest(".input-group").parent():c.parent();c.closest(".has-error").removeClass("has-error");b.find("label.has-error").remove()}})})(jQuery);jQuery.validator.addMethod("userName",function(a,c){return this.optional(c)||/^[\u0391-\uFFE5\w]+$/.test(a)},$.validator.messages.userName);
jQuery.validator.addMethod("realName",function(a,c){return this.optional(c)||/^[\u4e00-\u9fa5]{2,30}$/.test(a)},$.validator.messages.realName);jQuery.validator.addMethod("abc",function(a,c){return this.optional(c)||/^[a-zA-Z0-9_]*$/.test(a)},$.validator.messages.abc);jQuery.validator.addMethod("noEqualTo",function(a,c,b){return a!=$(b).val()},$.validator.messages.noEqualTo);jQuery.validator.addMethod("mobile",function(a,c){var b=/^1[3,4,5,6,7,8,9]\d{9}$/g;return this.optional(c)||b.test(a)},$.validator.messages.mobile);
jQuery.validator.addMethod("phone",function(a,c){var b=/(^0[1-9]{1}\d{8,10}$)|(^1[3,4,5,6,7,8,9]\d{9}$)/g;return this.optional(c)||b.test(a)},$.validator.messages.phone);jQuery.validator.addMethod("simplePhone",function(a,c){var b=/^(\d{3,4}-?)?\d{7,9}$/g;return this.optional(c)||b.test(a)},$.validator.messages.simplePhone);jQuery.validator.addMethod("zipCode",function(a,c){var b=/^[0-9]{6}$/;return this.optional(c)||b.test(a)},$.validator.messages.zipCode);
$.validator.addMethod("integer",function(a,c){return this.optional(c)||/^-?\d+$/.test(a)},$.validator.messages.integer);$.validator.addMethod("ipv4",function(a,c){return this.optional(c)||/^(25[0-5]|2[0-4]\d|[01]?\d\d?)\.(25[0-5]|2[0-4]\d|[01]?\d\d?)\.(25[0-5]|2[0-4]\d|[01]?\d\d?)\.(25[0-5]|2[0-4]\d|[01]?\d\d?)$/i.test(a)},$.validator.messages.ipv4);
$.validator.addMethod("ipv6",function(a,c){return this.optional(c)||/^((([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|(([0-9A-Fa-f]{1,4}:){0,5}:((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|(::([0-9A-Fa-f]{1,4}:){0,5}((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:))$/i.test(a)},$.validator.messages.ipv6);
jQuery.validator.addMethod("qq",function(a,c){var b=/^[1-9][0-9]{4,}$/;return this.optional(c)||b.test(a)},$.validator.messages.qq);jQuery.validator.addMethod("isBlank",function(a,c){var b=/^[ |\u3000]*$/;return this.optional(c)||!b.test(a)},$.validator.messages.isBlank);
jQuery.validator.addMethod("idcard",function(a,c){var b={provinceAndCitys:{11:"\u5317\u4eac",12:"\u5929\u6d25",13:"\u6cb3\u5317",14:"\u5c71\u897f",15:"\u5185\u8499\u53e4",21:"\u8fbd\u5b81",22:"\u5409\u6797",23:"\u9ed1\u9f99\u6c5f",31:"\u4e0a\u6d77",32:"\u6c5f\u82cf",33:"\u6d59\u6c5f",34:"\u5b89\u5fbd",35:"\u798f\u5efa",36:"\u6c5f\u897f",37:"\u5c71\u4e1c",41:"\u6cb3\u5357",42:"\u6e56\u5317",43:"\u6e56\u5357",44:"\u5e7f\u4e1c",45:"\u5e7f\u897f",46:"\u6d77\u5357",50:"\u91cd\u5e86",51:"\u56db\u5ddd",
52:"\u8d35\u5dde",53:"\u4e91\u5357",54:"\u897f\u85cf",61:"\u9655\u897f",62:"\u7518\u8083",63:"\u9752\u6d77",64:"\u5b81\u590f",65:"\u65b0\u7586",71:"\u53f0\u6e7e",81:"\u9999\u6e2f",82:"\u6fb3\u95e8",91:"\u56fd\u5916"},powers:"7 9 10 5 8 4 2 1 6 3 7 9 10 5 8 4 2".split(" "),parityBit:"10X98765432".split(""),genders:{male:"\u7537",female:"\u5973"},checkAddressCode:function(d){return/^[1-9]\d{5}$/.test(d)?b.provinceAndCitys[parseInt(d.substring(0,2))]?!0:!1:!1},checkBirthDayCode:function(d){if(!/^[1-9]\d{3}((0[1-9])|(1[0-2]))((0[1-9])|([1-2][0-9])|(3[0-1]))$/.test(d))return!1;
var a=parseInt(d.substring(0,4),10),b=parseInt(d.substring(4,6),10);d=parseInt(d.substring(6),10);var c=new Date(a,b-1,d);return c>new Date?!1:c.getFullYear()==a&&c.getMonth()==b-1&&c.getDate()==d?!0:!1},getParityBit:function(a){a=a.substring(0,17);for(var d=0,c=0;17>c;c++)d+=parseInt(a.charAt(c),10)*parseInt(b.powers[c]);return b.parityBit[d%11]},checkParityBit:function(a){var d=a.charAt(17).toUpperCase();return b.getParityBit(a)==d?!0:!1},checkIdCardNo:function(a){return/^\d{15}|(\d{17}(\d|x|X))$/.test(a)?
15==a.length?b.check15IdCardNo(a):18==a.length?b.check18IdCardNo(a):!1:!1},check15IdCardNo:function(a){var d=/^[1-9]\d{7}((0[1-9])|(1[0-2]))((0[1-9])|([1-2][0-9])|(3[0-1]))\d{3}$/.test(a);if(!d)return!1;d=a.substring(0,6);d=b.checkAddressCode(d);if(!d)return!1;a="19"+a.substring(6,12);return b.checkBirthDayCode(a)},check18IdCardNo:function(a){var d=/^[1-9]\d{5}[1-9]\d{3}((0[1-9])|(1[0-2]))((0[1-9])|([1-2][0-9])|(3[0-1]))\d{3}(\d|x|X)$/.test(a);if(!d)return!1;d=a.substring(0,6);d=b.checkAddressCode(d);
if(!d)return!1;d=a.substring(6,14);return(d=b.checkBirthDayCode(d))?b.checkParityBit(a):!1},formateDateCN:function(a){var b=a.substring(0,4),d=a.substring(4,6);a=a.substring(6);return b+"-"+d+"-"+a},getIdCardInfo:function(a){var d={gender:"",birthday:""};if(15==a.length){var c="19"+a.substring(6,12);d.birthday=b.formateDateCN(c);0==parseInt(a.charAt(14))%2?d.gender=b.genders.female:d.gender=b.genders.male}else 18==a.length&&(c=a.substring(6,14),d.birthday=b.formateDateCN(c),0==parseInt(a.charAt(16))%
2?d.gender=b.genders.female:d.gender=b.genders.male);return d},getId15:function(a){return 15==a.length?a:18==a.length?a.substring(0,6)+a.substring(8,17):null},getId18:function(a){if(15==a.length){a=a.substring(0,6)+"19"+a.substring(6);var c=b.getParityBit(a);return a+c}return 18==a.length?a:null}};return this.optional(c)||b.checkIdCardNo(a)},$.validator.messages.idcard);
