var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,k){a instanceof String&&(a=String(a));for(var c=a.length,l=0;l<c;l++){var r=a[l];if(b.call(k,r,l,a))return{i:l,v:r}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,k){a!=Array.prototype&&a!=Object.prototype&&(a[b]=k.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var k=a[b];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,k,c){if(b){k=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var l=a[c];l in k||(k[l]={});k=k[l]}a=a[a.length-1];c=k[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(k,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,k){return $jscomp.findInternal(this,a,k).v}},"es6","es3");
(function(a){a.jgrid.extend({searchGrid:function(b){b=a.extend({recreateFilter:!1,drag:!0,sField:"searchField",sValue:"searchString",sOper:"searchOper",sFilter:"filters",loadDefaults:!0,beforeShowSearch:null,afterShowSearch:null,onInitializeSearch:null,closeAfterSearch:!1,closeAfterReset:!1,closeOnEscape:!1,multipleSearch:!1,cloneSearchRowOnAdd:!0,sopt:null,stringResult:void 0,onClose:null,useDataProxy:!1,overlay:!0},a.jgrid.search,b||{});return this.each(function(){function k(b,c){c=b.p.postData[c.sFilter];
"string"==typeof c&&(c=a.jgrid.parse(c));if(c&&(c.groupOp&&b.SearchFilter.setGroupOp(c.groupOp),c.rules))for(var g,d=0,n=c.rules.length;d<n;d++)g=c.rules[d],void 0!==g.field&&void 0!==g.op&&void 0!==g.data&&(g=b.SearchFilter.setFilter({sfref:b.SearchFilter.$.find(".sf:last"),filter:a.extend({},g)}))&&b.SearchFilter.add()}function c(c){if(b.onClose){var g=b.onClose(c);if("boolean"==typeof g&&!g)return}c.hide();!0===b.overlay&&a(".jqgrid-overlay:first","#gbox_"+f.p.id).hide()}function l(){var c=a(".ui-searchFilter").length;
if(1<c){var d=a("#"+e).css("zIndex");a("#"+e).css({zIndex:parseInt(d,10)+c})}a("#"+e).show();!0===b.overlay&&a(".jqgrid-overlay:first","#gbox_"+f.p.id).show();try{a(":input:visible","#"+e)[0].focus()}catch(x){}}function r(g){var d=void 0!==g,n=a("#"+f.p.id),h={};!1===b.multipleSearch?(h[b.sField]=g.rules[0].field,h[b.sValue]=g.rules[0].data,h[b.sOper]=g.rules[0].op,h.hasOwnProperty(b.sFilter)&&delete h[b.sFilter]):(h[b.sFilter]=g,a.each([b.sField,b.sValue,b.sOper],function(a,b){h.hasOwnProperty(b)&&
delete h[b]}));n[0].p.search=d;a.extend(n[0].p.postData,h);n.trigger("reloadGrid",[{page:1}]);b.closeAfterSearch&&c(a("#"+e))}function p(g){g=g&&g.hasOwnProperty("reload")?g.reload:!0;var d=a("#"+f.p.id),h={};d[0].p.search=!1;!1===b.multipleSearch?h[b.sField]=h[b.sValue]=h[b.sOper]="":h[b.sFilter]="";a.extend(d[0].p.postData,h);g&&d.trigger("reloadGrid",[{page:1}]);b.closeAfterReset&&c(a("#"+e))}var f=this;if(f.grid){var e="fbox_"+f.p.id,m=!0;if(a.fn.searchFilter)if(!0===b.recreateFilter&&a("#"+e).remove(),
null!=a("#"+e).html())a.isFunction(b.beforeShowSearch)&&(m=b.beforeShowSearch(a("#"+e)),"undefined"==typeof m&&(m=!0)),!1!==m&&(l(),a.isFunction(b.afterShowSearch)&&b.afterShowSearch(a("#"+e)));else{var q=[],u=a("#"+f.p.id).jqGrid("getGridParam","colNames"),n=a("#"+f.p.id).jqGrid("getGridParam","colModel"),h="eq ne lt le gt ge bw bn in ni ew en cn nc".split(" "),d,v,t,w=[];if(null!==b.sopt)for(d=t=0;d<b.sopt.length;d++)-1!=(v=a.inArray(b.sopt[d],h))&&(w[t]={op:b.sopt[d],text:b.odata[v].text},t++);
else for(d=0;d<h.length;d++)w[d]={op:h[d],text:b.odata[d].text};a.each(n,function(c,n){var g="undefined"===typeof n.search?!0:n.search,e=!0===n.hidden;c=a.extend({},{text:u[c],itemval:n.index||n.name},this.searchoptions);n=!0===c.searchhidden;if("undefined"!==typeof c.sopt&&(t=0,c.ops=[],0<c.sopt.length))for(d=0;d<c.sopt.length;d++)-1!=(v=a.inArray(c.sopt[d],h))&&(c.ops[t]={op:c.sopt[d],text:b.odata[v].text},t++);"undefined"===typeof this.stype&&(this.stype="text");if("select"==this.stype&&void 0===
c.dataUrl){if(c.value)var f=c.value;else this.editoptions&&(f=this.editoptions.value);if(f)if(c.dataValues=[],"string"===typeof f)for(f=f.split(";"),d=0;d<f.length;d++){var k=f[d].split(":");c.dataValues[d]={value:k[0],text:k[1]}}else if("object"===typeof f)for(k in d=0,f)f.hasOwnProperty(k)&&(c.dataValues[d]={value:k,text:f[k]},d++)}(n&&g||g&&!e)&&q.push(c)});if(0<q.length){a("<div id='"+e+"' role='dialog' tabindex='-1'></div>").insertBefore("#gview_"+f.p.id);void 0===b.stringResult&&(b.stringResult=
b.multipleSearch);f.SearchFilter=a("#"+e).searchFilter(q,{groupOps:b.groupOps,operators:w,onClose:c,resetText:b.Reset,searchText:b.Find,windowTitle:b.caption,rulesText:b.rulesText,matchText:b.matchText,onSearch:r,onReset:p,stringResult:b.stringResult,ajaxSelectOptions:a.extend({},a.jgrid.ajaxOptions,f.p.ajaxSelectOptions||{}),clone:b.cloneSearchRowOnAdd});a(".ui-widget-overlay","#"+e).remove();"rtl"==f.p.direction&&a(".ui-closer","#"+e).css("float","left");if(!0===b.drag)if(a("#"+e+" table thead tr:first td:first").css("cursor",
"move"),jQuery.fn.jqDrag)a("#"+e).jqDrag(a("#"+e+" table thead tr:first td:first"));else try{a("#"+e).draggable({handle:a("#"+e+" table thead tr:first td:first")})}catch(g){}!1===b.multipleSearch&&(a(".ui-del, .ui-add, .ui-del, .ui-add-last, .matchText, .rulesText","#"+e).hide(),a("select[name='groupOp']","#"+e).hide());!0===b.multipleSearch&&!0===b.loadDefaults&&k(f,b);if(a.isFunction(b.onInitializeSearch))b.onInitializeSearch(a("#"+e));a.isFunction(b.beforeShowSearch)&&(m=b.beforeShowSearch(a("#"+
e)),"undefined"==typeof m&&(m=!0));!1!==m&&(l(),a.isFunction(b.afterShowSearch)&&b.afterShowSearch(a("#"+e)),!0===b.closeOnEscape&&a("#"+e).keydown(function(b){27==b.which&&c(a("#"+e));13==b.which&&a(".ui-search",this).click()}))}}}})},updateGridRows:function(b,k,c){var l,r=!1,p;this.each(function(){var f=this,e,m,q,u;if(!f.grid)return!1;k||(k="id");b&&0<b.length&&a(b).each(function(b){q=this;if(m=f.rows.namedItem(q[k])){u=q[k];if(!0===c&&!0===f.p.jsonReader.repeatitems){f.p.jsonReader.cell&&(q=q[f.p.jsonReader.cell]);
for(b=0;b<q.length;b++)e=f.formatter(u,q[b],b,q,"edit"),p=f.p.colModel[b].title?{title:a.jgrid.stripHtml(e)}:{},!0===f.p.treeGrid&&l==f.p.ExpandColumn?a("td:eq("+b+") > span:first",m).html(e).attr(p):a("td:eq("+b+")",m).html(e).attr(p);return r=!0}a(f.p.colModel).each(function(b){l=!0===c?this.jsonmap||this.name:this.name;void 0!==q[l]&&(e=f.formatter(u,q[l],b,q,"edit"),p=this.title?{title:a.jgrid.stripHtml(e)}:{},!0===f.p.treeGrid&&l==f.p.ExpandColumn?a("td:eq("+b+") > span:first",m).html(e).attr(p):
a("td:eq("+b+")",m).html(e).attr(p),r=!0)})}})});return r},filterGrid:function(b,k){k=a.extend({gridModel:!1,gridNames:!1,gridToolbar:!1,filterModel:[],formtype:"horizontal",autosearch:!0,formclass:"filterform",tableclass:"filtertable",buttonclass:"filterbutton",searchButton:"Search",clearButton:"Clear",enableSearch:!1,enableClear:!1,beforeSearch:null,afterSearch:null,beforeClear:null,afterClear:null,url:"",marksearched:!0},k||{});return this.each(function(){var c=this;this.p=k;if(0===this.p.filterModel.length&&
!1===this.p.gridModel)alert("No filter is set");else if(b){this.p.gridid=-1!=b.indexOf("#")?b:"#"+b;var l=a(this.p.gridid).jqGrid("getGridParam","colModel");if(l){if(!0===this.p.gridModel){var r=a(this.p.gridid)[0],p;a.each(l,function(a,b){b=[];this.search=!1===this.search?!1:!0;p=this.editrules&&!0===this.editrules.searchhidden?!0:!0===this.hidden?!1:!0;!0===this.search&&!0===p&&(b.label=!0===c.p.gridNames?r.p.colNames[a]:"",b.name=this.name,b.index=this.index||this.name,b.stype=this.edittype||"text",
"select"!=b.stype&&(b.stype="text"),b.defval=this.defval||"",b.surl=this.surl||"",b.sopt=this.editoptions||{},b.width=this.width,c.p.filterModel.push(b))})}else a.each(c.p.filterModel,function(a,b){for(a=0;a<l.length;a++)if(this.name==l[a].name){this.index=l[a].index||this.name;break}this.index||(this.index=this.name)});var f=function(){var b={},f=0,h,d=a(c.p.gridid)[0],e;d.p.searchdata={};a.isFunction(c.p.beforeSearch)&&c.p.beforeSearch();a.each(c.p.filterModel,function(g,k){e=this.index;if("select"===
this.stype)if(h=a("select[name="+e+"]",c).val())b[e]=h,c.p.marksearched&&a("#jqgh_"+this.name,d.grid.hDiv).addClass("dirty-cell"),f++;else{c.p.marksearched&&a("#jqgh_"+this.name,d.grid.hDiv).removeClass("dirty-cell");try{delete d.p.postData[this.index]}catch(x){}}else if(h=a("input[name="+e+"]",c).val())b[e]=h,c.p.marksearched&&a("#jqgh_"+this.name,d.grid.hDiv).addClass("dirty-cell"),f++;else{c.p.marksearched&&a("#jqgh_"+this.name,d.grid.hDiv).removeClass("dirty-cell");try{delete d.p.postData[this.index]}catch(x){}}});
var k=0<f?!0:!1;a.extend(d.p.postData,b);if(c.p.url){var l=a(d).jqGrid("getGridParam","url");a(d).jqGrid("setGridParam",{url:c.p.url})}a(d).jqGrid("setGridParam",{search:k}).trigger("reloadGrid",[{page:1}]);l&&a(d).jqGrid("setGridParam",{url:l});a.isFunction(c.p.afterSearch)&&c.p.afterSearch()},e=function(){var b={},f,h=0,d=a(c.p.gridid)[0],e;a.isFunction(c.p.beforeClear)&&c.p.beforeClear();a.each(c.p.filterModel,function(g,k){e=this.index;f=this.defval?this.defval:"";this.stype||(this.stype="text");
switch(this.stype){case "select":var l;a("select[name="+e+"] option",c).each(function(b){0===b&&(this.selected=!0);if(a(this).text()==f)return this.selected=!0,l=a(this).val(),!1});if(l)b[e]=l,c.p.marksearched&&a("#jqgh_"+this.name,d.grid.hDiv).addClass("dirty-cell"),h++;else{c.p.marksearched&&a("#jqgh_"+this.name,d.grid.hDiv).removeClass("dirty-cell");try{delete d.p.postData[this.index]}catch(y){}}break;case "text":if(a("input[name="+e+"]",c).val(f),f)b[e]=f,c.p.marksearched&&a("#jqgh_"+this.name,
d.grid.hDiv).addClass("dirty-cell"),h++;else{c.p.marksearched&&a("#jqgh_"+this.name,d.grid.hDiv).removeClass("dirty-cell");try{delete d.p.postData[this.index]}catch(y){}}}});var k=0<h?!0:!1;a.extend(d.p.postData,b);if(c.p.url){var l=a(d).jqGrid("getGridParam","url");a(d).jqGrid("setGridParam",{url:c.p.url})}a(d).jqGrid("setGridParam",{search:k}).trigger("reloadGrid",[{page:1}]);l&&a(d).jqGrid("setGridParam",{url:l});a.isFunction(c.p.afterClear)&&c.p.afterClear()},m=a("<form name='SearchForm' style=display:inline;' class='"+
this.p.formclass+"'></form>");var q=a("<table class='"+this.p.tableclass+"' cellspacing='0' cellpadding='0' border='0'><tbody></tbody></table>");a(m).append(q);(function(){var b=document.createElement("tr"),k;"horizontal"==c.p.formtype&&a(q).append(b);a.each(c.p.filterModel,function(d,e){k=document.createElement("td");a(k).append("<label for='"+this.name+"'>"+this.label+"</label>");h=document.createElement("td");var g=this;this.stype||(this.stype="text");switch(this.stype){case "select":if(this.surl)a(h).load(this.surl,
function(){g.defval&&a("select",this).val(g.defval);a("select",this).attr({name:g.index||g.name,id:"sg_"+g.name});g.sopt&&a("select",this).attr(g.sopt);!0===c.p.gridToolbar&&g.width&&a("select",this).width(g.width);!0===c.p.autosearch&&a("select",this).change(function(a){f();return!1})});else if(g.sopt.value){var m=g.sopt.value;e=document.createElement("select");a(e).attr({name:g.index||g.name,id:"sg_"+g.name}).attr(g.sopt);if("string"===typeof m)for(d=m.split(";"),m=0;m<d.length;m++){var n=d[m].split(":");
var p=document.createElement("option");p.value=n[0];p.innerHTML=n[1];n[1]==g.defval&&(p.selected="selected");e.appendChild(p)}else if("object"===typeof m)for(n in m)m.hasOwnProperty(n)&&(d++,p=document.createElement("option"),p.value=n,p.innerHTML=m[n],m[n]==g.defval&&(p.selected="selected"),e.appendChild(p));!0===c.p.gridToolbar&&g.width&&a(e).width(g.width);a(h).append(e);!0===c.p.autosearch&&a(e).change(function(a){f();return!1})}break;case "text":e=this.defval?this.defval:"",a(h).append("<input type='text' name='"+
(this.index||this.name)+"' id='sg_"+this.name+"' value='"+e+"'/>"),g.sopt&&a("input",h).attr(g.sopt),!0===c.p.gridToolbar&&g.width&&(a.browser.msie?a("input",h).width(g.width-4):a("input",h).width(g.width-2)),!0===c.p.autosearch&&a("input",h).keypress(function(a){return 13==(a.charCode?a.charCode:a.keyCode?a.keyCode:0)?(f(),!1):this})}"horizontal"==c.p.formtype?(!0===c.p.gridToolbar&&!1===c.p.gridNames?a(b).append(h):a(b).append(k).append(h),a(b).append(h)):(l=document.createElement("tr"),a(l).append(k).append(h),
a(q).append(l))});var h=document.createElement("td");if(!0===c.p.enableSearch){var d="<input type='button' id='sButton' class='"+c.p.buttonclass+"' value='"+c.p.searchButton+"'/>";a(h).append(d);a("input#sButton",h).click(function(){f();return!1})}!0===c.p.enableClear&&(d="<input type='button' id='cButton' class='"+c.p.buttonclass+"' value='"+c.p.clearButton+"'/>",a(h).append(d),a("input#cButton",h).click(function(){e();return!1}));if(!0===c.p.enableClear||!0===c.p.enableSearch)if("horizontal"==c.p.formtype)a(b).append(h);
else{var l=document.createElement("tr");a(l).append("<td>&#160;</td>").append(h);a(q).append(l)}})();a(this).append(m);this.triggerSearch=f;this.clearSearch=e}else alert("Could not get grid colModel")}else alert("No target grid is set!")})}})})(jQuery);
