/*
 Cropper v3.1.3
 https://github.com/fengyuanchen/cropper

 Copyright (c) 2014-2017 Chen Fengyuan
 Released under the MIT license

 Date: 2017-10-21T10:04:29.734Z
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,p,k){c!=Array.prototype&&c!=Object.prototype&&(c[p]=k.value)};
$jscomp.getGlobal=function(c){c=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,c];for(var p=0;p<c.length;++p){var k=c[p];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,p,k,r){if(p){k=$jscomp.global;c=c.split(".");for(r=0;r<c.length-1;r++){var t=c[r];t in k||(k[t]={});k=k[t]}c=c[c.length-1];r=k[c];p=p(r);p!=r&&null!=p&&$jscomp.defineProperty(k,c,{configurable:!0,writable:!0,value:p})}};
$jscomp.polyfill("Array.from",function(c){return c?c:function(c,k,r){k=null!=k?k:function(c){return c};var p=[],w="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];if("function"==typeof w){c=w.call(c);for(var A=0;!(w=c.next()).done;)p.push(k.call(r,w.value,A++))}else for(w=c.length,A=0;A<w;A++)p.push(k.call(r,c[A],A));return p}},"es6","es3");$jscomp.polyfill("Number.isNaN",function(c){return c?c:function(c){return"number"===typeof c&&isNaN(c)}},"es6","es3");
$jscomp.arrayIteratorImpl=function(c){var p=0;return function(){return p<c.length?{done:!1,value:c[p++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(c,p){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:p})};
$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function c(k){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(k||"")+"_"+p++,k)}var p=0;return c}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.asyncIterator;c||(c=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};
$jscomp.iteratorFromArray=function(c,p){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var k=0,r={next:function(){if(k<c.length){var t=k++;return{value:p(t,c[t]),done:!1}}r.next=function(){return{done:!0,value:void 0}};return r.next()}};r[Symbol.iterator]=function(){return r};return r};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");
$jscomp.polyfill("Number.isFinite",function(c){return c?c:function(c){return"number"!==typeof c?!1:!isNaN(c)&&Infinity!==c&&-Infinity!==c}},"es6","es3");$jscomp.findInternal=function(c,p,k){c instanceof String&&(c=String(c));for(var r=c.length,t=0;t<r;t++){var w=c[t];if(p.call(k,w,t,c))return{i:t,v:w}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,k){return $jscomp.findInternal(this,c,k).v}},"es6","es3");
(function(c,p){"object"===typeof exports&&"undefined"!==typeof module?p(require("jquery")):"function"===typeof define&&define.amd?define(["jquery"],p):p(c.jQuery)})(this,function(c){function p(a){if(Array.isArray(a)){for(var d=0,b=Array(a.length);d<a.length;d++)b[d]=a[d];return b}return Array.from(a)}function k(a){return"number"===typeof a&&!R(a)}function r(a){return"undefined"===typeof a}function t(a,d){for(var b=arguments.length,e=Array(2<b?b-2:0),f=2;f<b;f++)e[f-2]=arguments[f];return function(){for(var b=
arguments.length,f=Array(b),c=0;c<b;c++)f[c]=arguments[c];return a.apply(d,e.concat(f))}}function w(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1E11;return S.test(a)?Math.round(a*d)/d:a}function A(a){return(a=a.match(T))&&(a[1]!==K.protocol||a[2]!==K.hostname||a[3]!==K.port)}function D(a){var d="timestamp="+(new Date).getTime();return a+(-1===a.indexOf("?")?"?":"&")+d}function B(a){var d=a.rotate,b=a.scaleX,e=a.scaleY,f=a.translateX;a=a.translateY;var c=[];k(f)&&0!==f&&c.push("translateX("+
f+"px)");k(a)&&0!==a&&c.push("translateY("+a+"px)");k(d)&&0!==d&&c.push("rotate("+d+"deg)");k(b)&&1!==b&&c.push("scaleX("+b+")");k(e)&&1!==e&&c.push("scaleY("+e+")");return c.length?c.join(" "):"none"}function F(a,d){if(a.naturalWidth&&!U)d(a.naturalWidth,a.naturalHeight);else{var b=document.createElement("img");b.onload=function(){d(b.width,b.height)};b.src=a.src}}function V(a){var d=c.extend({},a),b=[];c.each(a,function(a,f){delete d[a];c.each(d,function(a,d){var e=Math.abs(f.startX-d.startX),c=
Math.abs(f.startY-d.startY);a=Math.abs(f.endX-d.endX);d=Math.abs(f.endY-d.endY);e=Math.sqrt(e*e+c*c);b.push((Math.sqrt(a*a+d*d)-e)/e)})});b.sort(function(b,a){return Math.abs(b)<Math.abs(a)});return b[0]}function G(a,d){var b=a.pageX;a=a.pageY;var e={endX:b,endY:a};return d?e:c.extend({startX:b,startY:a},e)}function W(a){var d=0,b=0,e=0;c.each(a,function(a,c){a=c.startY;d+=c.startX;b+=a;e+=1});d/=e;b/=e;return{pageX:d,pageY:b}}function E(a){var d=a.aspectRatio,b=a.height;a=a.width;var e=function(a){return X(a)&&
0<a};e(a)&&e(b)?b*d>a?b=a/d:a=b*d:e(a)?b=a/d:e(b)&&(a=b*d);return{width:a,height:b}}function Y(a,d,b,e){var f=d.naturalWidth,g=d.naturalHeight,l=d.rotate;l=void 0===l?0:l;var h=d.scaleX;h=void 0===h?1:h;d=d.scaleY;d=void 0===d?1:d;var n=b.aspectRatio,m=b.naturalWidth,q=b.naturalHeight;b=e.fillColor;b=void 0===b?"transparent":b;var k=e.imageSmoothingEnabled;k=void 0===k?!0:k;var r=e.imageSmoothingQuality;r=void 0===r?"low":r;var t=e.maxWidth,L=e.maxHeight,x=e.minWidth;x=void 0===x?0:x;e=e.minHeight;
e=void 0===e?0:e;t=E({aspectRatio:n,width:void 0===t?Infinity:t,height:void 0===L?Infinity:L});n=E({aspectRatio:n,width:x,height:e});e=Math.min(t.width,Math.max(n.width,m));m=Math.min(t.height,Math.max(n.height,q));q=document.createElement("canvas");n=q.getContext("2d");f=[-f/2,-g/2,f,g];q.width=w(e);q.height=w(m);n.fillStyle=b;n.fillRect(0,0,e,m);n.save();n.translate(e/2,m/2);n.rotate(l*Math.PI/180);n.scale(h,d);n.imageSmoothingEnabled=!!k;n.imageSmoothingQuality=r;n.drawImage.apply(n,[a].concat(p(c.map(f,
function(a){return Math.floor(w(a))}))));n.restore();return q}function Z(a){a=a.replace(aa,"");var d=atob(a);a=new ArrayBuffer(d.length);var b=new Uint8Array(a);c.each(b,function(a){b[a]=d.charCodeAt(a)});return a}function ba(a,d){a=new Uint8Array(a);var b="";c.each(a,function(a,d){b+=M(d)});return"data:"+d+";base64,"+btoa(b)}function ca(a){if(Array.isArray(a)){for(var d=0,b=Array(a.length);d<a.length;d++)b[d]=a[d];return b}return Array.from(a)}c=c&&c.hasOwnProperty("default")?c["default"]:c;var C=
"undefined"!==typeof window?window:{},N=C.PointerEvent?"pointerdown":"touchstart mousedown",O=C.PointerEvent?"pointermove":"touchmove mousemove",P=C.PointerEvent?" pointerup pointercancel":"touchend touchcancel mouseup",da=/^(e|w|s|n|se|sw|ne|nw|all|crop|move|zoom)$/,ea=/^data:/,fa=/^data:image\/jpeg;base64,/,ha=/^(img|canvas)$/i,Q={viewMode:0,dragMode:"crop",aspectRatio:NaN,data:null,preview:"",responsive:!0,restore:!0,checkCrossOrigin:!0,checkOrientation:!0,modal:!0,guides:!0,center:!0,highlight:!0,
background:!0,autoCrop:!0,autoCropArea:.8,movable:!0,rotatable:!0,scalable:!0,zoomable:!0,zoomOnTouch:!0,zoomOnWheel:!0,wheelZoomRatio:.1,cropBoxMovable:!0,cropBoxResizable:!0,toggleDragModeOnDblclick:!0,minCanvasWidth:0,minCanvasHeight:0,minCropBoxWidth:0,minCropBoxHeight:0,minContainerWidth:200,minContainerHeight:100,ready:null,cropstart:null,cropmove:null,cropend:null,crop:null,zoom:null},R=Number.isNaN||C.isNaN,H=Object.keys||function(a){var d=[];c.each(a,function(a){d.push(a)});return d},S=/\.\d*(?:0|9){12}\d*$/i,
K=C.location,T=/^(https?:)\/\/([^:/?#]+):?(\d*)/i,I=C.navigator,U=I&&/(Macintosh|iPhone|iPod|iPad).*AppleWebKit/i.test(I.userAgent),X=Number.isFinite||C.isFinite,M=String.fromCharCode,aa=/^data:.*,/;C={render:function(){this.initContainer();this.initCanvas();this.initCropBox();this.renderCanvas();this.cropped&&this.renderCropBox()},initContainer:function(){var a=this.$element,d=this.options,b=this.$container,e=this.$cropper;e.addClass("cropper-hidden");a.removeClass("cropper-hidden");e.css(this.container=
{width:Math.max(b.width(),Number(d.minContainerWidth)||200),height:Math.max(b.height(),Number(d.minContainerHeight)||100)});a.addClass("cropper-hidden");e.removeClass("cropper-hidden")},initCanvas:function(){var a=this.container,d=this.image,b=this.options.viewMode,e=90===Math.abs(d.rotate)%180,f=e?d.naturalHeight:d.naturalWidth,g=e?d.naturalWidth:d.naturalHeight,l=f/g;e=a.width;var h=a.height;a.height*l>a.width?3===b?e=a.height*l:h=a.width/l:3===b?h=a.width/l:e=a.height*l;f={aspectRatio:l,naturalWidth:f,
naturalHeight:g,width:e,height:h};f.left=(a.width-e)/2;f.top=(a.height-h)/2;f.oldLeft=f.left;f.oldTop=f.top;this.canvas=f;this.limited=1===b||2===b;this.limitCanvas(!0,!0);this.initialImage=c.extend({},d);this.initialCanvas=c.extend({},f)},limitCanvas:function(a,d){var b=this.options,e=this.container,f=this.canvas,c=this.cropBox,l=b.viewMode,h=f.aspectRatio,n=this.cropped&&c;a&&(a=Number(b.minCanvasWidth)||0,b=Number(b.minCanvasHeight)||0,0<l&&(1<l?(a=Math.max(a,e.width),b=Math.max(b,e.height),3===
l&&(b*h>a?a=b*h:b=a/h)):a?a=Math.max(a,n?c.width:0):b?b=Math.max(b,n?c.height:0):n&&(a=c.width,b=c.height,b*h>a?a=b*h:b=a/h)),h=E({aspectRatio:h,width:a,height:b}),a=h.width,b=h.height,f.minWidth=a,f.minHeight=b,f.maxWidth=Infinity,f.maxHeight=Infinity);d&&(0<l?(d=e.width-f.width,h=e.height-f.height,f.minLeft=Math.min(0,d),f.minTop=Math.min(0,h),f.maxLeft=Math.max(0,d),f.maxTop=Math.max(0,h),n&&this.limited&&(f.minLeft=Math.min(c.left,c.left+c.width-f.width),f.minTop=Math.min(c.top,c.top+c.height-
f.height),f.maxLeft=c.left,f.maxTop=c.top,2===l&&(f.width>=e.width&&(f.minLeft=Math.min(0,d),f.maxLeft=Math.max(0,d)),f.height>=e.height&&(f.minTop=Math.min(0,h),f.maxTop=Math.max(0,h))))):(f.minLeft=-f.width,f.minTop=-f.height,f.maxLeft=e.width,f.maxTop=e.height))},renderCanvas:function(a,d){var b=this.canvas;var e=this.image;if(d){d=e.naturalWidth*Math.abs(e.scaleX||1);var c=e.naturalHeight*Math.abs(e.scaleY||1);e=e.rotate||0;e=Math.abs(e);if(90===e%180)e=c,c=d;else{e=e%90*Math.PI/180;var g=Math.sin(e),
l=Math.cos(e);e=d*l+c*g;c=d*g+c*l}d=e;e=d/b.naturalWidth*b.width;g=c/b.naturalHeight*b.height;b.left-=(e-b.width)/2;b.top-=(g-b.height)/2;b.width=e;b.height=g;b.aspectRatio=d/c;b.naturalWidth=d;b.naturalHeight=c;this.limitCanvas(!0,!1)}if(b.width>b.maxWidth||b.width<b.minWidth)b.left=b.oldLeft;if(b.height>b.maxHeight||b.height<b.minHeight)b.top=b.oldTop;b.width=Math.min(Math.max(b.width,b.minWidth),b.maxWidth);b.height=Math.min(Math.max(b.height,b.minHeight),b.maxHeight);this.limitCanvas(!1,!0);b.left=
Math.min(Math.max(b.left,b.minLeft),b.maxLeft);b.top=Math.min(Math.max(b.top,b.minTop),b.maxTop);b.oldLeft=b.left;b.oldTop=b.top;this.$canvas.css({width:b.width,height:b.height,transform:B({translateX:b.left,translateY:b.top})});this.renderImage(a);this.cropped&&this.limited&&this.limitCropBox(!0,!0)},renderImage:function(a){var d=this.canvas,b=this.image,e=d.width/d.naturalWidth*b.naturalWidth,f=d.height/d.naturalHeight*b.naturalHeight;c.extend(b,{width:e,height:f,left:(d.width-e)/2,top:(d.height-
f)/2});this.$clone.css({width:b.width,height:b.height,transform:B(c.extend({translateX:b.left,translateY:b.top},b))});a&&this.output()},initCropBox:function(){var a=this.options,d=this.canvas,b=a.aspectRatio;a=Number(a.autoCropArea)||.8;var e={width:d.width,height:d.height};b&&(d.height*b>d.width?e.height=e.width/b:e.width=e.height*b);this.cropBox=e;this.limitCropBox(!0,!0);e.width=Math.min(Math.max(e.width,e.minWidth),e.maxWidth);e.height=Math.min(Math.max(e.height,e.minHeight),e.maxHeight);e.width=
Math.max(e.minWidth,e.width*a);e.height=Math.max(e.minHeight,e.height*a);e.left=d.left+(d.width-e.width)/2;e.top=d.top+(d.height-e.height)/2;e.oldLeft=e.left;e.oldTop=e.top;this.initialCropBox=c.extend({},e)},limitCropBox:function(a,d){var b=this.options,e=this.container,c=this.canvas,g=this.cropBox,l=this.limited,h=b.aspectRatio;if(a){a=Number(b.minCropBoxWidth)||0;b=Number(b.minCropBoxHeight)||0;var n=Math.min(e.width,l?c.width:e.width),m=Math.min(e.height,l?c.height:e.height);a=Math.min(a,e.width);
b=Math.min(b,e.height);h&&(a&&b?b*h>a?b=a/h:a=b*h:a?b=a/h:b&&(a=b*h),m*h>n?m=n/h:n=m*h);g.minWidth=Math.min(a,n);g.minHeight=Math.min(b,m);g.maxWidth=n;g.maxHeight=m}d&&(l?(g.minLeft=Math.max(0,c.left),g.minTop=Math.max(0,c.top),g.maxLeft=Math.min(e.width,c.left+c.width)-g.width,g.maxTop=Math.min(e.height,c.top+c.height)-g.height):(g.minLeft=0,g.minTop=0,g.maxLeft=e.width-g.width,g.maxTop=e.height-g.height))},renderCropBox:function(){var a=this.options,d=this.container,b=this.cropBox;if(b.width>b.maxWidth||
b.width<b.minWidth)b.left=b.oldLeft;if(b.height>b.maxHeight||b.height<b.minHeight)b.top=b.oldTop;b.width=Math.min(Math.max(b.width,b.minWidth),b.maxWidth);b.height=Math.min(Math.max(b.height,b.minHeight),b.maxHeight);this.limitCropBox(!1,!0);b.left=Math.min(Math.max(b.left,b.minLeft),b.maxLeft);b.top=Math.min(Math.max(b.top,b.minTop),b.maxTop);b.oldLeft=b.left;b.oldTop=b.top;a.movable&&a.cropBoxMovable&&this.$face.data("action",b.width>=d.width&&b.height>=d.height?"move":"all");this.$cropBox.css({width:b.width,
height:b.height,transform:B({translateX:b.left,translateY:b.top})});this.cropped&&this.limited&&this.limitCanvas(!0,!0);this.disabled||this.output()},output:function(){this.preview();this.completed&&this.trigger("crop",this.getData())}};I={initPreview:function(){var a=this.crossOrigin,d=a?this.crossOriginUrl:this.url,b=document.createElement("img");a&&(b.crossOrigin=a);b.src=d;b=c(b);this.$preview=c(this.options.preview);this.$clone2=b;this.$viewBox.html(b);this.$preview.each(function(b,f){b=c(f);
f=document.createElement("img");b.data("preview",{width:b.width(),height:b.height(),html:b.html()});a&&(f.crossOrigin=a);f.src=d;f.style.cssText='display:block;width:100%;height:auto;min-width:0!important;min-height:0!important;max-width:none!important;max-height:none!important;image-orientation:0deg!important;"';b.html(f)})},resetPreview:function(){this.$preview.each(function(a,d){a=c(d);d=a.data("preview");a.css({width:d.width,height:d.height}).html(d.html).removeData("preview")})},preview:function(){var a=
this.image,d=this.canvas,b=this.cropBox,e=b.width,f=b.height,g=a.width,l=a.height,h=b.left-d.left-a.left,n=b.top-d.top-a.top;this.cropped&&!this.disabled&&(this.$clone2.css({width:g,height:l,transform:B(c.extend({translateX:-h,translateY:-n},a))}),this.$preview.each(function(b,d){b=c(d);var m=b.data("preview");d=m.width;m=m.height;var q=d,k=m,p=1;e&&(p=d/e,k=f*p);f&&k>m&&(p=m/f,q=e*p,k=m);b.css({width:q,height:k}).find("img").css({width:g*p,height:l*p,transform:B(c.extend({translateX:-h*p,translateY:-n*
p},a))})}))}};var ia={bind:function(){var a=this.$element,d=this.options,b=this.$cropper;if(c.isFunction(d.cropstart))a.on("cropstart",d.cropstart);if(c.isFunction(d.cropmove))a.on("cropmove",d.cropmove);if(c.isFunction(d.cropend))a.on("cropend",d.cropend);if(c.isFunction(d.crop))a.on("crop",d.crop);if(c.isFunction(d.zoom))a.on("zoom",d.zoom);b.on(N,t(this.cropStart,this));if(d.zoomable&&d.zoomOnWheel)b.on("wheel mousewheel DOMMouseScroll",t(this.wheel,this));if(d.toggleDragModeOnDblclick)b.on("dblclick",
t(this.dblclick,this));c(document).on(O,this.onCropMove=t(this.cropMove,this)).on(P,this.onCropEnd=t(this.cropEnd,this));if(d.responsive)c(window).on("resize",this.onResize=t(this.resize,this))},unbind:function(){var a=this.$element,d=this.options,b=this.$cropper;c.isFunction(d.cropstart)&&a.off("cropstart",d.cropstart);c.isFunction(d.cropmove)&&a.off("cropmove",d.cropmove);c.isFunction(d.cropend)&&a.off("cropend",d.cropend);c.isFunction(d.crop)&&a.off("crop",d.crop);c.isFunction(d.zoom)&&a.off("zoom",
d.zoom);b.off(N,this.cropStart);d.zoomable&&d.zoomOnWheel&&b.off("wheel mousewheel DOMMouseScroll",this.wheel);d.toggleDragModeOnDblclick&&b.off("dblclick",this.dblclick);c(document).off(O,this.onCropMove).off(P,this.onCropEnd);d.responsive&&c(window).off("resize",this.onResize)}},ja={resize:function(){var a=this.options,d=this.$container,b=this.container,e=Number(a.minContainerWidth)||200,f=Number(a.minContainerHeight)||100;if(!(this.disabled||b.width<=e||b.height<=f)){var g=d.width()/b.width;if(1!==
g||d.height()!==b.height){var l=void 0,h=void 0;a.restore&&(l=this.getCanvasData(),h=this.getCropBoxData());this.render();a.restore&&(this.setCanvasData(c.each(l,function(a,b){l[a]=b*g})),this.setCropBoxData(c.each(h,function(a,b){h[a]=b*g})))}}},dblclick:function(){this.disabled||"none"===this.options.dragMode||this.setDragMode(this.$dragBox.hasClass("cropper-crop")?"move":"crop")},wheel:function(a){var d=this,b=a.originalEvent||a,e=Number(this.options.wheelZoomRatio)||.1;if(!this.disabled&&(a.preventDefault(),
!this.wheeling)){this.wheeling=!0;setTimeout(function(){d.wheeling=!1},50);var c=1;b.deltaY?c=0<b.deltaY?1:-1:b.wheelDelta?c=-b.wheelDelta/120:b.detail&&(c=0<b.detail?1:-1);this.zoom(-c*e,a)}},cropStart:function(a){if(!this.disabled){var d=this.options,b=this.pointers,e=a.originalEvent,f=void 0;e&&e.changedTouches?c.each(e.changedTouches,function(a,d){b[d.identifier]=G(d)}):b[e&&e.pointerId||0]=G(e||a);f=1<H(b).length&&d.zoomable&&d.zoomOnTouch?"zoom":c(a.target).data("action");da.test(f)&&!this.trigger("cropstart",
{originalEvent:e,action:f}).isDefaultPrevented()&&(a.preventDefault(),this.action=f,this.cropping=!1,"crop"===f&&(this.cropping=!0,this.$dragBox.addClass("cropper-modal")))}},cropMove:function(a){var d=this.action;if(!this.disabled&&d){var b=this.pointers,e=a.originalEvent;a.preventDefault();this.trigger("cropmove",{originalEvent:e,action:d}).isDefaultPrevented()||(e&&e.changedTouches?c.each(e.changedTouches,function(a,d){c.extend(b[d.identifier],G(d,!0))}):c.extend(b[e&&e.pointerId||0],G(e||a,!0)),
this.change(a))}},cropEnd:function(a){if(!this.disabled){var d=this.action,b=this.pointers,e=a.originalEvent;e&&e.changedTouches?c.each(e.changedTouches,function(a,d){delete b[d.identifier]}):delete b[e&&e.pointerId||0];d&&(a.preventDefault(),H(b).length||(this.action=""),this.cropping&&(this.cropping=!1,this.$dragBox.toggleClass("cropper-modal",this.cropped&&this.options.modal)),this.trigger("cropend",{originalEvent:e,action:d}))}}},ka={change:function(a){var d=this.pointers,b=this.container,e=this.canvas,
f=this.cropBox,g=this.action,l=this.options.aspectRatio,h=f.left,n=f.top,m=f.width,q=f.height,k=h+m,p=n+q,t=0,r=0,x=b.width,w=b.height,z=!0,y=void 0;!l&&a.shiftKey&&(l=m&&q?m/q:1);this.limited&&(t=f.minLeft,r=f.minTop,x=t+Math.min(b.width,e.width,e.left+e.width),w=r+Math.min(b.height,e.height,e.top+e.height));b=d[H(d)[0]];var v=b.endX-b.startX,u=b.endY-b.startY;y=function(a){switch(a){case "e":k+v>x&&(v=x-k);break;case "w":h+v<t&&(v=t-h);break;case "n":n+u<r&&(u=r-n);break;case "s":p+u>w&&(u=w-p)}};
switch(g){case "all":h+=v;n+=u;break;case "e":if(0<=v&&(k>=x||l&&(n<=r||p>=w))){z=!1;break}y("e");m+=v;l&&(q=m/l,n-=v/l/2);0>m&&(g="w",m=0);break;case "n":if(0>=u&&(n<=r||l&&(h<=t||k>=x))){z=!1;break}y("n");q-=u;n+=u;l&&(m=q*l,h+=u*l/2);0>q&&(g="s",q=0);break;case "w":if(0>=v&&(h<=t||l&&(n<=r||p>=w))){z=!1;break}y("w");m-=v;h+=v;l&&(q=m/l,n+=v/l/2);0>m&&(g="e",m=0);break;case "s":if(0<=u&&(p>=w||l&&(h<=t||k>=x))){z=!1;break}y("s");q+=u;l&&(m=q*l,h-=u*l/2);0>q&&(g="n",q=0);break;case "ne":if(l){if(0>=
u&&(n<=r||k>=x)){z=!1;break}y("n");q-=u;n+=u;m=q*l}else y("n"),y("e"),0<=v?k<x?m+=v:0>=u&&n<=r&&(z=!1):m+=v,0>=u?n>r&&(q-=u,n+=u):(q-=u,n+=u);0>m&&0>q?(g="sw",m=q=0):0>m?(g="nw",m=0):0>q&&(g="se",q=0);break;case "nw":if(l){if(0>=u&&(n<=r||h<=t)){z=!1;break}y("n");q-=u;n+=u;m=q*l;h+=u*l}else y("n"),y("w"),0>=v?h>t?(m-=v,h+=v):0>=u&&n<=r&&(z=!1):(m-=v,h+=v),0>=u?n>r&&(q-=u,n+=u):(q-=u,n+=u);0>m&&0>q?(g="se",m=q=0):0>m?(g="ne",m=0):0>q&&(g="sw",q=0);break;case "sw":if(l){if(0>=v&&(h<=t||p>=w)){z=!1;
break}y("w");m-=v;h+=v;q=m/l}else y("s"),y("w"),0>=v?h>t?(m-=v,h+=v):0<=u&&p>=w&&(z=!1):(m-=v,h+=v),0<=u?p<w&&(q+=u):q+=u;0>m&&0>q?(g="ne",m=q=0):0>m?(g="se",m=0):0>q&&(g="nw",q=0);break;case "se":if(l){if(0<=v&&(k>=x||p>=w)){z=!1;break}y("e");m+=v;q=m/l}else y("s"),y("e"),0<=v?k<x?m+=v:0<=u&&p>=w&&(z=!1):m+=v,0<=u?p<w&&(q+=u):q+=u;0>m&&0>q?(g="nw",m=q=0):0>m?(g="sw",m=0):0>q&&(g="ne",q=0);break;case "move":this.move(v,u);z=!1;break;case "zoom":this.zoom(V(d),a.originalEvent);z=!1;break;case "crop":v&&
u?(y=this.$cropper.offset(),h=b.startX-y.left,n=b.startY-y.top,m=f.minWidth,q=f.minHeight,0<v?g=0<u?"se":"ne":0>v&&(h-=m,g=0<u?"sw":"nw"),0>u&&(n-=q),this.cropped||(this.$cropBox.removeClass("cropper-hidden"),this.cropped=!0,this.limited&&this.limitCropBox(!0,!0))):z=!1}z&&(f.width=m,f.height=q,f.left=h,f.top=n,this.action=g,this.renderCropBox());c.each(d,function(a,b){b.startX=b.endX;b.startY=b.endY})}},la={crop:function(){this.ready&&!this.disabled&&(this.cropped||(this.cropped=!0,this.limitCropBox(!0,
!0),this.options.modal&&this.$dragBox.addClass("cropper-modal"),this.$cropBox.removeClass("cropper-hidden")),this.setCropBoxData(this.initialCropBox))},reset:function(){this.ready&&!this.disabled&&(this.image=c.extend({},this.initialImage),this.canvas=c.extend({},this.initialCanvas),this.cropBox=c.extend({},this.initialCropBox),this.renderCanvas(),this.cropped&&this.renderCropBox())},clear:function(){this.cropped&&!this.disabled&&(c.extend(this.cropBox,{left:0,top:0,width:0,height:0}),this.cropped=
!1,this.renderCropBox(),this.limitCanvas(!0,!0),this.renderCanvas(),this.$dragBox.removeClass("cropper-modal"),this.$cropBox.addClass("cropper-hidden"))},replace:function(a,d){!this.disabled&&a&&(this.isImg&&this.$element.attr("src",a),d?(this.url=a,this.$clone.attr("src",a),this.ready&&this.$preview.find("img").add(this.$clone2).attr("src",a)):(this.isImg&&(this.replaced=!0),this.options.data=null,this.load(a)))},enable:function(){this.ready&&(this.disabled=!1,this.$cropper.removeClass("cropper-disabled"))},
disable:function(){this.ready&&(this.disabled=!0,this.$cropper.addClass("cropper-disabled"))},destroy:function(){var a=this.$element;this.loaded?(this.isImg&&this.replaced&&a.attr("src",this.originalUrl),this.unbuild(),a.removeClass("cropper-hidden")):this.isImg?a.off("load",this.start):this.$clone&&this.$clone.remove();a.removeData("cropper")},move:function(a,d){var b=this.canvas,e=b.left;b=b.top;this.moveTo(r(a)?a:e+Number(a),r(d)?d:b+Number(d))},moveTo:function(a,d){var b=this.canvas,e=!1;r(d)&&
(d=a);a=Number(a);d=Number(d);this.ready&&!this.disabled&&this.options.movable&&(k(a)&&(b.left=a,e=!0),k(d)&&(b.top=d,e=!0),e&&this.renderCanvas(!0))},zoom:function(a,d){var b=this.canvas;a=Number(a);this.zoomTo(b.width*(0>a?1/(1-a):1+a)/b.naturalWidth,d)},zoomTo:function(a,d){var b=this.options,e=this.pointers,c=this.canvas,g=c.width,l=c.height,h=c.naturalWidth,n=c.naturalHeight;a=Number(a);0<=a&&this.ready&&!this.disabled&&b.zoomable&&(b=h*a,a*=n,n=void 0,d&&(n=d.originalEvent),this.trigger("zoom",
{originalEvent:n,oldRatio:g/h,ratio:b/h}).isDefaultPrevented()||(n?(h=this.$cropper.offset(),d=e&&H(e).length?W(e):{pageX:d.pageX||n.pageX||0,pageY:d.pageY||n.pageY||0},c.left-=(d.pageX-h.left-c.left)/g*(b-g),c.top-=(d.pageY-h.top-c.top)/l*(a-l)):(c.left-=(b-g)/2,c.top-=(a-l)/2),c.width=b,c.height=a,this.renderCanvas(!0)))},rotate:function(a){this.rotateTo((this.image.rotate||0)+Number(a))},rotateTo:function(a){a=Number(a);k(a)&&this.ready&&!this.disabled&&this.options.rotatable&&(this.image.rotate=
a%360,this.renderCanvas(!0,!0))},scaleX:function(a){var d=this.image.scaleY;this.scale(a,k(d)?d:1)},scaleY:function(a){var d=this.image.scaleX;this.scale(k(d)?d:1,a)},scale:function(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:a,b=this.image,c=!1;a=Number(a);d=Number(d);this.ready&&!this.disabled&&this.options.scalable&&(k(a)&&(b.scaleX=a,c=!0),k(d)&&(b.scaleY=d,c=!0),c&&this.renderCanvas(!0,!0))},getData:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:!1,
d=this.options,b=this.image,e=this.canvas,f=this.cropBox,g=void 0;if(this.ready&&this.cropped){g={x:f.left-e.left,y:f.top-e.top,width:f.width,height:f.height};var l=b.width/b.naturalWidth;c.each(g,function(b,d){d/=l;g[b]=a?Math.round(d):d})}else g={x:0,y:0,width:0,height:0};d.rotatable&&(g.rotate=b.rotate||0);d.scalable&&(g.scaleX=b.scaleX||1,g.scaleY=b.scaleY||1);return g},setData:function(a){var d=this.options,b=this.image,e=this.canvas,f={};c.isFunction(a)&&(a=a.call(this.element));if(this.ready&&
!this.disabled&&c.isPlainObject(a)){var g=!1;d.rotatable&&k(a.rotate)&&a.rotate!==b.rotate&&(b.rotate=a.rotate,g=!0);d.scalable&&(k(a.scaleX)&&a.scaleX!==b.scaleX&&(b.scaleX=a.scaleX,g=!0),k(a.scaleY)&&a.scaleY!==b.scaleY&&(b.scaleY=a.scaleY,g=!0));g&&this.renderCanvas(!0,!0);d=b.width/b.naturalWidth;k(a.x)&&(f.left=a.x*d+e.left);k(a.y)&&(f.top=a.y*d+e.top);k(a.width)&&(f.width=a.width*d);k(a.height)&&(f.height=a.height*d);this.setCropBoxData(f)}},getContainerData:function(){return this.ready?c.extend({},
this.container):{}},getImageData:function(){return this.loaded?c.extend({},this.image):{}},getCanvasData:function(){var a=this.canvas,d={};this.ready&&c.each("left top width height naturalWidth naturalHeight".split(" "),function(b,c){d[c]=a[c]});return d},setCanvasData:function(a){var d=this.canvas,b=d.aspectRatio;c.isFunction(a)&&(a=a.call(this.$element));this.ready&&!this.disabled&&c.isPlainObject(a)&&(k(a.left)&&(d.left=a.left),k(a.top)&&(d.top=a.top),k(a.width)?(d.width=a.width,d.height=a.width/
b):k(a.height)&&(d.height=a.height,d.width=a.height*b),this.renderCanvas(!0))},getCropBoxData:function(){var a=this.cropBox;return this.ready&&this.cropped?{left:a.left,top:a.top,width:a.width,height:a.height}:{}},setCropBoxData:function(a){var d=this.cropBox,b=this.options.aspectRatio,e=void 0,f=void 0;c.isFunction(a)&&(a=a.call(this.$element));this.ready&&this.cropped&&!this.disabled&&c.isPlainObject(a)&&(k(a.left)&&(d.left=a.left),k(a.top)&&(d.top=a.top),k(a.width)&&a.width!==d.width&&(e=!0,d.width=
a.width),k(a.height)&&a.height!==d.height&&(f=!0,d.height=a.height),b&&(e?d.height=d.width/b:f&&(d.width=d.height*b)),this.renderCropBox())},getCroppedCanvas:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};if(!this.ready||!window.HTMLCanvasElement)return null;var d=Y(this.$clone[0],this.image,this.canvas,a);if(!this.cropped)return d;var b=this.getData(),e=b.x,f=b.y,g=b.width;b=b.height;var l=g/b,h=E({aspectRatio:l,width:a.maxWidth||Infinity,height:a.maxHeight||Infinity}),
n=E({aspectRatio:l,width:a.minWidth||0,height:a.minHeight||0}),m=E({aspectRatio:l,width:a.width||g,height:a.height||b});l=m.width;m=m.height;l=Math.min(h.width,Math.max(n.width,l));m=Math.min(h.height,Math.max(n.height,m));h=document.createElement("canvas");n=h.getContext("2d");h.width=w(l);h.height=w(m);n.fillStyle=a.fillColor||"transparent";n.fillRect(0,0,l,m);m=a.imageSmoothingEnabled;a=a.imageSmoothingQuality;n.imageSmoothingEnabled=void 0===m?!0:m;a&&(n.imageSmoothingQuality=a);a=d.width;m=d.height;
var k=e,p=f,r=void 0,t=void 0,A=e=f=void 0,x=void 0;k<=-g||k>a?A=f=r=k=0:0>=k?(f=-k,k=0,A=r=Math.min(a,g+k)):k<=a&&(f=0,A=r=Math.min(g,a-k));0>=r||p<=-b||p>m?x=e=t=p=0:0>=p?(e=-p,p=0,x=t=Math.min(m,b+p)):p<=m&&(e=0,x=t=Math.min(b,m-p));b=[k,p,r,t];0<A&&0<x&&(g=l/g,b.push(f*g,e*g,A*g,x*g));n.drawImage.apply(n,[d].concat(ca(c.map(b,function(a){return Math.floor(w(a))}))));return h},setAspectRatio:function(a){var d=this.options;this.disabled||r(a)||(d.aspectRatio=Math.max(0,a)||NaN,this.ready&&(this.initCropBox(),
this.cropped&&this.renderCropBox()))},setDragMode:function(a){var d=this.options;if(this.loaded&&!this.disabled){var b="crop"===a;var c=d.movable&&"move"===a;a=b||c?a:"none";this.$dragBox.data("action",a).toggleClass("cropper-crop",b).toggleClass("cropper-move",c);d.cropBoxMovable||this.$face.data("action",a).toggleClass("cropper-crop",b).toggleClass("cropper-move",c)}}},ma=function(){function a(a,b){for(var d=0;d<b.length;d++){var c=b[d];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&
(c.writable=!0);Object.defineProperty(a,c.key,c)}}return function(d,b,c){b&&a(d.prototype,b);c&&a(d,c);return d}}(),J=function(){function a(d){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");if(!d||!ha.test(d.tagName))throw Error("The first argument is required and must be an <img> or <canvas> element.");this.element=d;this.$element=c(d);this.options=c.extend({},Q,c.isPlainObject(b)&&b);this.wheeling=
this.replaced=this.ready=this.loaded=this.limited=this.isImg=this.disabled=this.cropped=this.completed=!1;this.originalUrl="";this.cropBox=this.canvas=null;this.pointers={};this.init()}ma(a,[{key:"init",value:function(){var a=this.$element,b=void 0;if(a.is("img")){this.isImg=!0;this.originalUrl=b=a.attr("src")||"";if(!b)return;b=a.prop("src")}else a.is("canvas")&&window.HTMLCanvasElement&&(b=a[0].toDataURL());this.load(b)}},{key:"trigger",value:function(a,b){a=c.Event(a,b);this.$element.trigger(a);
return a}},{key:"load",value:function(a){var b=this;if(a){this.url=a;this.image={};var d=this.$element,c=this.options;if(c.checkOrientation&&window.ArrayBuffer)if(ea.test(a))fa.test(a)?this.read(Z(a)):this.clone();else{var g=new XMLHttpRequest;g.onerror=function(){b.clone()};g.onload=function(){b.read(g.response)};c.checkCrossOrigin&&A(a)&&d.prop("crossOrigin")&&(a=D(a));g.open("get",a);g.responseType="arraybuffer";g.withCredentials="use-credentials"===d.prop("crossOrigin");g.send()}else this.clone()}}},
{key:"read",value:function(a){var b=this.options,d=this.image;var c=new DataView(a);var g=void 0,l=void 0,h=void 0,k=void 0;if(255===c.getUint8(0)&&216===c.getUint8(1))for(var m=c.byteLength,q=2;q<m;){if(255===c.getUint8(q)&&225===c.getUint8(q+1)){h=q;break}q+=1}if(h){m=h+10;var p=h+4;q="";for(h=4+p;p<h;p+=1)q+=M(c.getUint8(p));"Exif"===q&&(h=c.getUint16(m),!(l=18761===h)&&19789!==h||42!==c.getUint16(m+2,l)||(h=c.getUint32(m+4,l),8<=h&&(k=m+h)))}if(k)for(m=c.getUint16(k,l),q=0;q<m;q+=1)if(h=k+12*
q+2,274===c.getUint16(h,l)){h+=8;g=c.getUint16(h,l);c.setUint16(h,1,l);break}c=g;g=0;k=l=1;if(1<c){this.url=ba(a,"image/jpeg");g=0;a=l=1;switch(c){case 2:l=-1;break;case 3:g=-180;break;case 4:a=-1;break;case 5:g=90;a=-1;break;case 6:g=90;break;case 7:g=90;l=-1;break;case 8:g=-90}k=a}b.rotatable&&(d.rotate=g);b.scalable&&(d.scaleX=l,d.scaleY=k);this.clone()}},{key:"clone",value:function(){var a=this.$element,b=this.url,e="",f=void 0;this.options.checkCrossOrigin&&A(b)&&((e=a.prop("crossOrigin"))?f=
b:(e="anonymous",f=D(b)));this.crossOrigin=e;this.crossOriginUrl=f;var g=document.createElement("img");e&&(g.crossOrigin=e);g.src=f||b;this.$clone=b=c(g);if(this.isImg)if(this.element.complete)this.start();else a.one("load",c.proxy(this.start,this));else b.one("load",c.proxy(this.start,this)).one("error",c.proxy(this.stop,this)).addClass("cropper-hide").insertAfter(a)}},{key:"start",value:function(){var a=this,b=this.$clone,e=this.$element;this.isImg||(b.off("error",this.stop),e=b);F(e[0],function(b,
d){c.extend(a.image,{naturalWidth:b,naturalHeight:d,aspectRatio:b/d});a.loaded=!0;a.build()})}},{key:"stop",value:function(){this.$clone.remove();this.$clone=null}},{key:"build",value:function(){var a=this;if(this.loaded){this.ready&&this.unbuild();var b=this.$element,e=this.options,f=this.$clone,g=c('<div class="cropper-container"><div class="cropper-wrap-box"><div class="cropper-canvas"></div></div><div class="cropper-drag-box"></div><div class="cropper-crop-box"><span class="cropper-view-box"></span><span class="cropper-dashed dashed-h"></span><span class="cropper-dashed dashed-v"></span><span class="cropper-center"></span><span class="cropper-face"></span><span class="cropper-line line-e" data-action="e"></span><span class="cropper-line line-n" data-action="n"></span><span class="cropper-line line-w" data-action="w"></span><span class="cropper-line line-s" data-action="s"></span><span class="cropper-point point-e" data-action="e"></span><span class="cropper-point point-n" data-action="n"></span><span class="cropper-point point-w" data-action="w"></span><span class="cropper-point point-s" data-action="s"></span><span class="cropper-point point-ne" data-action="ne"></span><span class="cropper-point point-nw" data-action="nw"></span><span class="cropper-point point-sw" data-action="sw"></span><span class="cropper-point point-se" data-action="se"></span></div></div>'),
l=g.find(".cropper-crop-box"),h=l.find(".cropper-face");this.$container=b.parent();this.$cropper=g;this.$canvas=g.find(".cropper-canvas").append(f);this.$dragBox=g.find(".cropper-drag-box");this.$cropBox=l;this.$viewBox=g.find(".cropper-view-box");this.$face=h;b.addClass("cropper-hidden").after(g);this.isImg||f.removeClass("cropper-hide");this.initPreview();this.bind();e.aspectRatio=Math.max(0,e.aspectRatio)||NaN;e.viewMode=Math.max(0,Math.min(3,Math.round(e.viewMode)))||0;(this.cropped=e.autoCrop)?
e.modal&&this.$dragBox.addClass("cropper-modal"):l.addClass("cropper-hidden");e.guides||l.find(".cropper-dashed").addClass("cropper-hidden");e.center||l.find(".cropper-center").addClass("cropper-hidden");e.cropBoxMovable&&h.addClass("cropper-move").data("action","all");e.highlight||h.addClass("cropper-invisible");e.background&&g.addClass("cropper-bg");e.cropBoxResizable||l.find(".cropper-line,.cropper-point").addClass("cropper-hidden");this.setDragMode(e.dragMode);this.render();this.ready=!0;this.setData(e.data);
this.completing=setTimeout(function(){if(c.isFunction(e.ready))b.one("ready",e.ready);a.trigger("ready");a.trigger("crop",a.getData());a.completed=!0},0)}}},{key:"unbuild",value:function(){this.ready&&(this.completed||clearTimeout(this.completing),this.completed=this.ready=!1,this.cropBox=this.canvas=this.container=this.initialCropBox=this.initialCanvas=this.initialImage=null,this.unbind(),this.resetPreview(),this.$container=this.$canvas=this.$dragBox=this.$cropBox=this.$viewBox=this.$preview=null,
this.$cropper.remove(),this.$cropper=null)}}],[{key:"setDefaults",value:function(a){c.extend(Q,c.isPlainObject(a)&&a)}}]);return a}();c.extend&&c.extend(J.prototype,C,I,ia,ja,ka,la);if(c.fn){var na=c.fn.cropper;c.fn.cropper=function(a){for(var d=arguments.length,b=Array(1<d?d-1:0),e=1;e<d;e++)b[e-1]=arguments[e];var f=void 0;this.each(function(d,e){d=c(e);var g=d.data("cropper");if(!g){if(/destroy/.test(a))return;g=c.extend({},d.data(),c.isPlainObject(a)&&a);g=new J(e,g);d.data("cropper",g)}"string"===
typeof a&&(e=g[a],c.isFunction(e)&&(f=e.apply(g,b)))});return r(f)?this:f};c.fn.cropper.Constructor=J;c.fn.cropper.setDefaults=J.setDefaults;c.fn.cropper.noConflict=function(){c.fn.cropper=na;return this}}});
function getImageBase64(c,p){var k=c.cropper("getCroppedCanvas").toDataURL(uploadedImageType);new FileReader;var r=new Image,t=document.createElement("canvas"),w=t.getContext("2d");r.src=k;r.onload=function(){var c=this.width,D=this.height,B=c,F=D;if(c>maxWidth||D>maxHeight)c/D>maxWidth/maxHeight?(B=maxWidth,F=Math.round(D/c*maxWidth)):(F=maxHeight,B=Math.round(c/D*maxHeight));t.width=B;t.height=F;w.clearRect(0,0,t.width,t.height);w.drawImage(r,0,0,t.width,t.height);k=t.toDataURL(uploadedImageType);
p(k)}};
