/*
 ??????
 @author ThinkGem
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,b){a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var f=a[e];if(d.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var d=0;d<a.length;++d){var b=a[d];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,c){if(d){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in b||(b[e]={});b=b[e]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");$(function(){unreadMsg()});
function unreadMsg(){$.get(ctx+"/msg/unreadMsg?__notUpdateSession=true&__t="+(new Date).getTime(),function(a){if(a&&"login"!=a.result){var d=$("#msgList").empty(),b=a.count||0;a=a.list||[];for(i=0;i<a.length;i++)d.append(js.template("msgListTpl",a[i]));$("#msgNum, #msgNum2").text(b);$(".timeago").timeago();pullPoolMsg();window.ppmInt&&clearInterval(window.ppmInt);a=$("#msgList").attr("data-pullMsgPollingInterval");window.ppmInt=setInterval(pullPoolMsg,a&&""!=a?eval(a):6E4)}else(d=$("#msgList").attr("data-loginTimeout"))&&
""!=d&&(js.alert(d,function(){location.reload(!0)}),window.ppmInt&&clearInterval(window.ppmInt)),log(a)},"json")}
function pullPoolMsg(){var a=$("#msgList"),d=a.attr("data-mergeMsgLimit");$.get(ctx+"/msg/pullPoolMsg?__notUpdateSession=true&__t="+(new Date).getTime(),function(b){if(b&&"login"!=b.result){for(i=0;i<b.length;i++){if(!(b.length>d)){var c=js.template("msgTipTpl",b[i]),e=a.attr("data-showMsgCloseTimeout");js.showMessage(c,b[i].msgContentEntity.title,"info",e&&""!=e?eval(e):6E4);doFlashTitle()}b[i].id&&""!=b[i].id&&a.prepend(js.template("msgListTpl",b[i]))}b.length>d&&(c={msgContentEntity:{title:a.attr("data-mergeMsgTitle"),
content:js.text(a.attr("data-mergeMsgContent"),b.length)},sendDate:"",sendUserName:"",id:""},c=js.template("msgTipTpl",c),e=a.attr("data-showMsgCloseTimeout"),js.showMessage(c,null,"info",e&&""!=e?eval(e):6E4),doFlashTitle());c=parseInt($("#msgNum").text());c=isNaN(c)?a.find("li").length:c+(b.length||0);$("#msgNum, #msgNum2").text(c);$(".timeago").timeago()}else(c=a.attr("data-loginTimeout"))&&""!=c&&(js.alert(c,function(){location.reload(!0)}),window.ppmInt&&clearInterval(window.ppmInt)),log(b)},
"json")}function readMsg(a,d,b){var c=$(a).data("href");""==b&&(c=ctx+"/msg/list");if(a=js.addTabPage($(a),d,c))$("#"+a+"-frame").on("load",function(){setTimeout(unreadMsg,1E3)})}var isWindowFocus=!0;"onfocusin"in document?(document.onfocusin=function(){isWindowFocus=!0},document.onfocusout=function(){isWindowFocus=!1}):(window.onfocus=function(){isWindowFocus=!0},window.onblur=function(){isWindowFocus=!1});
var flashStep=0,flashTitleRun=!1,normalTitle=document.title,flashTitle=function(){isWindowFocus?(document.title=normalTitle,flashTitleRun=!1):(flashTitleRun=!0,flashStep++,3==flashStep&&(flashStep=1),1==flashStep&&(document.title="\u3010\u65b0\u6d88\u606f\u3011"+normalTitle),2==flashStep&&(document.title="\u3010\u3000\u3000\u3000\u3011"+normalTitle),setTimeout("flashTitle()",500))};function doFlashTitle(){flashTitleRun||flashTitle();var a=document.getElementById("audioMessage");a&&a.play()};
