/*
 Copyright (c) 2013-Now http://jeesite.com All rights reserved.
 The JS file, without author permission, shall not be copied, 
 published and spread, can not be used for commercial purposes
 @author Think Gem, Email: ThinkGem at 163.COM
 @version 2020-4-26
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,f,g){if(null==a)throw new TypeError("The 'this' value for String.prototype."+g+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+g+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,g){a!=Array.prototype&&a!=Object.prototype&&(a[f]=g.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var f=0;f<a.length;++f){var g=a[f];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,f,g,d){if(f){g=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var b=a[d];b in g||(g[b]={});g=g[b]}a=a[a.length-1];d=g[a];f=f(d);f!=d&&null!=f&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,g){var d=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var b=d.length,c=a.length;g=Math.max(0,Math.min(g|0,d.length));for(var h=0;h<c&&g<b;)if(d[g++]!=a[h++])return!1;return h>=c}},"es6","es3");
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,g){var d=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===g&&(g=d.length);g=Math.max(0,Math.min(g|0,d.length));for(var b=a.length;0<b&&0<g;)if(d[--g]!=a[--b])return!1;return 0>=b}},"es6","es3");$jscomp.findInternal=function(a,f,g){a instanceof String&&(a=String(a));for(var d=a.length,b=0;b<d;b++){var c=a[b];if(f.call(g,c,b,a))return{i:b,v:c}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,g){return $jscomp.findInternal(this,a,g).v}},"es6","es3");if("undefined"===typeof jQuery)throw Error("JeeSite's JavaScript requires jQuery");
(function(a,f,g){try{parent.$("iframe.ui-layout-content").each(function(){document.body.ownerDocument===this.contentWindow.document&&a("body").addClass("ui-layout-content")})}catch(b){}a(function(){d.toastr=d.toastrInit();d.iCheck("input[type=checkbox].form-control:not(.noicheck),input[type=radio].form-control:not(.noicheck)");d.select2("select.form-control:not(.noselect2)");d.ie&&a("a").bind("focus",function(){this.blur&&this.blur()});a.fn.textareaAutoHieght&&a("textarea.autoHeight").textareaAutoHieght();
767<a(f).width()&&a("#inputForm:not(.nofocus) input[type=text]:not([readonly]):not([disabled]):not(.nofocus):eq(0)").focus();d.laydate("input.form-control.laydate:not(.readonly):not(.disabled):not(.nolaydate)");a(document).on("click",".addTabPage",function(b){b=a(this);var c=b.data("href")||b.attr("href"),h=0==b.data("title")?!1:b.data("title")||b.attr("title")||b.text();return c&&""!=c&&"blank"!=c?(h=a.trim(h||d.text("tabpanel.newTabPage")),d.addTabPage(b,a.trim(h||d.text("tabpanel.newTabPage")),
c),b.parent().hasClass("treeview")&&(d.window.isMenuClickFlag=!0,d.window.location.hash=c.replace("#","")+"#"+h),!1):!0});if(0<a("#scroll-up").length){var b=a("#scroll-up"),c=!1;a(f).on("scroll.btnScrollTop",function(){var h=a(document).scrollTop(),e=a(f).height(),d=document.body.scrollHeight;h>parseInt(e/4)||0<h&&d>=e&&e+h>=d-1?c||(b.addClass("display"),c=!0):c&&(b.removeClass("display"),c=!1)}).triggerHandler("scroll.btnScrollTop");b.on("click",function(){a("html,body").animate({scrollTop:0},500);
return!1})}});var d={iCheck:function(b){if(b!=g&&a.fn.iCheck!=g)return a(b).each(function(){return a(this).iCheck(a.extend({checkboxClass:"icheckbox_"+(a(this).data("style")||"minimal-grey"),radioClass:"iradio_"+(a(this).data("style")||"minimal-grey")},a(this).data())).on("ifChanged",function(){try{a(this).resetValid()}catch(c){}})})},select2:function(b){if(b!=g&&a.fn.select2!=g)return a(b).each(function(){return a(this).select2(a.extend({minimumResultsForSearch:10,templateResult:function(b,h){var c=
a(b.element);h=a(h);var d=c.attr("style");c=c.attr("class");d&&""!=d&&h.attr("style",d);c&&""!=c&&h.addClass(c);return b.text}},a(this).data())).on("change",function(){try{a(this).resetValid()}catch(c){}})})},laydate:function(b){if(b!=g&&f.laydate!=g)return a(b).each(function(){var b=a(this).data();if(b.ready&&""!=b.ready){var h=b.ready;b.ready=function(b){return eval(h)}}b.done&&""!=b.done&&(h=b.done,b.done=function(b,a,c){b=h.indexOf(".click()");return-1!=b&&(a=h.substring(0,b),/^[a-zA-Z0-9_]*$/.test(a))?
(a="$('#"+a+"')"+h.substring(b),eval(a)):eval(h)});b.change&&""!=b.change&&(h=b.change,b.change=function(b,a,c){return eval(h)});return laydate.render(a.extend({elem:this},b))})},log:function(b){"undefined"!==typeof console&&console.log(b)},error:function(b){"undefined"!==typeof console&&console.error(b)},encodeUrl:function(b){return encodeURIComponent(b)},decodeUrl:function(b){return decodeURIComponent(b)},ie:function(){var b=navigator.userAgent.toLowerCase();return f.ActiveXObject||"ActiveXObject"in
f?(b.match(/msie\s(\d+)/)||[])[1]||(b.match(/Trident/i)&&b.match(/rv:(\d+)/)||[])[1]||!1:!1}(),val:function(b,a){if(b===g)return"";if(a===g||""==a)return"string"===typeof b?b:"";var c=b[a],e=[],d;if(c===g)try{if("string"===typeof a&&(e=a.split(".")),d=e.length)for(c=b;c&&d--;){var v=e.shift();c=c[v]}}catch(k){}return c===g?"":c},hashCode:function(b,a){1!=a&&(b=b.toLowerCase());a=1315423911;var c;for(c=b.length-1;0<=c;c--){var e=b.charCodeAt(c);a^=(a<<5)+e+(a>>2)}return a&2147483647},loadFile:function(b,
c,h){c=c||function(){};h=h||function(b){d.showMessage(b)};b="string"==typeof b?[b]:b;var e=document.getElementsByTagName("head")[0],p=0,v=b.length,k,l=null;for(k=0;k<v;k++){var f=null,g=null;l=b[k];var n=d.hashCode(l);if(document.getElementById("loadHash_"+n)){if(p+=1,p==v)return c(),!0}else{g=l.split("?")[0].split(".");switch(g[g.length-1].toLowerCase()){case "css":f=document.createElement("link");f.setAttribute("rel","stylesheet");f.setAttribute("type","text/css");f.setAttribute("href",l);break;
case "js":f=document.createElement("script");f.setAttribute("type","text/javascript");f.setAttribute("src",l);break;case "jpg":case "jpeg":case "png":case "gif":f=document.createElement("img");f.setAttribute("src",l);break;default:return h("\u8f7d\u5165\u7684\u683c\u5f0f\u4e0d\u652f\u6301:"+l),!1}"undefined"!=typeof f&&(f.setAttribute("id","loadHash_"+n),e.appendChild(f),f.onreadystatechange=function(){if("loaded"==f.readyState||"complete"==f.readyState)if(p+=1,p==v)return c(),!0},f.onload=function(){p+=
1;if(p==v)return c(),!0},f.onerror=function(){a("#loadhash_"+n).remove();return!1})}}},windowOpen:function(b,a,h,e){h&&e||(h=f.screen.width-200,e=f.screen.height-150);var c=parseInt((f.screen.height-e)/2-20,10),d=parseInt((f.screen.width-h)/2,10);f.open(b,a,"location=no,menubar=no,toolbar=no,dependent=yes,minimizable=no,modal=yes,alwaysRaised=yes,resizable=yes,scrollbars=yes,width="+h+",height="+e+",top="+c+",left="+d)},windowClose:function(){setTimeout(function(){f.opener=null;f.open("","_self");
f.close()},100)},addParam:function(b,a){""!=a&&(b+=-1==b.indexOf("?")?"?":"&",b+=a);return b},getParam:function(b,a){b=new RegExp("(^|&)"+b+"=([^&]*)(&|$)","i");a=a&&""!=a?a.substring(a.indexOf("?")):f.location.search;a=a.substr(1).match(b);return null!=a?unescape(a[2]):null},removeParam:function(a,c){a=new RegExp("(^|&)"+a+"=([^&]*)(&|$)","i");var b=c&&""!=c?c.substring(c.indexOf("?")):f.location.search;if(""!=b){if(d.startsWith(b,"?")||d.startsWith(b,"&"))b=b.substr(1);c=c.substring(0,c.indexOf("?")+
1)+b.replace(a,"$1");if(d.endsWith(c,"?")||d.endsWith(c,"&"))return c.substring(0,c.length-1)}return c},alertObj:function(a){a=eval(a);var b=1,h="",e;for(e in a)h+=b++ +"\u3001"+e+" = "+a[e]+"\n";alert(h)},text:function(a,c){if(a){d.i18n=d.i18n||{};var b=d.i18n[a];b&&""!=b||(b=a);if(c)for(var e=1;e<arguments.length;e++)b=b.replace(new RegExp("\\{"+(e-1)+"\\}","gm"),arguments[e]);return b}return a},getDictLabel:function(a,c,h,e){for(var b=[],d=0;d<a.length;d++){var k=a[d];if(-1!=(","+c+",").indexOf(","+
k.dictValue+",")){var l="";e&&(k.cssClass||k.cssStyle)?(l+="<span",k.cssClass&&(l+=' class="'+k.cssClass+'"'),k.cssStyle&&(l+=' style="'+k.cssStyle+'"'),b.push(l+">"+k.dictLabel+"</span>")):b.push(k.dictLabel)}}return 0<b.length?b.join(","):h},loading:function(b,c){try{top.loadingFlag=!0;var h=top.js||parent.parent.js||parent.js}catch(e){}if("undefined"==typeof loadingFlag&&h&&"function"==typeof h.loading)h.loading(b);else{if(b==g||""==b)b=d.text("loading.message");"none"!=b&&setTimeout(function(){d.pageLoadingNum||
(d.pageLoadingNum=0);d.pageLoadingStyle||(a("body").hasClass("loading-topline")?d.pageLoadingStyle=2:d.pageLoadingStyle=1);1==d.pageLoadingStyle?(b+='<em onclick="js.closeLoading(0, true)">\u00d7</em>',0==a("#page-loading").length?a("body").append('<div id="page-loading" onmouseover="$(this).find(\'em\').show()" onmouseout="$(this).find(\'em\').hide()">'+b+"</div>"):1!=c&&a("#page-loading").html(b)):2==d.pageLoadingStyle&&0==a("#page-loading-top").length&&(a("body").append('<div id="page-loading-top" class="page-loading-top"></div>'),
a("#page-loading-top").animate({width:"65%"},2E3,function(){a(this).animate({width:"85%"},8E3)}));d.pageLoadingNum++},0)}},closeLoading:function(b,c){try{top.loadingFlag=!0;var h=top.js||parent.parent.js||parent.js}catch(e){}"undefined"==typeof loadingFlag&&h&&"function"==typeof h.closeLoading?h.closeLoading(b,c):setTimeout(function(){d.pageLoadingNum||(d.pageLoadingNum=0);d.pageLoadingNum--;if(c||0>=d.pageLoadingNum)1==d.pageLoadingStyle?a("#page-loading").remove():2==d.pageLoadingStyle&&a("#page-loading-top").stop().animate({width:"100%"},
200,function(){a(this).fadeOut(300,function(){a(this).remove()})}),d.pageLoadingNum=0},b==g?0:b)},window:function(){try{if(top.window&&top.window.jeesite)return top.window}catch(b){}try{if(parent.parent.window&&parent.parent.window.jeesite)return parent.parent.window}catch(b){}try{if(parent.window&&parent.window.jeesite)return parent.window}catch(b){}return f}(),layer:function(){try{if(top.layer&&top.layer.window)return top.layer}catch(b){}try{if(parent.parent.layer&&parent.parent.layer.window)return parent.parent.layer}catch(b){}try{if(parent.layer&&
parent.layer.window)return parent.layer}catch(b){}return f.layer?layer:null}(),toastrInit:function(){try{if(top.toastr)return top.toastr}catch(b){}try{if(parent.parent.toastr)return parent.parent.toastr}catch(b){}try{if(parent.toastr)return parent.toastr}catch(b){}return null},showMessage:function(a,c,h,e){var b=String(a);a=function(a,c){if(c)for(a=c.split(","),c=0;c<a.length;c++)if(0<=b.indexOf(a[c]))return!0;return!1};h&&"error"==h||!h&&a(b,d.text("showMessage.error"))?(h="error",a=2):h&&"warning"==
h||!h&&a(b,d.text("showMessage.warning"))?(h="warning",a=5):h&&"success"==h||!h&&a(b,d.text("showMessage.success"))?(h="success",a=1):(h="info",a=6);d.toastr?(a="toast-bottom-right",b&&8<=b.length&&0<=b.indexOf("posfull:")&&(e==g&&(e=6E4),a="toast-top-full-width",b=b.substring(8),d.log(b)),d.toastr.options={closeButton:!0,tapToDismiss:!1,progressBar:!0,positionClass:a,timeOut:e},d.toastr[h](b,c)):d.layer?a?d.layer.msg(b,{icon:a,time:e}):d.layer.msg(b,{time:e}):alert(b)},showErrorMessage:function(a){if(a&&
""!=a)if(d.error(d.abbr(a,500)),-1!=a.indexOf("<html ")||-1!=a.indexOf("<head ")||-1!=a.indexOf("<body "))d.showMessage("\u672a\u77e5\u9519\u8bef\uff0cF12\u67e5\u770b\u5f02\u5e38\u4fe1\u606f\uff01",null,"error");else{try{var b=JSON.parse(a);if("object"==typeof b&&"undefined"!=typeof b.message){d.showMessage(b.message,null,"error");return}}catch(h){}d.showMessage(a,null,"error")}},closeMessage:function(){d.toastr&&d.toastr.clear()},alert:function(a,c,h){"object"!=typeof c&&(h=c,c={icon:1});d.layer?
d.layer.alert(a,c,function(a){"function"==typeof h&&h(a);d.layer.close(a)}):(alert(a),"function"==typeof h&&h())},confirm:function(b,c,h,e,f,v,k){var l={icon:3};"object"==typeof c?l=a.extend(!0,l,c):"string"==typeof c&&("function"==typeof h?(l.message=v,l.async=f,l.dataType=e,l.callback=h,l.data=g):(l.message=k,l.async=v,l.dataType=f,l.callback=e,l.data=h),l.url=c);if(d.layer)return d.layer.confirm(b,l,function(a){"function"==typeof c?c():d.ajaxSubmit(l);d.layer.close(a)}),!1;confirm(b)&&("function"==
typeof c?c():d.ajaxSubmit(l))},ajaxSubmit:function(b,c,h,e,f,v){a(".btn").attr("disabled",!0);var k={};"object"==typeof b?k=b:"string"==typeof b&&("function"==typeof c?(k.message=f,k.async=e,k.dataType=h,k.callback=c,k.data=g):(k.message=v,k.async=f,k.dataType=e,k.callback=h,k.data=c),k.url=b);d.loading(k.message||d.text("loading.submitMessage"));k=a.extend(!0,{type:"POST",dataType:"json",async:!0,xhrFields:{withCredentials:!0},error:function(b){a(".btn").attr("disabled",!1);d.showErrorMessage(b.responseText);
d.closeLoading(0,!0)},success:function(b,c,e){a(".btn").attr("disabled",!1);d.closeLoading();"function"==typeof k.callback?k.callback(b,c,e):d.log(b)}},k);a.ajax(k)},ajaxSubmitForm:function(b,c,h,e,f){a(".btn").attr("disabled",!0);var v={};"object"==typeof c?v=c:"function"==typeof c&&(v.message=f,v.async=e,v.dataType=h,v.callback=c);d.loading(v.message||d.text("loading.submitMessage"));!0===v.downloadFile&&(v.iframe=!0);v=a.extend(!0,{type:"POST",dataType:"json",async:!0,xhrFields:{withCredentials:!0},
error:function(b){a(".btn").attr("disabled",!1);d.showErrorMessage(b.responseText);d.closeLoading(0,!0)},success:function(b,c,e){a(".btn").attr("disabled",!1);d.closeLoading();"function"==typeof v.callback?v.callback(b,c,e):d.log(b)}},v);b.ajaxSubmit(v);!0===v.downloadFile&&(a(".btn").attr("disabled",!1),d.closeLoading())},trim:function(a){return jQuery.trim(a)},startWith:function(a,c){return(new RegExp("^"+c)).test(a)},startsWith:function(a,c){return!a||!c||a.length<c.length?!1:a.slice(0,c.length)===
c},endWith:function(a,c){return(new RegExp(c+"$")).test(a)},endsWith:function(a,c){return!a||!c||a.length<c.length?!1:-1!==a.indexOf(c,a.length-c.length)},abbr:function(a,c){c||(c=20);if(null==a||1>a.length)return"";for(var b=0,e=0,d=!1,f=!1,k,l=0;l<a.length;l++)if(1<l&&0==f&&(d=!1),1<l&&1==f&&(d=!0),f=a.charCodeAt(l),1<=f&&126>=f||65376<=f&&65439>=f?(b++,f=!1):(b+=2,e++,f=!0),b>c&&l<=a.length-1){1==f&&1==d&&(k=a.substring(0,l-2)+"...");0==f&&0==d&&(k=a.substring(0,l-3)+"...");1==f&&0==d&&(k=a.substring(0,
l-2)+"...");1==d&&(k=a.substring(0,l-2)+"...");break}return b<=c?a:k},formatNumber:function(a,c,d,e){if("undefined"==typeof a||null==a||""===a)return e||"";a=String(a).replace(/\$|,/g,"");isNaN(a)&&(a="0");e=a==(a=Math.abs(a));a=Math.floor(a*Math.pow(10,c)+.50000000001);var b=a%Math.pow(10,c);a=Math.floor(a/Math.pow(10,c)).toString();for(b=b.toString();b.length<c;)b="0"+b;if(d)for(d=0;d<Math.floor((a.length-(1+d))/3);d++)a=a.substring(0,a.length-(4*d+3))+","+a.substring(a.length-(4*d+3));return 0<
c?(e?"":"-")+a+"."+b:(e?"":"-")+a},formatMoney:function(a,c){if(a==g||""==a)return"0.00";c=0<=c&&20>=c?c:2;a=parseFloat((a+"").replace(/[^\d\.-]/g,"")).toFixed(c)+"";c=a.split(".")[0].split("").reverse();a=a.split(".")[1];var b,e="";for(b=0;b<c.length;b++)e+=c[b]+(0==(b+1)%3&&b+1!=c.length?",":"");return e.split("").reverse().join("")+(a?"."+a:"")},numberPad:function(a,c){for(var b=a.toString().length;b<c;)a="0"+a,b++;return a},formatDate:function(a,c){if(a==g)return"";c==g&&(c="yyyy-MM-dd HH:mm");
var b={"M+":a.getMonth()+1,"d+":a.getDate(),"H+":a.getHours(),"m+":a.getMinutes(),"s+":a.getSeconds(),"q+":Math.floor((a.getMonth()+3)/3),S:a.getMilliseconds()};/(y+)/.test(c)&&(c=c.replace(RegExp.$1,(a.getFullYear()+"").substr(4-RegExp.$1.length)));for(var e in b)(new RegExp("("+e+")")).test(c)&&(c=c.replace(RegExp.$1,1==RegExp.$1.length?b[e]:("00"+b[e]).substr((""+b[e]).length)));return c},parseDate:function(a){return a==g?null:new Date(a.replace(/-/g,"/"))},addDate:function(a,c){if(a==g)return null;
a=a.valueOf();return new Date(a+864E5*c)},addMonths:function(a,c){if(a==g)return null;var b=new Date(a.getFullYear(),a.getMonth(),a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds(),a.getMilliseconds());b.setMonth(a.getMonth()+c);b.getDate()!=a.getDate()&&b.setDate(0);return b},quickSelectDate:function(b,c,h){var e=new Date,f=e.getFullYear(),g=e.getMonth(),k=e.getDate(),l=e.getDay();c=a("#"+c);h=a("#"+h);var u=function(a){return d.formatDate(a,"yyyy-MM-dd")},r=function(a){return(new Date(f,a+1,
1)-new Date(f,a,1))/864E5},n=1;-1!=b.indexOf("|")&&(n=b.split("|"),b=n[0],n=parseInt(n[1]));"1"==b?1!=n?(g=new Date,k=d.addDate(g,0-n),c.val(u(k)),h.val(u(g))):(c.val(u(e)),h.val(c.val())):"2"==b?(l=0==l?6:l-1,r=new Date(f,g,k-l),g=new Date(f,g,k+(6-l)),1!=n&&(r=d.addDate(r,0-n),g=d.addDate(g,0-n)),c.val(u(r)),h.val(u(g))):"3"==b?(k=new Date(f,g,1),g=new Date(f,g,r(g)),c.val(u(k)),h.val(u(g))):"4"==b?(k=0,3>g&&(k=0),2<g&&6>g&&(k=3),5<g&&9>g&&(k=6),8<g&&(k=9),g=k+2,k=new Date(f,k,1),g=new Date(f,g,
r(g)),c.val(u(k)),h.val(u(g))):"5"==b?(g=d.addMonths(new Date,-1),k=d.addMonths(g,1-n),k.setDate(1),g.setDate(r(g.getMonth())),c.val(u(k)),h.val(u(g))):"6"==b&&(g=new Date,k=d.addMonths(g,0-n),c.val(u(k)),h.val(u(g)));c.change();h.change()},template:function(b,c,d){b=String(a("#"+b).html()).replace(/(\/\/<!\-\-)|(\/\/\-\->)/g,"");c=c||[];return"function"==typeof d?(laytpl(b).render(c||[],function(a){d(a)}),null):laytpl(b).render(c||[])},cookie:function(a,c,d){if("undefined"!=typeof c){d=d||{};null===
c&&(c="",d.expires=-1);var b="";d.expires&&("number"==typeof d.expires||d.expires.toUTCString)&&("number"==typeof d.expires?(b=new Date,b.setTime(b.getTime()+864E5*d.expires)):b=d.expires,b="; expires="+b.toUTCString());var f="; path="+(d.path?d.path:"/"),h=d.domain?"; domain="+d.domain:"";d=d.secure?"; secure":"";document.cookie=[a,"=",encodeURIComponent(c),b,f,h,d].join("")}else{c=null;if(document.cookie&&""!=document.cookie)for(d=document.cookie.split(";"),b=d.length-1;0<=b;b--)if(f=jQuery.trim(d[b]),
f.substring(0,a.length+1)==a+"="){c=decodeURIComponent(f.substring(a.length+1));break}return c}},tabPage:function(){if(f.tabPage)return tabPage;try{if(parent.tabPage)return parent.tabPage}catch(b){}try{if(parent.parent.tabPage)return parent.parent.tabPage}catch(b){}try{if(top.tabPage)return top.tabPage}catch(b){}return null}(),initTabPage:function(a,c){return f.tabPage.initTabPage(a,c)},addTabPage:function(b,c,h,e,g){try{top.prevWindow=f}catch(t){}var p=d.tabPage;if(!p||"function"!=typeof p.addTabPage||
"true"==d.cookie("formLayerModel")&&b&&0!=b.data("layer")&&(b.hasClass("btnTool")||b.hasClass("btnList"))||b&&1==b.data("layer"))if(d.layer){if(b){var k=b.data("layerWidth");var l=b.data("layerHeight");var u=b.data("layerLeft");var r=b.data("layerTop");var n=b.data("shadeClose")}if(null==k||""==k)k=a(d.window).width(),k=null!=u&&""!=u?k-2*parseInt(u):800>k?k-30:k-200;if(null==l||""==l)l=a(d.window).height(),l=null!=r&&""!=r?l-2*parseInt(r):500>l?l-30:l-50;d.layer.open({type:2,maxmin:!0,shadeClose:1==
n,title:"false"!=String(c)?c:!1,area:[k+"px",l+"px"],content:h,contentFormData:{__layer:!0,__layer_title:"false"!=String(c)},success:function(c,e){a(d.layer.window).width()<k||a(d.layer.window).height()<l?d.layer.full(e):b&&1==b.data("layerFull")&&d.layer.full(e)}})}else d.windowOpen(h,c,"auto","auto");else return p.addTabPage(b,c,h,e,g)},getCurrentTabPage:function(a){var c=d.tabPage;c&&"function"==typeof c.getCurrentTabPage&&c.getCurrentTabPage(a)},getPrevTabPage:function(a,c){var b=d.tabPage;b&&
"function"==typeof b.getPrevTabPage&&b.getPrevTabPage(a,c)},closeCurrentTabPage:function(a){var c=d.tabPage;if(c&&"function"==typeof c.closeCurrentTabPage&&-1==f.name.indexOf("layui-layer"))c.closeCurrentTabPage(a);else{var b;d.layer&&(b=d.layer.getFrameIndex(f.name));b?d.layer.close(b):d.windowClose();if("function"==typeof a)try{c=g;try{c=top.prevWindow}catch(e){}a(c)}catch(e){d.error(e)}}}};f.js=d;f.log=d.log;f.error=d.error;f.lang=f.lang||"zh_CN";f.text=d.text;f.jeesite=!0})(window.jQuery,window);
+function(a){function f(c){return this.each(function(){var b=a(this),e=b.data("lte.boxwidget");e||(e=a.extend({},g,b.data(),"object"==typeof c&&c),b.data("lte.boxwidget",e=new d(b,e)));if("string"==typeof c){if("undefined"==typeof e[c])throw Error("No method named "+c);e[c]()}})}var g={animationSpeed:500,collapseTrigger:'[data-widget="collapse"]',removeTrigger:'[data-widget="remove"]',collapseIcon:"fa-minus",expandIcon:"fa-plus",removeIcon:"fa-times"},d=function(a,b){this.element=a;this.options=b;
this._setUpListeners()};d.prototype.toggle=function(){a(this.element).is(".collapsed-box")?this.expand():this.collapse()};d.prototype.expand=function(){var b=a.Event("expanded.boxwidget"),d=this.options.collapseIcon,e=this.options.expandIcon;a(this.element).removeClass("collapsed-box");a(this.element).find(".box-tools").find("."+e).removeClass(e).addClass(d);var f=this;a(f.element).find(".box-body, .box-footer").slideDown(f.options.animationSpeed,function(){a(f.element).trigger(b)})};d.prototype.collapse=
function(){var b=a.Event("collapsed.boxwidget"),d=this.options.collapseIcon,e=this.options.expandIcon;a(this.element).find(".box-tools").find("."+d).removeClass(d).addClass(e);var f=this;a(f.element).find(".box-body, .box-footer").slideUp(f.options.animationSpeed,function(){a(f.element).addClass("collapsed-box");a(f.element).trigger(b)}.bind(f))};d.prototype.remove=function(){var b=a.Event("removed.boxwidget"),d=this;a(d.element).slideUp(this.options.animationSpeed,function(){a(d.element).trigger(b);
a(d.element).remove()})};d.prototype._setUpListeners=function(){var b=this;a(this.element).on("click",this.options.collapseTrigger,function(a){a&&a.preventDefault();b.toggle()});a(this.element).on("click",this.options.removeTrigger,function(a){a&&a.preventDefault();b.remove()});a(this.options.collapseTrigger).css({cursor:"pointer"});a(this.options.removeTrigger).css({cursor:"pointer"})};var b=a.fn.boxWidget;a.fn.boxWidget=f;a.fn.boxWidget.Constructor=d;a.fn.boxWidget.noConflict=function(){a.fn.boxWidget=
b;return this};a(function(){a(".box").each(function(){f.call(a(this))});a(".box-child").boxWidget({collapseTrigger:'[data-widget="collapse-child"]',removeTrigger:'[data-widget="remove-child"]'})})}(jQuery);
(function(a){a.fn.textareaAutoHieght=function(f){var g={maxHeight:null,minHeight:18*a(this).attr("rows")},d=a.extend({},g,f);return a(this).each(function(){a(this).bind("paste cut keydown keyup focus blur",function(){var a=this.style;this.style.height=d.minHeight+"px";if(this.scrollHeight>d.minHeight){if(d.maxHeight&&this.scrollHeight>d.maxHeight){var c=d.maxHeight;a.overflowY="scroll"}else c=this.scrollHeight,a.overflowY="hidden";a.height=c+"px"}}).trigger("blur")})}})(jQuery);
(function(a){a.fn.position1x=function(){if(this[0]){var a={top:0,left:0},g=this[0];if("fixed"===jQuery.css(g,"position"))var d=g.getBoundingClientRect();else{var b=this.offsetParent();d=this.offset();jQuery.nodeName(b[0],"html")||(a=b.offset());a.top+=jQuery.css(b[0],"borderTopWidth",!0);a.left+=jQuery.css(b[0],"borderLeftWidth",!0)}return{top:d.top-a.top-jQuery.css(g,"marginTop",!0),left:d.left-a.left-jQuery.css(g,"marginLeft",!0)}}}})(jQuery);
(function(a){a.fn.iframeWindow=function(){var f=a(this).find("iframe");return 0<f.length?f[0].contentWindow:null}})(jQuery);
(function(a){function f(a,b,c){var e=a[0],f=/er/.test(c)?t:/bl/.test(c)?r:l,h=c==w?{checked:e[l],disabled:e[r],indeterminate:"true"==a.attr(t)||"false"==a.attr(n)}:e[f];if(/^(ch|di|in)/.test(c)&&!h)g(a,f);else if(/^(un|en|de)/.test(c)&&h)d(a,f);else if(c==w)for(f in h)h[f]?g(a,f,!0):d(a,f,!0);else if(!b||"toggle"==c){if(!b)a[F]("ifClicked");h?e[y]!==k&&d(a,f):g(a,f)}}function g(b,f,g){var A=b[0],m=b.parent(),G=f==l,z=f==t,w=f==r,L=z?n:G?u:"enabled",q=c(b,L+h(A[y])),M=c(b,f+h(A[y]));if(!0!==A[f]){if(!g&&
f==l&&A[y]==k&&A.name){var K=b.closest("form"),H='input[name="'+A.name+'"]';H=K.length?K.find(H):a(H);H.each(function(){this!==A&&a(this).data(p)&&d(a(this),f)})}z?(A[f]=!0,A[l]&&d(b,l,"force")):(g||(A[f]=!0),G&&A[t]&&d(b,t,!1));e(b,G,f,g)}A[r]&&c(b,E,!0)&&m.find("."+v).css(E,"default");m[x](M||c(b,f)||"");w?m.attr("aria-disabled","true"):m.attr("aria-checked",z?"mixed":"true");m[D](q||c(b,L)||"")}function d(a,b,d){var f=a[0],g=a.parent(),k=b==l,p=b==t,A=b==r,z=p?n:k?u:"enabled",q=c(a,z+h(f[y])),
G=c(a,b+h(f[y]));if(!1!==f[b]){if(p||!d||"force"==d)f[b]=!1;e(a,k,z,d)}!f[r]&&c(a,E,!0)&&g.find("."+v).css(E,"pointer");g[D](G||c(a,b)||"");A?g.attr("aria-disabled","false"):g.attr("aria-checked","false");g[x](q||c(a,z)||"")}function b(b,c){if(b.data(p)){b.parent().html(b.attr("style",b.data(p).s||""));if(c)b[F](c);b.off(".i").unwrap();a(J+'[for="'+b[0].id+'"]').add(b.closest(J)).off(".i")}}function c(a,b,c){if(a.data(p))return a.data(p).o[b+(c?"":"Class")]}function h(a){return a.charAt(0).toUpperCase()+
a.slice(1)}function e(a,b,c,d){if(!d){if(b)a[F]("ifToggled");a[F]("ifChanged")[F]("if"+h(c))}}var p="iCheck",v=p+"-helper",k="radio",l="checked",u="un"+l,r="disabled",n="determinate",t="in"+n,w="update",y="type",x="addClass",D="removeClass",F="trigger",J="label",E="cursor",z=/ipad|iphone|ipod|android|blackberry|windows phone|opera mini|silk/i.test(navigator.userAgent);a.fn[p]=function(c,e){var h='input[type="checkbox"], input[type="'+k+'"]',u=a(),m=function(b){b.each(function(){var b=a(this);u=b.is(h)?
u.add(b):u.add(b.find(h))})};if(/^(check|uncheck|toggle|indeterminate|determinate|disable|enable|update|destroy)$/i.test(c))return c=c.toLowerCase(),m(this),u.each(function(){var d=a(this);"destroy"==c?b(d,"ifDestroyed"):f(d,!0,c);a.isFunction(e)&&e()});if("object"!=typeof c&&c)return this;var n=a.extend({checkedClass:l,disabledClass:r,indeterminateClass:t,checkboxClass:"icheckbox_minimal-grey",radioClass:"iradio_minimal-grey",labelHover:!0,aria:!1},c),A=n.handle,G=n.hoverClass||"hover",R=n.focusClass||
"focus",q=n.activeClass||"active",M=!!n.labelHover,K=n.labelHoverClass||"hover",H=(""+n.increaseArea).replace("%","")|0;if("checkbox"==A||A==k)h='input[type="'+A+'"]';-50>H&&(H=-50);m(this);return u.each(function(){var c=a(this);b(c);var e=this,h=e.id,m=-H+"%",u=100+2*H+"%";u={position:"absolute",top:m,left:m,display:"block",width:u,height:u,margin:0,padding:0,background:"#fff",border:0,opacity:0};m=z?{position:"absolute",visibility:"hidden"}:H?u:{position:"absolute",opacity:0};var A="checkbox"==
e[y]?n.checkboxClass||"icheckbox":n.radioClass||"i"+k,t=a(J+'[for="'+h+'"]').add(c.closest(J)),L=!!n.aria,P=p+"-"+Math.random().toString(36).replace("0.",""),B='<div class="'+A+'" '+(L?'role="'+e[y]+'" ':"");t.length&&L&&t.each(function(){B+='aria-labelledby="';this.id?B+=this.id:(this.id=P,B+=P);B+='"'});B=c.wrap(B+"/>")[F]("ifCreated").parent().append(n.insert);u=a('<ins class="'+v+'"/>').css(u).appendTo(B);c.data(p,{o:n,s:c.attr("style")}).css(m);n.inheritClass&&B[x](e.className||"");n.inheritID&&
h&&B.attr("id",p+"-"+h);"static"==B.css("position")&&B.css("position","relative");f(c,!0,w);if(t.length)t.on("click.i mouseover.i mouseout.i touchbegin.i touchend.i",function(b){var d=b[y],g=a(this);if(!e[r]){if("click"==d||"touchend"==d){if(a(b.target).is("a"))return;f(c,!1,!0)}else M&&(/ut|nd/.test(d)?(B[D](G),g[D](K)):(B[x](G),g[x](K)));if(z)b.stopPropagation();else return!1}});c.on("click.i focus.i blur.i keyup.i keydown.i keypress.i",function(a){var b=a[y];a=a.keyCode;if("click"==b)return!1;
if("keydown"==b&&32==a)return e[y]==k&&e[l]||(e[l]?d(c,l):g(c,l)),!1;if("keyup"==b&&e[y]==k)!e[l]&&g(c,l);else if(/us|ur/.test(b))B["blur"==b?D:x](R)});u.on("click mousedown mouseup mouseover mouseout touchbegin.i touchend.i",function(a){var b=a[y],d=/wn|up/.test(b)?q:G;if(!e[r]){if("click"==b)f(c,!1,!0);else{if(/wn|er|in/.test(b))B[x](d);else B[D](d+" "+q);if(t.length&&M&&d==G)t[/ut|nd/.test(b)?D:x](K)}if(z)a.stopPropagation();else return!1}})})}})(window.jQuery||window.Zepto);
(function(a,f,g){var d={delay:150};var b=function(b,f,e){"function"===typeof f&&(e=f,f={});e=e||null;this.element=b;this.settings=a.extend({},d,f);this._defaults=d;this._name="resizeEnd";this._timeout=!1;this._callback=e;return this.init()};b.prototype={init:function(){var b=this;return a(this.element).on("resize",function(){return b.initResize()})},getUTCDate:function(a){a=a||new Date;return Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),
a.getUTCMilliseconds())},initResize:function(){var a=this;a.controlTime=a.getUTCDate();if(!1===a._timeout)return a._timeout=!0,setTimeout(function(){return a.runCallback(a)},a.settings.delay)},runCallback:function(a){if(a.getUTCDate()-a.controlTime<a.settings.delay)return setTimeout(function(){return a.runCallback(a)},a.settings.delay);a._timeout=!1;return a._callback()}};return a.fn.resizeEnd=function(c,d){return this.each(function(){if(!a.data(this,"plugin_resizeEnd"))return a.data(this,"plugin_resizeEnd",
new b(this,c,d))})}})(jQuery,window,document);
!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):a("undefined"!=typeof jQuery?jQuery:window.Zepto)}(function(a){function f(b){var c=b.data;b.isDefaultPrevented()||(b.preventDefault(),a(b.target).ajaxSubmit(c))}function g(b){var c=b.target,d=a(c);if(!d.is("[type=submit],[type=image]")){c=d.closest("[type=submit]");if(0===c.length)return;c=c[0]}var e=this;if(e.clk=c,"image"==c.type)void 0!==b.offsetX?(e.clk_x=b.offsetX,e.clk_y=b.offsetY):"function"==typeof a.fn.offset?(d=d.offset(),
e.clk_x=b.pageX-d.left,e.clk_y=b.pageY-d.top):(e.clk_x=b.pageX-c.offsetLeft,e.clk_y=b.pageY-c.offsetTop);setTimeout(function(){e.clk=e.clk_x=e.clk_y=null},100)}function d(){if(a.fn.ajaxSubmit.debug){var b="[jquery.form] "+Array.prototype.join.call(arguments,"");window.console&&window.console.log?window.console.log(b):window.opera&&window.opera.postError&&window.opera.postError(b)}}var b=void 0!==a("<input type='file'/>").get(0).files;var c=void 0!==window.FormData;var h=!!a.fn.prop;a.fn.attr2=function(){if(!h)return this.attr.apply(this,
arguments);var a=this.prop.apply(this,arguments);return a&&a.jquery||"string"==typeof a?a:this.attr.apply(this,arguments)};a.fn.ajaxSubmit=function(e){function f(b){var c=a.param(b,e.traditional).split("&"),d=c.length,f=[];for(b=0;d>b;b++){c[b]=c[b].replace(/\+/g," ");var g=c[b].split("=");f.push([decodeURIComponent(g[0]),decodeURIComponent(g[1])])}return f}function g(b){for(var c=new FormData,d=0;d<b.length;d++)c.append(b[d].name,b[d].value);if(e.extraData)for(b=f(e.extraData),d=0;d<b.length;d++)b[d]&&
c.append(b[d][0],b[d][1]);e.data=null;d=a.extend(!0,{},a.ajaxSettings,e,{contentType:!1,processData:!1,cache:!1,type:u||"POST"});e.uploadProgress&&(d.xhr=function(){var b=a.ajaxSettings.xhr();return b.upload&&b.upload.addEventListener("progress",function(a){var b=0,c=a.loaded||a.position,d=a.total;a.lengthComputable&&(b=Math.ceil(c/d*100));e.uploadProgress(a,c,d,b)},!1),b});d.data=null;var g=d.beforeSend;return d.beforeSend=function(a,b){b.data=e.formData?e.formData:c;g&&g.call(this,a,b)},a.ajax(d)}
function k(b){function c(a){var b=null;try{a.contentWindow&&(b=a.contentWindow.document)}catch(N){d("cannot get iframe.contentWindow document: "+N)}if(b)return b;try{b=a.contentDocument?a.contentDocument:a.document}catch(N){d("cannot get iframe.contentDocument: "+N),b=a.document}return b}function f(){function b(){try{var a=c(n).readyState;d("state = "+a);a&&"uninitialized"==a.toLowerCase()&&setTimeout(b,50)}catch(Q){d("Server abort: ",Q," (",Q.name,")"),g(D),x&&clearTimeout(x),x=void 0}}var e=l.attr2("target"),
f=l.attr2("action"),h=l.attr("enctype")||l.attr("encoding")||"multipart/form-data";z.setAttribute("target",v);u&&!/post/i.test(u)||z.setAttribute("method","POST");f!=m.url&&z.setAttribute("action",m.url);m.skipEncodingOverride||u&&!/post/i.test(u)||l.attr({encoding:"multipart/form-data",enctype:"multipart/form-data"});m.timeout&&(x=setTimeout(function(){y=!0;g(E)},m.timeout));var k=[];try{if(m.extraData)for(var p in m.extraData)m.extraData.hasOwnProperty(p)&&k.push(a.isPlainObject(m.extraData[p])&&
m.extraData[p].hasOwnProperty("name")&&m.extraData[p].hasOwnProperty("value")?a('<input type="hidden" name="'+m.extraData[p].name+'">').val(m.extraData[p].value).appendTo(z)[0]:a('<input type="hidden" name="'+p+'">').val(m.extraData[p]).appendTo(z)[0]);m.iframeTarget||r.appendTo("body");n.attachEvent?n.attachEvent("onload",g):n.addEventListener("load",g,!1);setTimeout(b,15);try{z.submit()}catch(V){document.createElement("form").submit.apply(z)}}finally{z.setAttribute("action",f),z.setAttribute("enctype",
h),e?z.setAttribute("target",e):l.removeAttr("target"),a(k).remove()}}function g(b){if(!q.aborted&&!J){if(C=c(n),C||(d("cannot access response document"),b=D),b===E&&q)return q.abort("timeout"),void I.reject(q,"timeout");if(b==D&&q)return q.abort("server abort"),void I.reject(q,"error","server abort");if(C&&C.location.href!=m.iframeSrc||y){n.detachEvent?n.detachEvent("onload",g):n.removeEventListener("load",g,!1);var e;b="success";try{if(y)throw"timeout";var f="xml"==m.dataType||C.XMLDocument||a.isXMLDoc(C);
if(d("isXml="+f),!f&&window.opera&&(null===C.body||!C.body.innerHTML)&&--S)return d("requeing onLoad callback, DOM not available"),void setTimeout(g,250);var k=C.body?C.body:C.documentElement;q.responseText=k?k.innerHTML:null;q.responseXML=C.XMLDocument?C.XMLDocument:C;f&&(m.dataType="xml");q.getResponseHeader=function(a){return{"content-type":m.dataType}[a.toLowerCase()]};k&&(q.status=Number(k.getAttribute("status"))||q.status,q.statusText=k.getAttribute("statusText")||q.statusText);var h=(m.dataType||
"").toLowerCase(),l=/(json|script|text)/.test(h);if(l||m.textarea){var v=C.getElementsByTagName("textarea")[0];if(v)q.responseText=v.value,q.status=Number(v.getAttribute("status"))||q.status,q.statusText=v.getAttribute("statusText")||q.statusText;else if(l){var u=C.getElementsByTagName("pre")[0],t=C.getElementsByTagName("body")[0];u?q.responseText=u.textContent?u.textContent:u.innerText:t&&(q.responseText=t.textContent?t.textContent:t.innerText)}}else"xml"==h&&!q.responseXML&&q.responseText&&(q.responseXML=
T(q.responseText));try{F=U(q,h,m)}catch(O){b="parsererror",q.error=e=O||b}}catch(O){d("error caught: ",O),b="error",q.error=e=O||b}q.aborted&&(d("upload aborted"),b=null);q.status&&(b=200<=q.status&&300>q.status||304===q.status?"success":"error");"success"===b?(m.success&&m.success.call(m.context,F,"success",q),I.resolve(q.responseText,"success",q),p&&a.event.trigger("ajaxSuccess",[q,m])):b&&(void 0===e&&(e=q.statusText),m.error&&m.error.call(m.context,q,b,e),I.reject(q,"error",e),p&&a.event.trigger("ajaxError",
[q,m,e]));p&&a.event.trigger("ajaxComplete",[q,m]);p&&!--a.active&&a.event.trigger("ajaxStop");m.complete&&m.complete.call(m.context,q,b);J=!0;m.timeout&&clearTimeout(x);setTimeout(function(){m.iframeTarget?r.attr("src",m.iframeSrc):r.remove();q.responseXML=null},100)}}}var k,m,p,v,r,n,q,t,y,x,z=l[0],I=a.Deferred();if(I.abort=function(a){q.abort(a)},b)for(k=0;k<w.length;k++)b=a(w[k]),h?b.prop("disabled",!1):b.removeAttr("disabled");if(m=a.extend(!0,{},a.ajaxSettings,e),m.context=m.context||m,v="jqFormIO"+
(new Date).getTime(),m.iframeTarget?(r=a(m.iframeTarget),t=r.attr2("name"),t?v=t:r.attr2("name",v)):(r=a('<iframe name="'+v+'" src="'+m.iframeSrc+'" />'),r.css({position:"absolute",top:"-1000px",left:"-1000px"})),n=r[0],q={aborted:0,responseText:null,responseXML:null,status:0,statusText:"n/a",getAllResponseHeaders:function(){},getResponseHeader:function(){},setRequestHeader:function(){},abort:function(b){var c="timeout"===b?"timeout":"aborted";d("aborting upload... "+c);this.aborted=1;try{n.contentWindow.document.execCommand&&
n.contentWindow.document.execCommand("Stop")}catch(N){}r.attr("src",m.iframeSrc);q.error=c;m.error&&m.error.call(m.context,q,c,b);p&&a.event.trigger("ajaxError",[q,m,c]);m.complete&&m.complete.call(m.context,q,c)}},p=m.global,p&&0===a.active++&&a.event.trigger("ajaxStart"),p&&a.event.trigger("ajaxSend",[q,m]),m.beforeSend&&!1===m.beforeSend.call(m.context,q,m))return m.global&&a.active--,I.reject(),I;if(q.aborted)return I.reject(),I;(b=z.clk)&&(t=b.name,t&&!b.disabled&&(m.extraData=m.extraData||{},
m.extraData[t]=b.value,"image"==b.type&&(m.extraData[t+".x"]=z.clk_x,m.extraData[t+".y"]=z.clk_y)));var E=1,D=2;t=a("meta[name=csrf-token]").attr("content");(b=a("meta[name=csrf-param]").attr("content"))&&t&&(m.extraData=m.extraData||{},m.extraData[b]=t);m.forceSync?f():setTimeout(f,10);var F,C,J,S=50,T=a.parseXML||function(a,b){return window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a)):b=(new DOMParser).parseFromString(a,"text/xml"),b&&b.documentElement&&"parsererror"!=
b.documentElement.nodeName?b:null},B=a.parseJSON||function(a){return window.eval("("+a+")")},U=function(b,c,d){var e=b.getResponseHeader("content-type")||"",f="xml"===c||!c&&0<=e.indexOf("xml");b=f?b.responseXML:b.responseText;return f&&"parsererror"===b.documentElement.nodeName&&a.error&&a.error("parsererror"),d&&d.dataFilter&&(b=d.dataFilter(b,c)),"string"==typeof b&&("json"===c||!c&&0<=e.indexOf("json")?b=B(b):("script"===c||!c&&0<=e.indexOf("javascript"))&&a.globalEval(b)),b};return I}if(!this.length)return d("ajaxSubmit: skipping submit process - no element selected"),
this;var l=this;"function"==typeof e?e={success:e}:void 0===e&&(e={});var u=e.type||this.attr2("method");var r=e.url||this.attr2("action");(r=(r="string"==typeof r?a.trim(r):"")||window.location.href||"")&&(r=(r.match(/^([^#]+)/)||[])[1]);e=a.extend(!0,{url:r,success:a.ajaxSettings.success,type:u||a.ajaxSettings.type,iframeSrc:/^https/i.test(window.location.href||"")?"javascript:false":"about:blank"},e);r={};if(this.trigger("form-pre-serialize",[this,e,r]),r.veto)return d("ajaxSubmit: submit vetoed via form-pre-serialize trigger"),
this;if(e.beforeSerialize&&!1===e.beforeSerialize(this,e))return d("ajaxSubmit: submit aborted via beforeSerialize callback"),this;var n=e.traditional;void 0===n&&(n=a.ajaxSettings.traditional);var t,w=[],y=this.formToArray(e.semantic,w);if(e.data&&(e.extraData=e.data,t=a.param(e.data,n)),e.beforeSubmit&&!1===e.beforeSubmit(y,this,e))return d("ajaxSubmit: submit aborted via beforeSubmit callback"),this;if(this.trigger("form-submit-validate",[y,this,e,r]),r.veto)return d("ajaxSubmit: submit vetoed via form-submit-validate trigger"),
this;r=a.param(y,n);t&&(r=r?r+"&"+t:t);"GET"==e.type.toUpperCase()?(e.url+=(0<=e.url.indexOf("?")?"&":"?")+r,e.data=null):e.data=r;var x=[];if(e.resetForm&&x.push(function(){l.resetForm()}),e.clearForm&&x.push(function(){l.clearForm(e.includeHidden)}),!e.dataType&&e.target){var D=e.success||function(){};x.push(function(b){var c=e.replaceTarget?"replaceWith":"html";a(e.target)[c](b).each(D,arguments)})}else e.success&&x.push(e.success);if(e.success=function(a,b,c){for(var d=e.context||this,f=0,g=x.length;g>
f;f++)x[f].apply(d,[a,b,c||l,l])},e.error){var F=e.error;e.error=function(a,b,c){F.apply(e.context||this,[a,b,c,l])}}if(e.complete){var J=e.complete;e.complete=function(a,b){J.apply(e.context||this,[a,b,l])}}t=0<a("input[type=file]:enabled",this).filter(function(){return""!==a(this).val()}).length;r="multipart/form-data"==l.attr("enctype")||"multipart/form-data"==l.attr("encoding");n=b&&c;d("fileAPI :"+n);var E;!1!==e.iframe&&(e.iframe||(t||r)&&!n)?e.closeKeepAlive?a.get(e.closeKeepAlive,function(){E=
k(y)}):E=k(y):E=(t||r)&&n?g(y):a.ajax(e);l.removeData("jqxhr").data("jqxhr",E);for(t=0;t<w.length;t++)w[t]=null;return this.trigger("form-submit-notify",[this,e]),this};a.fn.ajaxForm=function(b){if(b=b||{},b.delegation=b.delegation&&a.isFunction(a.fn.on),!b.delegation&&0===this.length){var c=this.selector,e=this.context;return!a.isReady&&c?(d("DOM not ready, queuing ajaxForm"),a(function(){a(c,e).ajaxForm(b)}),this):(d("terminating; zero elements found by selector"+(a.isReady?"":" (DOM not ready)")),
this)}return b.delegation?(a(document).off("submit.form-plugin",this.selector,f).off("click.form-plugin",this.selector,g).on("submit.form-plugin",this.selector,b,f).on("click.form-plugin",this.selector,b,g),this):this.ajaxFormUnbind().bind("submit.form-plugin",b,f).bind("click.form-plugin",b,g)};a.fn.ajaxFormUnbind=function(){return this.unbind("submit.form-plugin click.form-plugin")};a.fn.formToArray=function(c,d){var e=[];if(0===this.length)return e;var f,g=this[0],h=this.attr("id"),p=c?g.getElementsByTagName("*"):
g.elements;if(p&&!/MSIE [678]/.test(navigator.userAgent)&&(p=a(p).get()),h&&(f=a(':input[form="'+h+'"]').get(),f.length&&(p=(p||[]).concat(f))),!p||!p.length)return e;var n,t,w,y,x;f=0;for(y=p.length;y>f;f++)if(w=p[f],n=w.name,n&&!w.disabled)if(c&&g.clk&&"image"==w.type)g.clk==w&&(e.push({name:n,value:a(w).val(),type:w.type}),e.push({name:n+".x",value:g.clk_x},{name:n+".y",value:g.clk_y}));else if(t=a.fieldValue(w,!0),t&&t.constructor==Array)for(d&&d.push(w),h=0,x=t.length;x>h;h++)e.push({name:n,
value:t[h]});else if(b&&"file"==w.type)if(d&&d.push(w),x=w.files,x.length)for(h=0;h<x.length;h++)e.push({name:n,value:x[h],type:w.type});else e.push({name:n,value:"",type:w.type});else null!==t&&"undefined"!=typeof t&&(d&&d.push(w),e.push({name:n,value:t,type:w.type,required:w.required}));!c&&g.clk&&(c=a(g.clk),d=c[0],(n=d.name)&&!d.disabled&&"image"==d.type&&(e.push({name:n,value:c.val()}),e.push({name:n+".x",value:g.clk_x},{name:n+".y",value:g.clk_y})));return e};a.fn.formSerialize=function(b){return a.param(this.formToArray(b))};
a.fn.fieldSerialize=function(b){var c=[];return this.each(function(){var d=this.name;if(d){var e=a.fieldValue(this,b);if(e&&e.constructor==Array)for(var f=0,g=e.length;g>f;f++)c.push({name:d,value:e[f]});else null!==e&&"undefined"!=typeof e&&c.push({name:this.name,value:e})}}),a.param(c)};a.fn.fieldValue=function(b){for(var c=[],d=0,e=this.length;e>d;d++){var f=a.fieldValue(this[d],b);null===f||"undefined"==typeof f||f.constructor==Array&&!f.length||(f.constructor==Array?a.merge(c,f):c.push(f))}return c};
a.fieldValue=function(b,c){var d=b.name,e=b.type,f=b.tagName.toLowerCase();if(void 0===c&&(c=!0),c&&(!d||b.disabled||"reset"==e||"button"==e||("checkbox"==e||"radio"==e)&&!b.checked||("submit"==e||"image"==e)&&b.form&&b.form.clk!=b||"select"==f&&-1==b.selectedIndex))return null;if("select"==f){f=b.selectedIndex;if(0>f)return null;c=[];b=b.options;d=(e="select-one"==e)?f+1:b.length;for(f=e?f:0;d>f;f++){var g=b[f];if(g.selected){var h=g.value;if(h||(h=g.attributes&&g.attributes.value&&!g.attributes.value.specified?
g.text:g.value),e)return h;c.push(h)}}return c}return a(b).val()};a.fn.clearForm=function(b){return this.each(function(){a("input,select,textarea",this).clearFields(b)})};a.fn.clearFields=a.fn.clearInputs=function(b){var c=/^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i;return this.each(function(){var d=this.type,e=this.tagName.toLowerCase();c.test(d)||"textarea"==e?this.value="":"checkbox"==d||"radio"==d?this.checked=!1:"select"==e?this.selectedIndex=
-1:"file"==d?/MSIE/.test(navigator.userAgent)?a(this).replaceWith(a(this).clone(!0)):a(this).val(""):b&&(!0===b&&/hidden/.test(d)||"string"==typeof b&&a(this).is(b))&&(this.value="")})};a.fn.resetForm=function(){return this.each(function(){("function"==typeof this.reset||"object"==typeof this.reset&&!this.reset.nodeType)&&this.reset()})};a.fn.enable=function(a){return void 0===a&&(a=!0),this.each(function(){this.disabled=!a})};a.fn.selected=function(b){return void 0===b&&(b=!0),this.each(function(){var c=
this.type;"checkbox"==c||"radio"==c?this.checked=b:"option"==this.tagName.toLowerCase()&&(c=a(this).parent("select"),b&&c[0]&&"select-one"==c[0].type&&c.find("option").selected(!1),this.selected=b)})};a.fn.ajaxSubmit.debug=!1});
!function(a,f){var g=a();a.fn.dropdownHover=function(d){return"ontouchstart"in document?this:(g=g.add(this.parent()),this.each(function(){function b(){e.parents(".navbar").find(".navbar-toggle").is(":visible")||(f.clearTimeout(c),f.clearTimeout(h),h=f.setTimeout(function(){g.find(":focus").blur();!0===l.instantlyCloseOthers&&g.removeClass("open");f.clearTimeout(h);e.attr("aria-expanded","true");p.addClass("open");e.trigger(k)},l.hoverDelay))}var c,h,e=a(this),p=e.parent(),v={delay:a(this).data("delay"),
hoverDelay:a(this).data("hover-delay"),instantlyCloseOthers:a(this).data("close-others")},k="show.bs.dropdown",l=a.extend(!0,{},{delay:500,hoverDelay:0,instantlyCloseOthers:!0},d,v);p.hover(function(a){return p.hasClass("open")||e.is(a.target)?void b(a):!0},function(){f.clearTimeout(h);c=f.setTimeout(function(){e.attr("aria-expanded","false");p.removeClass("open");e.trigger("hide.bs.dropdown")},l.delay)});e.hover(function(a){return p.hasClass("open")||p.is(a.target)?void b(a):!0});p.find(".dropdown-submenu").each(function(){var b,
c=a(this);c.hover(function(){f.clearTimeout(b);c.children(".dropdown-menu").show();c.siblings().children(".dropdown-menu").hide()},function(){var a=c.children(".dropdown-menu");b=f.setTimeout(function(){a.hide()},l.delay)})})}))};a(document).ready(function(){a('[data-hover="dropdown"]').dropdownHover()})}(jQuery,window);
!function(){var a={open:"{{",close:"}}"},f={exp:function(a){return new RegExp(a,"g")},query:function(b,d,e){return g((d||"")+a.open+["#([\\s\\S])+?","([^{#}])*?"][b||0]+a.close+(e||""))},escape:function(a){return String(a||"").replace(/&(?!#?[a-zA-Z0-9]+;)/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/'/g,"&#39;").replace(/"/g,"&quot;")},error:function(a,b){return"object"==typeof console&&console.error("Laytpl Error\uff1a"+a+"\n"+(b||"")),"Laytpl Error\uff1a"+a}},g=f.exp,d=function(a){this.tpl=
a};d.pt=d.prototype;window.errors=0;d.pt.parse=function(b,d){var c=b,h=g("^"+a.open+"#",""),v=g(a.close+"$","");b=b.replace(/\s+|\r|\t|\n/g," ").replace(g(a.open+"#"),a.open+"# ").replace(g(a.close+"}"),"} "+a.close).replace(/\\/g,"\\\\").replace(/(?="|')/g,"\\").replace(f.query(),function(a){return a=a.replace(h,"").replace(v,""),'";'+a.replace(/\\/g,"")+';view+="'}).replace(f.query(1),function(b){var c='"+(';return b.replace(/\s/g,"")===a.open+a.close?"":(b=b.replace(g(a.open+"|"+a.close),""),/^=/.test(b)&&
(b=b.replace(/^=/,""),c='"+_escape_('),c+b.replace(/\\/g,"")+')+"')});b='"use strict";var view = "'+b+'";return view;';try{return this.cache=b=new Function("d, _escape_",b),b(d,f.escape)}catch(k){return delete this.cache,f.error(k,c)}};d.pt.render=function(a,b){var c;return a?(c=this.cache?this.cache(a,f.escape):this.parse(this.tpl,a),b?void b(c):c):f.error("no data")};var b=function(a){return"string"!=typeof a?f.error("Template not found"):new d(a)};b.config=function(b){b=b||{};for(var c in b)a[c]=
b[c]};b.v="1.2";"function"==typeof define?define(function(){return b}):"undefined"!=typeof exports?module.exports=b:window.laytpl=b}();
(function(){this.Base64=new function(){_keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";this.encode=function(a){var f="";if(!a||""==a)return f;var g=0;for(a=_utf8_encode(a);g<a.length;){var d=a.charCodeAt(g++);var b=a.charCodeAt(g++);var c=a.charCodeAt(g++);var h=d>>2;d=(d&3)<<4|b>>4;var e=(b&15)<<2|c>>6;var p=c&63;isNaN(b)?e=p=64:isNaN(c)&&(p=64);f=f+_keyStr.charAt(h)+_keyStr.charAt(d)+_keyStr.charAt(e)+_keyStr.charAt(p)}return f};this.decode=function(a){var f="";if(!a||
""==a)return f;var g=0;for(a=a.replace(/[^A-Za-z0-9\+\/=]/g,"");g<a.length;){var d=_keyStr.indexOf(a.charAt(g++));var b=_keyStr.indexOf(a.charAt(g++));var c=_keyStr.indexOf(a.charAt(g++));var h=_keyStr.indexOf(a.charAt(g++));d=d<<2|b>>4;b=(b&15)<<4|c>>2;var e=(c&3)<<6|h;f+=String.fromCharCode(d);64!=c&&(f+=String.fromCharCode(b));64!=h&&(f+=String.fromCharCode(e))}return f=_utf8_decode(f)};_utf8_encode=function(a){a=a.replace(/\r\n/g,"\n");for(var f="",g=0;g<a.length;g++){var d=a.charCodeAt(g);128>
d?f+=String.fromCharCode(d):(127<d&&2048>d?f+=String.fromCharCode(d>>6|192):(f+=String.fromCharCode(d>>12|224),f+=String.fromCharCode(d>>6&63|128)),f+=String.fromCharCode(d&63|128))}return f};_utf8_decode=function(a){var f="",g=0;for(c1=c2=0;g<a.length;){var d=a.charCodeAt(g);128>d?(f+=String.fromCharCode(d),g++):191<d&&224>d?(c2=a.charCodeAt(g+1),f+=String.fromCharCode((d&31)<<6|c2&63),g+=2):(c2=a.charCodeAt(g+1),c3=a.charCodeAt(g+2),f+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),g+=3)}return f}}})();
